### ISSUE TITLE
Same architecture: lipo is unhappy

### ISSUE THREAD

**Issue by vessenes** [part-cw/lambdanative#101]
I'm quite a bit further down the build process at this point. I'm not clear on why both of these architectures should be built, but I'm not savvy at building on darwin. Is this a make script error, a configuration error on my part?

```bash
admin$ make
[snip]
==> creating ios loader needed for Calculator..
fatal error: /Library/Developer/CommandLineTools/usr/bin/lipo: /Users/admin/Library/Caches/lambdanative/ios/arm64/lib/libpayload.a and /Users/admin/Library/Caches/lambdanative/ios/armv7/lib/libpayload.a have the same architectures (x86_64) and can't be in the same fat output file
ERROR: failed on file /Users/admin/Library/Caches/lambdanative/ios/libpayload-fat.a
>> lipo failed to create fat payload
```

Here's my gcc --version results:

```bash
admin$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

**Comment by mgorges** [comment]
@vessenes: There seem to be a few things wrong in your setup: Apple requires you to build for two architectures (armv7 and arm64) to submit iOS apps to the App Store. This only works when using the llvm compiler. However, your error messages states that you are trying to compile both for the `x86_64` platform, which is obviously wrong. Did you link gcc into your path or modify the target files for ios?

For a start, could you recompile with `verbose` enabled, and post the full log as a https://gist.github.com/ ? - e.g. like this: `./configure Calculator ios verbose; make;`

Thanks Matthias

**Comment by vessenes** [comment]
Will do. I am hypothesizing my previous borked installation resulted in a bad cache directory and I just wiped it and am rebuilding. I will update on that and your suggestions when finished.

**Comment by vessenes** [comment]
Here's a gist. This is after an ```rm -rf ~/Library/Caches/lambdanative/```. https://gist.github.com/vessenes/12f7dc3a7c5074b6e5c2

**Comment by vessenes** [comment]
Further update: looks possible that compiling libgambit is happening with gcc-5 here. Sit tight.

**Comment by mgorges** [comment]
Your Gist seems to be calling `llvm` in some places - give me a bit more time to read them properly.

**Comment by vessenes** [comment]
I turned on verbose, wiped the cache and made sure I was calling llvm everywhere. The debug file was verbose with over 10k warnings. But, it seems to compile, and now fails on a codesign error. I will see if I can figure out how to get this sorted, but for now I'm going to close this as essentially a waste of time coming from a bad dev environment. Thanks for the help, greatly appreciated.

**Comment by mgorges** [comment]
I am a bit puzzled by your Gist. The first thing my system does after scrubbing the cache is to rebuild the entire toolchain, followed by a build of some required applications for the native platform.

**Comment by mgorges** [comment]
Wait  - if you get to the part with the codesign error you are good and all is working. You need to follow the instructions regarding the patching of the codesign

**Comment by vessenes** [comment]
Great news. Do you have written instructions somewhere? Do I need to export the certs from Xcode?

**Comment by mgorges** [comment]
the error message at the end tells you how to do it, or if it doesn't we didn't detect your version of OSX correctly. The message is in [targets/ios/package](..//blob/master/targets/ios/package) line 56. The path will depend on your setup but for me it is 

    ** ERROR: You must edit /Applications/Xcode.app/Contents/Developer/Platforms
    /iPhoneOS.platform/Developer/usr/bin/PackageApplication to codesign with --no-strict 
    Like this (two occurrences):
    runCmd("/usr/bin/codesign", "--verify", "--no-strict", "-vvvv", , $plugin );

**Comment by vessenes** [comment]
Got it. Thank you. Mine said

```bash
=== BUILD TARGET Calculator OF PROJECT Calculator WITH CONFIGURATION Release ===

Check dependencies
Code Sign error: No matching codesigning identity found: No codesigning identities (i.e. certificate and private key pairs) matching "sample@sample.com" were found.

```

**Comment by mgorges** [comment]
Could you post me your `sw_vers -productVersion` so I can fix the check in line 53?

**Comment by vessenes** [comment]
```bash
$ sw_vers -productVersion
10.11.1
```

**Comment by vessenes** [comment]
Unfortunately I have to leave off now; I'll be back at it tomorrow, hopefully with more success.

**Comment by mgorges** [comment]
Based on your `codesign` error I feel you don't have your `PROFILE` file setup right. It needs to match an actual entry in your keychain, e.g. this are the two relevant lines from mine:

    # iOS release (SYS_IOSRELCERT) and development (SYS_IOSDEVCERT) names:
    SYS_IOSRELCERT="iPhone Distribution: PART BC Children's (AEU86A42UQ)"
    SYS_IOSDEVCERT="iPhone Developer: PART BC Children's (GX24E4ENF7)"

**Comment by vessenes** [comment]
For those who find this thread, I had to do three things.

1. Re-download Apple's Developer Cert (one of mine was expired) at https://www.apple.com/certificateauthority/

2. Re-download my own distribution and development certs and import them to my local user's keychain

3. Load the "Keychain Access" app on my mac, and search for iPhone, then copy the full text of the title into the PROFILE file. 

Things now build smoothly! Thanks for the guidance @mgorges.

**Comment by mgorges** [comment]
@vessenes If you could use this example to expand upon the documentation in the Wiki I'd be grateful.

**Comment by vessenes** [comment]
No problem. I just put in a step 4 in the ios section of Getting Started. I think that's probably the meat of it; let me know if you'd like more detail.
