### ISSUE TITLE
how to package assets?

### ISSUE THREAD

**Issue by absrnd** [part-cw/lambdanative#105]
Hi - How can I package assets to be included by 'make install'.

I'm looking for a way to include files that will be loaded by the program at runtime.

Thanks,
Stuart.

**Comment by clpetersen** [comment]
Hi Stuart,

you can place your asset files in the app source directory and point to them with an EMBED configuration file, as described here
https://github.com/part-cw/lambdanative/wiki/EMBED
This packaging scheme works on all platforms.

Chris

**Comment by absrnd** [comment]
Perfect! thanks.
