### ISSUE TITLE
Is it possible to have more files than just main.scm?

### ISSUE THREAD

**Issue by kreely** [part-cw/lambdanative#110]
Hi,
I'm wanting to break up some of my app logic into other files, rather than having it all in main.scm.
Is this possible? If it is, how is it done?
Thanks & Regards

**Comment by kreely** [comment]
Hi,
My apologies. I think this can be done using modules.
I think you can ignore my previous request.
Regards.....

**Comment by mgorges** [comment]
Of course - just use `(include "somefilename.scm")` in your `main.scm`. An example of a file, which includes multiple other files, can be seen in [modules/timestamp/timestamp.scm](../tree/master/modules/timestamp/timestamp.scm)

**Comment by kreely** [comment]
Ah, that's more sensible. Thanks for that.
