### ISSUE TITLE
iphone 6 vs Android Performance

### ISSUE THREAD

**Issue by VincentToups** [part-cw/lambdanative#112]
My codebase seems to perform significantly more poorly on the iPhone 6 when compared to the Samsung SM-G800F android device, both of which have a processor running at 1.4Gz. The performance difference is large enough to be noticeable in the frame rate: the game plays very smoothly on the Android device but feels jerky on iOS. I can try to quantify this by frame rate, if that would be helpful. 

This issue raises two questions: 
1. is there any good advice for performance profiling a lambdanative app?
2. are there any compiler flags I might try to adjust to fix the performance difference?

**Comment by clpetersen** [comment]
The iOS frame rate is determined by the `animationInterval` in `loaders/ios/EAGLView.m`, currently
```
   animationInterval = 1.0 / 20.0;
```
Try if setting this to something like 1/60. solves your problem.

**Comment by VincentToups** [comment]
Wonderful - that does it!
