### ISSUE TITLE
Getting a debug environment working from exe created from gsc is hard to do

### ISSUE THREAD

**Issue by kreely** [part-cw/lambdanative#115]
Hi,
I'm building on Linux. I have my main.scm compiled via gsc then gcc. I have a scheme file with interpreted code in it that I want to test with, so I don't have to go through a compile cycle each time I make a change.
...However, if I reference an uninitialised variable in the interpreted code or make a general silly error, I don't get a REPL, a stack trace or anything useful. I simply get "segmentation fault".

Is there a way to get a relatively resilient executable?
If not is there at least a way to get a stack trace?
I've added (declare (safe) (debug)... other debug options) and I've tried doing export SYS_MODE=debug before doing a build, but I still get a segmentation fault.

Is there something I've missed? It would be nice to get a bit of info or perhaps not even crash, but report an error and allow the exe to continue on. Is this possible?

Any help appreciated.
Thanks
David

**Comment by clpetersen** [comment]
If you compile a file containing e.g. `(load "myfile.scm")` with gsc, and your interpreted code in `myfile.scm` has bugs, this will indeed cause a segmentation fault at runtime. You can avoid this by catching the exception, like so
```
(with-exception-catcher (lambda (e) #f) (lambda () (load "myfile.scm")))
```
which will silently ignore the buggy code and carry on without throwing the fault. If you want to know what went wrong you can print the exception:
```
(with-exception-catcher (lambda (e) (for-each display (list (exception->string e) "\n"))  #f) (lambda () (load "test.scm")))
```
assuming that you are using lambdanative (it sounds like you are calling gsc directly, which will then only support the standard Gambit functions). Hope that helps.

**Comment by kreely** [comment]
Hi ClPetersen,
Thanks for that. Using the 2nd with-exception-catcher, I end up with a sensible error messages and no crash if I try to use an unbound variable in a loaded script.
If I call a precompiled function with an unbound var, I still seem to get errors, but I kind of would have expected that.
Would be nice to get around the issue with calling a precompiled function, but what you've given me is a large improvement.
Is it possible to get a callstack?
Thanks again.
Regards,
David

**Comment by mgorges** [comment]
@kreely I am not sure if I understand your question correctly but there might be two things for you to consider - in the meantime we'll have a look at the callstack question:
a) Build your main application in debug mode - DemoConsole might be good as it contains a REPL. E.g. `./configure DemoConsole debug;make;make install`
b) Look into the application's `log` folder, and if there isn't one by default create one. E.g. `cd ~/Desktop/DemoConsole/; mkdir -p log; ./DemoConsole` which might show you the crash reason:

    mg@kanonia ~/Desktop/DemoConsole $cat log/*
    [SYSTEM] 2016-06-28 00:42:45: Git hash lambdanative: c2b1fc4,parts: 2650622,lnHealth: 53b7356,
    [ERROR] 2016-06-28 00:42:45: primordial: (display): Wrong number of arguments passed to procedure
    [ERROR] 2016-06-28 00:42:45: trace: /home/mg/documents/Programming/lambdanative/apps/DemoConsole/main.scm line=41 col=1
    [ERROR] 2016-06-28 00:42:45: HALT

**Comment by clpetersen** [comment]
Just to follow up on this - compiling the program with debug information is not going to help much in the situation where the buggy code is loaded and interpreted at runtime. The trace will just point to the location of the load instruction in the program. There might be a proper way of doing this that I'm not aware of. I guess you could try evaluating the expressions in the file individually, something like
```
(with-input-from-file "myfile.scm" (lambda ()
  (let loop ((exp (read))(exp_1 ""))
    (if (eof-object? exp) #t (begin
     (with-exception-catcher
       (lambda (e)
         (for-each display (list  (exception->string e) "\n"
           "trace: " exp "\ntrace: " exp_1 "\n"))
         #f)
     (lambda () (eval exp)))
     (loop (read) exp))))))
```
That's not ideal admittedly, and not useful if the error is buried deep in a complex expression.
