### ISSUE TITLE
ln_repl questions

### ISSUE THREAD

**Issue by fungiblecog** [part-cw/lambdanative#117]
I have a couple of questions regarding the ln_repl module, which appears to work differently (with fewer features) from the repl code in the gambit sources.

1) It does not allow some special forms  such as "include" and "define-macro" to be used. Is this by design? If so why? It is a small modification to make it a top-level repl and  enable these.

2) When an error is encountered the repl does not drop into a nested debug-repl. Again I wonder why?

Thanks

**Comment by mgorges** [comment]
@fungiblecog we primarily use modified versions of [DemoConsole](../blob/master/apps/DemoConsole/main.scm) if we need a local REPL for testing, while for remote REPL-like features we use the [rupi](../wiki/Index-of-Module-rupi) module. Also we don't use macros internally. Hence, if you wanted to contribute some modifications to the [ln-repl](../blob/master/modules/ln_repl/ln_repl.scm) module we would welcome a pull-request. Many Thanks!

**Comment by fungiblecog** [comment]
Ok, I will submit something when I'm happy with it.

**Comment by fungiblecog** [comment]
I've been working on enhancements for the repl module on linux and it's working fine so I thought I'd test on some other platforms. I tried to get ln_repl working on the android emulator, but when i telnet i immediately get a 'disconnected by server' error. Before I investigate my setup can you tell me - has the ln_repl module been confirmed as working on Android?

**Comment by clpetersen** [comment]
I just tried the current ln_repl on Android (real device, not emulator).. it works fine, but needed permissions to be accessed remotely. Added in commit f181a8e

**Comment by fungiblecog** [comment]
Great. Now confirmed also working on the android emulator on linux.
