### ISSUE TITLE
Question about copyright and notices

### ISSUE THREAD

**Issue by fungiblecog** [part-cw/lambdanative#123]
I'm putting together some enhancements for the ln_repl module that I would like to submit for inclusion, and I've found some useful code in the gambit sources (specifically in a test file). I'm not sure how to proceed, should I:

a) copy the functions I need into my own file, and add a reference to the original source
b) copy the whole file - so as to retain the existing copyright notice - and comment-out the parts I don't need
c) something else

Thanks

**Comment by mgorges** [comment]
@fungiblecog - we'll currently only accept code that will be using the `3-clause BSD` license (or a more liberal one), which is the overarching [LICENSE](../blob/master/lambdanative/blob/master/LICENSE) for `LambdaNative`. However, `Gambit` is dual licensed as [LGPL](https://github.com/gambit/gambit/blob/master/LGPL.txt) and [Apache 2](https://github.com/gambit/gambit/blob/master/LICENSE-2.0.txt) so you can't just copy the code here. 

In the past, when we considered adding pieces from Gambit, we approached @feeley (as the copyright holder) and requested if he was willing to re-license a certain piece as `3-clause BSD`. He graciously did so for a few pieces, e.g. [modules/base64/base64.scm](../blob/master/modules/base64/base64.scm), but this would be a discussion you'd need to have with him. - It might be good to have an example of what you'd like to include here?

**Comment by fungiblecog** [comment]
I'm writing some utilities for the repl that query the functions/variables available in the different namespaces, and found the code in this file uses gambit internals to do that sort of thing. 

https://github.com/gambit/gambit/blob/dc9820362c1e461f3bd07819062590220a511229/tests/test10.scm

If it is not possible to copy this directly, it will not be much work for me to re-code it in a different way and to keep in mind the licensing requirements for the future.

**Comment by mgorges** [comment]
@fungiblecog Could you comment on which lines you'll need to see how much rewriting it would be? E.g. we already have list sorting functions (albeit named slightly differently)

**Comment by fungiblecog** [comment]
Once I take out all the boilerplate functions (sort, filter, etc) there are actually only a couple of low-level functions I really need so I think it will be easy to re-implement.

Thanks
