### ISSUE TITLE
Python language front-end

### ISSUE THREAD

**Issue by mhueser** [part-cw/lambdanative#125]
Are there currently plans to create further front-ends for languages that also trans-compile to C (like Gambit Scheme)? My need is more elaborate meta-programming, synthesizing GUI layout from declarative representation and layout management. 

Without an object model where I can bring some structure into global state I feel like this is a cumbersome task. I was considering to use stores but currently it feels a bit low-level. Having Python OOP facilities where I can just do e.g. question_widget.set_property("hidden",False) would be ideal. What is the complexity of creating such a front-end for Python?

**Comment by mhueser** [comment]
Could the TinyCLOS module be used for my purpose?

**Comment by mgorges** [comment]
@mhueser I am not quite sure what you are looking for but please have a look at [LNhealth](https://github.com/part-cw/LNhealth), which adds abstraction to allow easy creation of surveys-like apps with simplified language described in the [uiform](../wiki/Index-of-Module-uiform) module. 

However, if you require object models, there is object support in `LambdaNative`, e.g. see the [tinyclos](../tree/master/modules/tinyclos) module, which @clpetersen added in 727a5b4. Don't expect a lot of documentation for this in the Wiki though.

**Comment by mhueser** [comment]
@mgorges What I want to roughly do is to reason server-side about the optimal question-set / ordering to ask the care-taker in the next iteration (e.g. medical diagnostic check-up) based on data-base. Then I want to send a declarative representation (XML/JSON/...) from the server backend (implemented in Python) to the LambdaNative application which describes the questions to be asked (basically a data schema). Then the LambdaNative application decides based on local constraints (Resources, screen size, etc.) how to modify this representation and then finally draws its GUI.

**Comment by mgorges** [comment]
@mhueser I think you really want to look at both the [LNhealth](https://github.com/part-cw/LNhealth) app idea and the [uiform](../wiki/Index-of-Module-uiform) module, which might be able to do just that with very simple code, that the server would create and send. These things can be updated and re-rendered on the fly. There are some examples in the module, e.g. [ (dateentry . args) ](../wiki/uiform-dateentry) and the `WidgetDemo.sx` file has lots of pages, that are all dynamically built.

**Comment by mhueser** [comment]
Thanks a lot. 

Would you think this is powerful enough even when I aim for attractive GUIs (beyond purely functional)? I tried combining the two levels of GUI creation in LambdaNative (GLGUI on some pages together with UIFORM) and I could not customize the UIFORM enough to yield the layout that I needed. Then I just fell back to do everything in GLGUI.

**Comment by mgorges** [comment]
@mhueser two more thoughts: 
a) You can use [(uiform-register-legacy name draw input)](https://github.com/part-cw/lambdanative/wiki/uiform-register-legacy) to draw [ln_glgui](https://github.com/part-cw/lambdanative/wiki/Index-of-Module-ln_glgui) widgets in [uiform](https://github.com/part-cw/lambdanative/wiki/Index-of-Module-uiform) and thereby used them in `LNhealth` applications. For example we embed an [`RRate`](https://github.com/part-cw/LNhealth/wiki/Index-of-Module-rrate) page that way.
b) If there are some simple patches to make the [uiform](https://github.com/part-cw/lambdanative/wiki/Index-of-Module-uiform) elements more attractive we'd welcome some pull requests. Thanks!
