### ISSUE TITLE
Other GUI frontend (roadmap request)

### ISSUE THREAD

**Issue by 11111000000** [part-cw/lambdanative#126]
I think, we need the abstract layer to other UI C libs, like https://github.com/vurtun/nuklear, http://libagar.org/ , how difficult can it be done? Maybe some underwater rocks here?

**Comment by mgorges** [comment]
@11111000000 I only found this information for AGAR, but it doesn't seem to support iOS or Android, while Nuklear didn't seem to state their target platforms? - We do want to maintain mobile and desktop platforms, so I'll need to read more about it.

**Comment by 11111000000** [comment]
there is many ways to improve mobile UI we want to support: https://github.com/wasabeef/awesome-android-ui, https://github.com/cjwirth/awesome-ios-ui
primarly, I'm about "view abstraction" (like V in MVC), and now looks on webview as frontend
