### ISSUE TITLE
antialiasing

### ISSUE THREAD

**Issue by WildBench** [part-cw/lambdanative#131]
In the Calculator example, the font doesn't look pleasing in IOS (I didn't test in Android). How to use antialiasing with text in LambdaNative?

**Comment by mgorges** [comment]
@WildBench fonts are pre-rendered into character texture maps during the building process so there is no antialiasing upon display as would happen if a string were generated directly by iOS. Personally, I think the xelatex-rendered strings look nicer than the ones built with GD, which ones did you use?

Finally, the other factor that might help moving forward would be to render the iOS screen at a higher resolution than the current logical one (as low as 320x480). Maybe this is something we can change in OpenGL but at the moment I don't know how.

**Comment by WildBench** [comment]
Thank you two for the informative reply.
LambdaNative is so great. Appreciate your work very much!
