### ISSUE TITLE
Can't resume a looping sound on android

### ISSUE THREAD

**Issue by VincentToups** [part-cw/lambdanative#137]
I'm experiencing the following issue with the Android build of my project: looping sounds, once stopped, cannot be started again. I see the code has moved on a bit since I contributed it, but it is still pretty readable and I don't see anything obvious.

I'll be trying to resolve the issue myself but I figured I'd create an issue if you had any hints.

**Comment by mgorges** [comment]
@VincentToups sorry, but I don't have the resources to debug this at the moment. I believe UnloadSound is the only place, where the Sound file handle is released, so as long as that is not called I don't know why it now fails. Was this ever working as expected in your original contribution?

**Comment by VincentToups** [comment]
I seem to recall that it was. I'll try to figure it out and submit a patch.

**Comment by mgorges** [comment]
@VincentToups this should have been closed with d279279 - if not please reopen this. Thanks!
