### ISSUE TITLE
Trying to run the following, with tinyclos compiled in as a module, fails

### ISSUE THREAD

**Issue by kreely** [part-cw/lambdanative#138]
(define <pos>)
(define pos-x (make-generic))
(define pos-y (make-generic))
(define move  (make-generic))

(let ((x (vector 'x))
      (y (vector 'y)))
  
  (set! <pos> (make <class>
		    'direct-supers (list <object>)
		    'direct-slots  (list x y)))

  (add-method pos-x
      (make-method (list <pos>)
	(lambda (call-next-method pos) (slot-ref pos x))))
  (add-method pos-y
      (make-method (list <pos>)
	(lambda (call-next-method pos) (slot-ref pos y))))

  (add-method move
      (make-method (list <pos>)
        (lambda (call-next-method pos new-x new-y)
	  (slot-set! pos x new-x)
	  (slot-set! pos y new-y))))

  (add-method initialize
      (make-method (list <pos>)
	(lambda (call-next-method pos initargs)
	  (move pos (getl initargs 'x 0) (getl initargs 'y 0)))))
  )

(define p3 (make <pos> 'x 1 'y 2))
(define p4 (make <pos> 'x 3 'y 5))

Error is 
Unbound variable: getl

This function is defined in support.scm in the tinyclos module.

**Comment by mgorges** [comment]
@kreely I believe this is a namespace issue, with `getl` not being exposed in [modules/tinyclos/support.scm](https://github.com/part-cw/lambdanative/blob/master/modules/tinyclos/support.scm#L21). However, if I make it public I get a different error: `No slot #(x) "in instances of" #<procedure #9 <pos>>` so I must be missing something else too. Will look into it tomorrow with @clpetersen.

**Comment by kreely** [comment]
Made a mistake with my usage of namespace.
Missed that there was a (namespace## ("tinyclos")) elsewhere in the code.
Prefixed with tinyclos# and all is fine.
