### ISSUE TITLE
Injecting testing events

### ISSUE THREAD

**Issue by fungiblecog** [part-cw/lambdanative#139]
Is there any way of creating test events? 

For example I would like to inject an orientation event so that I can test orientation handling on my laptop rather than having to install the program on an actual mobile device. This would also be useful for automated testing eg by generating touch events to simulate user interaction and so on.

**Comment by mgorges** [comment]
Yes, use [(event-push t x y)](../blob/master/modules/eventloop/eventloop.scm), also see [wiki: event-push](https://github.com/part-cw/lambdanative/wiki/event-push). For example I use this to test changes  in orientations on my desktop. It is in the event handing code section starting with `(lambda (t x y)`

    ;; Keyboard events
    (if (fx= t EVENT_KEYRELEASE) 
      (begin
        ;; These are key presses, in case of ESC exit
        (if (fx= x EVENT_KEYESCAPE)
          (terminate)
        )
        ;; Change orientation with TAB
        (if (fx= x EVENT_KEYTAB)
          (event-push EVENT_ORIENTATION (if (orientation-landscape?) GUI_PORTRAIT GUI_LANDSCAPE) 0)
        )
        [...]
    )

**Comment by fungiblecog** [comment]
Great, thanks.
