### ISSUE TITLE
TestFlight Documentation?

### ISSUE THREAD

**Issue by VincentToups** [part-cw/lambdanative#143]
Have you used any lambdanative apps with TestFlight? All the documentation talks about using XCode, but Lambdanative bypasses that environment. I am at the stage where it might be nice to do some ios beta testing.

**Comment by clpetersen** [comment]
We don't use TestFlight (iOS only), but regularly use TestFairy for both iOS and Android distribution. I believe the functionality is similar. There are no added requirements to using TestFairy for distribution, just upload the ipa and/or apk packages generated by the Lambdanative build as-is.

**Comment by mgorges** [comment]
Have used it a few times now. Configure the app in `ios release` mode, upload the **Appname.ipa** file with `ApplicationLoader` and continue the remainder of the process in [https://itunesconnect.apple.com](https://itunesconnect.apple.com) as you typically would with internal and external beta testing.

**Comment by ionathanch** [comment]
Documentation has been added at https://github.com/part-cw/lambdanative/wiki/Preparing-for-Release#ios.
