### ISSUE TITLE
rendering onto a texture?

### ISSUE THREAD

**Issue by VincentToups** [part-cw/lambdanative#144]
Sorry for the barrage, but I have one final question: does the rendering system expose any easy way to render onto a texture? My game has screens with a large amount of text and the strategy of rendering each string (and each glyph, I believe, looking at the code) on every frame is slow. I'd like to render the text once onto a texture and use until the text is updated. 

I think I can probably muddle through writing the appropriate code, but wanted to make sure there wasn't already a way to do it.

**Comment by clpetersen** [comment]
You can pre-render all static text into single textures. This is illustrated by several of the demo apps.. for example, in DemoHelloWorld, the`STRINGS` file contains `cmss.ttf 24 'LambdaNative HelloWorld' title` which renders into a single texture `title.img` with the specified font and point size. Rendering dynamic text into a single texture is not implemented though, and would require manipulating the raw texture map and font atlas directly.

**Comment by VincentToups** [comment]
Is it possible to do multiline strings like this?

**Comment by VincentToups** [comment]
I am rendering pages of text, if that context helps.

**Comment by mgorges** [comment]
Yes, e.g. `cmss.ttf 12 "telePORT (c) 2011-2013 UBC \& BC Children's Hospital//CAUTION: NOT FOR CLINICAL USE !!!" copyright` - the linebreak is at the '//', which gets transformed into '\\'. I believe this only works for the LaTeX renderer though.

**Comment by VincentToups** [comment]
This looks useful, but the benefit of rendering onto a texture is that app size will be significantly smaller if I don't bundle in all that binary data (I think). 

http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-14-render-to-texture/

I think I might be able to figure this out - maybe I can add a function `with-rendering-to-image` with two arguments, a .img object and a function which is called in such a way that all rendering hits that texture. 

Incidentally, what exactly do .img objects contain?

**Comment by VincentToups** [comment]
So I am pursuing initializing a frame buffer by analogy to the ffi construct here:

`(define (glGenTextures arg1 arg2)
  ((c-lambda (int scheme-object) void
    "glGenTextures(___arg1,___CAST(void*,___BODY_AS(___arg2,___tSUBTYPED)));")
   arg1 arg2))
`

My code looks like this:

`(define (glGenFramebuffers arg1 arg2)
  ((c-lambda (int scheme-object) void
    "glGenFramebuffers(___arg1,___CAST(void*,___BODY_AS(___arg2,___tSUBTYPED)));")
   arg1 arg2))
`

But I'm not sure what needs to be passed in from scheme for the second argument? It seems like I need a u32vector, but I'm trying to invoke this like so:

`(define (gl-generate-frame-buffer)
  (let ((v (u32vector 0)))
    (glGenFramebuffers 1 v)
    (u32vector-ref v 0)))
`

And that segfaults. I'm no opengl wizard. Any suggestions?

**Comment by peterlew** [comment]
This is an old issue, but I have some tips that might help. 

Your `glGenFramebuffers` code is fine, and when I run it, it properly generates framebuffer names. The segfault may be related to where and when you call `gl-generate-frame-buffer`. 

There may be problems if there is not an active GL Context in that thread. I would suggest using [(glGetError)](../wiki/glGetError) to check if GL is running and if it has encountered any issues - it will return 0 if it is operating normally.

**Comment by peterlew** [comment]
I'd also like to add that if you are still interested in working on this, I'd be happy to collaborate. It seems like there would be real performance gains to be made by reducing the number of times strings and glyphs are rendered.
