### ISSUE TITLE
Need a detailed documentation

### ISSUE THREAD

**Issue by afidegnum** [part-cw/lambdanative#147]
Hi, 

when looking in python library's Kivy, they provide a detailed documentation on how their system work, 

is there a way we can do the same here? specially outlining relationship between elements and what do we need to do when we are to build them?

**Comment by mgorges** [comment]
@afidegnum all documentation in existence can be found in the [Wiki](https://github.com/part-cw/lambdanative/wiki) tab. Functions are described in the [Modules](https://github.com/part-cw/lambdanative/wiki/Source-Modules) sections and their respective subpages, with overall information on building in the [Compilation](https://github.com/part-cw/lambdanative/wiki/Compilation) and [Getting started](https://github.com/part-cw/lambdanative/wiki/Getting-Started) sections. 

The beauty of this approach is that any Github user can start to contribute to the documentation and expand upon areas as needed. I would welcome any suggestions and changes you are willing to help with. Thanks!
