### ISSUE TITLE
Build broken for new Android SDK Tools, Revision 25.3.1

### ISSUE THREAD

**Issue by Ondra09** [part-cw/lambdanative#148]
Build always returns e.g: ERROR: API 15 not a target.

Reason is change in tools/android binary, now it returns: 
```
The android command is no longer available.
For manual SDK and AVD management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
```
so https://github.com/part-cw/lambdanative/blob/master/targets/android/build-binary is failing between lines 72. to 80.

Same issue as this: https://github.com/appium/appium/issues/8017

**Comment by mgorges** [comment]
@Ondra09 this will require quite a bit of refactoring so we'll need a few days if not weeks to make something that remains backwards compatible. In the meantime if you need to build I'd suggest downgrading the SDK Tools to an older version.

**Comment by Ondra09** [comment]
Hi Matthias, it's fine for me, take your time.

It looks like` tools/bin/avdmanager list target` call should have provided the same result, but on my computer it lists devices... I expect this would make fix more complicated.

**Comment by mgorges** [comment]
That one is not the problem, you can query them with `tools/bin/sdkmanager --list | grep "platforms/android"` and then move on. The problem is that the `android create project` is no longer possible, and hence building with ant is no longer supported and we would need to switch to `gradle`.

**Comment by mgorges** [comment]
36d57ad automatically extracts `android` building tools from the last SDK, which contains it. Gradle support requires a major refactoring in project setup, which we currently don't have resources for.
