### ISSUE TITLE
Resize event for desktop applications?

### ISSUE THREAD

**Issue by snells** [part-cw/lambdanative#149]
As I understood you define window size on initialization and then everything gets scaled to it but I couldn't find way to resize screen and there's no mention of resize event in modules/eventloop/eventloop.scm.
I can see how this is good for mobile applications but on desktop applications it's really limiting.
Is there already way to change window size that I just haven't found? If not will you ever add way to resize window?

**Comment by clpetersen** [comment]
I'm afraid you are right, there is currently no resize option for desktop applications, and there are currently no plans to make the existing OpenGL rendering pipeline resizable. Our focus has mainly been the mobile targets, and coding once for a fixed size that then scales to any device viewport has been an tremendously effective way of saving programming resources.  We do have a few applications for desktops, but they typically run full screen (if you don't specify a window size, apps will go full screen on desktops).. this works well for situations where the device (in our case a medical PC) is dedicated to a single function. It's not great if you are planning on the traditional rich desktop-centric user interface of say a word processor or similar. Lambdanative is really not a good fit for that.. you'd probably want a more conventional flexible widget system for that as well, like say GTK+ or Qt. We are in the process of building out a hybrid option that eventually will run in a resizable webview frame on desktops, but for the moment the desktop approach is just to launch into a browser window.
