### ISSUE TITLE
How do we implement Android's recycleview in Lambdanative?

### ISSUE THREAD

**Issue by afidegnum** [part-cw/lambdanative#150]
Android's recycleview is the latest features brought out which allow widget displaying long list of items to be recreated to load new elements without degrading on the performance of the mobile device. 

Any idea on how can that be implemented in lambdanative?

**Comment by mgorges** [comment]
@afidegnum we currently don't support any native Android widgets as all of our widgets are created using OpenGL to be reused with the same look and feel on any platform we support. Why do you specifically want `recycleview`?

**Comment by afidegnum** [comment]
Thanks for your reply

In order to load a huge list of contents, android uses Listview to contain each elements of the list. This could be performance degradant and resources intensive if i.e we are to load 100, 200 items hence the android bought out the concept of RecyclerView,  or Recycleview in kivy. 

The RecyclerViews contains a an adapter which loads data visible to the screen, as a use scrolls the data up, unused data not visible on the screen are destroyed. With this approach, a user can load more than 1000 data on his mobile device without worrying about memory hug. Typical usecase is facebook or twitter feeds. I believe this could also be implemented on OpenGL as well, 

[you can read here for more reference, ](https://developer.android.com/training/material/lists-cards.html)

**Comment by mgorges** [comment]
[(glgui-list g x y w h dh lst cb . kcb)](https://github.com/part-cw/lambdanative/wiki/glgui-list) already only renders the elements visible on the screen. Thus elements not show won't require their data to be loaded and thus won't waste memory.

**Comment by mgorges** [comment]
Closing this as no further information provided.
