### ISSUE TITLE
How do i implement barcode reader using java's ZXing library or QR code? and widget styling?

### ISSUE THREAD

**Issue by afidegnum** [part-cw/lambdanative#151]
I have been practicing a bit of Lambdanative, which is quite nice, but i would like to know how do i implement the barcode reader functionality using the [ZXing library](https://github.com/zxing/zxing)? 

How do style the original interface in order to have native buttons and layout effects?

**Comment by mgorges** [comment]
The [dmtx](https://github.com/part-cw/lambdanative/wiki/Index-of-Module-dmtx) module wraps `libdmtx`, with examples for encoding and decoding found on that Wiki page. It is used, for example in the [WidgetDemo](https://github.com/part-cw/LNhealth/blob/master/apps/WidgetDemo/sandbox/main.sx) [LNhealth](http://lnhealth.lambdanative.org/) app. Which unsupported type of barcode  do you need that made you ask for `ZXing` specifically?

As for your second question - this is generally not supported at this point, and with the exception of native keyboard support in the [native-keypad](https://github.com/part-cw/lambdanative/wiki/glgui-native-keypad) module we have no intents to add this in the near future.

**Comment by mgorges** [comment]
In addition: If you want to decode QR codes, look into the [quirc](https://github.com/part-cw/lambdanative/blob/master/modules/quirc/quirc.scm) module, which has a function to do so from PNG images `(png->qrcodes pngfile)`.

**Comment by afidegnum** [comment]
Thanks a lot, i will look into the said library.

**Comment by mgorges** [comment]
We use this feature in some of our apps, from an image the user took with their camera, the processing piece looks like this:
```;; Process a QR code if not done already, look for new QR image
(define (process-qr)
  (let* ((fileinfo (if (file-exists? imagefile) (file-info imagefile) #f))
         (modtime  (if fileinfo (time->seconds (file-info-last-modification-time fileinfo)) #f)))
    (if (and modtime (> modtime lastmodtime))
      (let* ((gdf (gdFileOpen imagefile "r"))
             (gd  (gdImageCreateFromJpeg gdf))
             (w   (gdImageSX gd))
             (h   (gdImageSY gd))
             (w2  512)
             (h2  (fix (* w2 (/ h w))))
             (x0 (fix (/ w 4)))
             (y0 (fix (/ h 4)))
             (w3 (fix (/ w 2)))
             (h3 (fix (/ h 2)))
             (gdf2 (gdFileOpen imagefile2 "w"))
             (gd2 (gdImageCreateTrueColor w2 h2)))
         (gdImageCopyResampled gd2 gd 0 0 x0 y0 w2 h2 w3 h3)
         (gdImagePng gd2 gdf2)
         (gdImageDestroy gd)
         (gdImageDestroy gd2)
         (gdFileClose gdf)
         (gdFileClose gdf2)
         (let ((code (png->qrcodes imagefile2)))
           (if (and (list? code) (fx> (length code) 0))
             (begin
               (glgui-widget-set! save:cont save:id 'label (car code))
               (glgui-widget-set! save:cont save:save 'hidden #f))
             ;; Scanning failed, give popup
             (begin
               (glgui-widget-set! popup:gui popup:message 'label (local-get-text "qr_fail"))
               (show-ok-popup))))
         (set! lastmodtime modtime))))
)
