### ISSUE TITLE
App Name as Appears on Phone iOS build

### ISSUE THREAD

**Issue by VincentToups** [part-cw/lambdanative#155]
Is there any way to set the app name as it appears on the device? 

At the moment the only way to do so seems to be to change the folder name, but my game's name has spaces in it, and creating such a folder name breaks the build process. 

Unfortunately, the App Store guidelines require the name of the game to match the name of the app.

**Comment by mgorges** [comment]
@VincentToups the fastest way to change this is to change `loaders/ios/Info.plist.in` and hardcode the  name there.

**Comment by mgorges** [comment]
Should be fixed in 5e7849f. Please test and let me know.

**Comment by VincentToups** [comment]
I ought to have said, this resolved my issue as well. Thank you!
