### ISSUE TITLE
Potential Garbage Collection Issue on Android

### ISSUE THREAD

**Issue by VincentToups** [part-cw/lambdanative#156]
This is a bit preliminary, but in the Android version of my lambdanative app, on certain android devices, it appears as if manually invoking the garbage collector during event processing causes a crash. This appears to be difficult to reproduce as I believe it has something to do with resource utilization in other parts of the program which aren't easy to isolate. 

My app used to periodically invoke the GC manually and removing that behavior resolved the issue for the most part. However, I still see random crashes on some android devices which I suspect are coming from automatic GC invocation. 

I'm posting the issue despite these very vague indications in case it stimulates any thoughts on your parts about whether we might need additional synchronization measures in the android glue code.

**Comment by mgorges** [comment]
If this is indeed a problem, please file a new issue that shows a concrete problem and we'll look into it. Thanks!
