### ISSUE TITLE
How to speed up event loop

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#157]
What would be the best way to speed up the main loop cycle? 
It seems that on most systems one cycle takes about 10-12 ms (on macosx sometimes 50 ms, I guess this links to the redraw rate)
my workaround  was to invoke a random event with (event-push t x y) at the very end in the loop.  With that I can get up to 1 -2 ms on linux and macosx

I was wondering if there is a better way to cycle fast through the loop?

**Comment by mgorges** [comment]
Non-console apps sleep as defined in [loaders/common/main.c#L188](https://github.com/part-cw/lambdanative/blob/master/loaders/common/main.c#L188) for win32/linux platforms, [loaders/ios/EAGLView.m#L91](https://github.com/part-cw/lambdanative/blob/master/loaders/ios/EAGLView.m#L91) for ios and [loaders/macosx/SimpleOpenGLView.m#L53](https://github.com/part-cw/lambdanative/blob/master/loaders/macosx/SimpleOpenGLView.m#L53) for macos. Try reducing these values to get faster loop calls if you need to - see also ticket #142. If you need a task running more frequently I would suggest spawning a thread for it.

**Comment by karliwalti** [comment]
Thank you for suggesting a thread here. I saw the ticket  #142  on framerates.  The ios change seems to have very little effect on the loop cycle times.  The loaders/common/main.c#L188 works very well!
