### ISSUE TITLE
Android build broken for long organization identifiers

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#158]
setting either 
SYS_ORGTLD="com"
SYS_ORGSLD="mydomain.mysubdomain"
with a separator, will break the build. 
While the files end up in  $tmpdir/src/com/mydomain/mysubdomain/$SYS_LOCASEAPPNAME/$SYS_APPNAME.java 
the system looks for them in 
$tmpdir/src/com/mydomain.mysubdomain/$SYS_LOCASEAPPNAME/$SYS_APPNAME.java 

can be fixed by replacing "." with "/" in lines 144, 249, 250  of  android build-binary

**Comment by mgorges** [comment]
I fear it is more complicated than that as the substitutions in `loaders/android/bootstrap.c.in` require special handling (and part of that is in the cache) - can try to take a look tomorrow.

**Comment by mgorges** [comment]
This patch will only fix the path issue, but not the `ac_cache` piece

    diff --git a/targets/android/build-binary b/targets/android/build-binary
    index 11db1e1..c9625e4 100755
    --- a/targets/android/build-binary
    +++ b/targets/android/build-binary
    @@ -140,7 +140,8 @@ if [ -d "$xmlfilesdir" ]; then
     fi
     
     echo " => transferring java hook.."
    -appdir=$tmpdir/src/$SYS_ORGTLD/$SYS_ORGSLD/$SYS_LOCASEAPPNAME
    +SYS_ORGSLD_PATH=`echo $SYS_ORGSLD | sed 's/\./\//'` 
    +appdir=$tmpdir/src/$SYS_ORGTLD/$SYS_ORGSLD_PATH/$SYS_LOCASEAPPNAME
     ac_output loaders/android/bootstrap.java.in $appdir/$SYS_APPNAME.java
     
     echo " => transferring java public classes.."
    @@ -244,8 +245,8 @@ fi
     
     # allow free rotation of hybrid apps
     if [ `has_module hybridapp hybridapp-xwalk` = yes ]; then
    -  cp $tmpdir/src/$SYS_ORGTLD/$SYS_ORGSLD/$SYS_LOCASEAPPNAME/$SYS_APPNAME.java tmp.java
    -  cat tmp.java | sed '/SCREEN_ORIENTATION_PORTRAIT/d' > $tmpdir/src/$SYS_ORGTLD/$SYS_ORGSLD/$SYS_LOCASEAPPNAME/$SYS_APPNAME.java
    +  cp $tmpdir/src/$SYS_ORGTLD/$SYS_ORGSLD_PATH/$SYS_LOCASEAPPNAME/$SYS_APPNAME.java tmp.java
    +  cat tmp.java | sed '/SCREEN_ORIENTATION_PORTRAIT/d' > $tmpdir/src/$SYS_ORGTLD/$SYS_ORGSLD_PATH/$SYS_LOCASEAPPNAME/$SYS_APPNAME.java
       rm tmp.java
     fi

**Comment by ionathanch** [comment]
Because we have a lot of JNI code with the C functions named by `Java_@SYS_ORGTLD@_@SYS_ORGSLD@_@SYS_LOCASEAPPNAME@...`, having `.` in TLDs and SLDs causes problems when compiling. Since acceptable characters in C functions seem to be only `[a-zA-Z0-9_]`, I'll try replacing `.` with `_` at the very beginning. Perhaps we should enforce allowing only these characters and `.` for TLDs and SLDs (`.` is a common delimeter in domains, I don't think we can avoid it) and provide error messages when people try otherwise?

**Comment by mgorges** [comment]
Let’s talk about this one in person. The problems include file locations and inverting the notation of the domain.
