### ISSUE TITLE
xcode 8 iOS provisioning profile

### ISSUE THREAD

**Issue by doctorguile** [part-cw/lambdanative#159]
Hi,

This is probably a documentation issue and not a real lambdanative bug 

I'm new to iOS development (but a experienced lisp/scheme developer), I followed the wiki and also https://livecode.com/how-to-create-a-free-ios-development-provisioning-profile/

I don't have a paid ios developer account but according to the above link, starting from xcode 7 we can develop and test without a paid account.

I can create a demo ios obj-c app and deployed to my iphone using xcode, but when I tried lambdanative (changing the PROFILE SYS_IOSDEVCERT to match my cert.

I still get this error

`Signing for "Calculator" requires a development team. Select a development team in the project editor. Code signing is required for product type 'Application' in SDK 'iOS 10.3'`

I created the same com.mydomain.calculator app using xcode without issue.

Note I cannot create a manual provisioning profile in xcode (uncheck "Automatically manage signing", I got "No eligible profiles for calculator")

Logging in to https://developer.apple.com/account/ and I do not see links to certs/profiles (probably because mine is not a paid account)

So, can I develop and test without a paid apple developer account using lambdanative? (apparently developing obj-c/swift in xcode works)

Thanks

**Comment by mgorges** [comment]
I am not sure the error is where you think it might be - what did you specify for `SYS_IOSRELCERT` and `SYS_IOSDEVCERT` in your PROFILE? - the `SYS_IOSTEAMID` gets extracted from these

**Comment by mgorges** [comment]
Also have a look in your keychain if there are any certificates which start with 'iPhone Developer' or 'iPhone Distribution' that need to match in name with the settings in the PROFILE

**Comment by doctorguile** [comment]
I copied the identify from keychain access and set SYS_IOSDEVCERT to "iPhone Developer: My Name (ABC...XYZ)"

As for SYS_IOSRELCERT, after going through the tutorial linked above, I only created a certificate for iOS development, I don't have certs for "iPhone Distribution: ...".

I'm just guessing here, but in order to get a iPhone Distribution, I tried the following

I went back to `Xcode 8 > Preference > Accounts > Manage Certificates > + sign > iOS app store`

then I get

`Permissions failure
Your account does not have permission to create iOS Distribution certificates.`

Can I just develop and test using lambdanative without distribution? (seems I'm able to with xcode/objc alone)

**Comment by mgorges** [comment]
Set a `SYS_IOSRELCERT` with some matching information to your `SYS_IOSDEVCERT` anyway, as [make.sh](https://github.com/part-cw/lambdanative/blob/master/make.sh#L825) extracts `IOSTEAMID` from it. - You might even be able to use the same content of everything past the colon.

**Comment by doctorguile** [comment]
Thanks for taking the time to help diagnose. 

I now saw this in make.sh
SYS_IOSTEAMID=`echo "$SYS_IOSRELCERT" | cut -f 2 -d "(" | cut -f 1 -d ")"`
so it's just extracting ABC...XYZ from it

I now set both SYS_IOSRELCERT and SYS_IOSDEVCERT to 
"iPhone Developer: My Name (ABC...XYZ)"

Now `make` gave a different error

`No profiles for 'com.mydomain.calculator' were found:  Xcode couldn't find a provisioning profile matching 'com.mydomain.calculator'.
Code signing is required for product type 'Application' in SDK 'iOS 10.3'`

Not sure if it's related, but in the sample objc xcode project I set the bundle Identifier to `com.mydomain.calculator` and it can build and deploy. (Do I need to generate a dummy project in xcode first before I can build using lambdanative??)

I googled a bit more and found the xcode generated profile under less "~/Library/MobileDevice/Provisioning Profiles/blahblah.mobileprovision"

<dict>
                <key>keychain-access-groups</key>
                <array>
                        <string>FQ2Y3AH597.*</string>           
                </array>
                <key>get-task-allow</key>
                <true/>
                <key>application-identifier</key>
                <string>FQ2Y3AH597.com.mydomain.calculator</string>
                <key>com.apple.developer.team-identifier</key>
                <string>FQ2Y3AH597</string>
        </dict>

It seems like xcode assigned a prefix FQ2Y3AH597. (Again, this might be unrelated, I'm just including stuff I found)

Thanks

**Comment by mgorges** [comment]
The provisioning profile is set in [loaders/ios/CMakeLists.txt.in#L30](https://github.com/part-cw/lambdanative/blob/master/loaders/ios/CMakeLists.txt.in#L30). If you leave it blank Xcode will try to sort it out by itself. This might not work in your case to try hardcoding it there instead.

**Comment by zhaoboqiang** [comment]
When I replace "iPhone Developer: My Name (ABC...XYZ)" with "ABC...XYZ", it work.

**Comment by zhaoboqiang** [comment]
When I replace "iPhone Developer: My Name (ABC...XYZ)" with "ABC...XYZ", it work.

**Comment by mgorges** [comment]
Great - do you feel we need to patch this for everyone, or is is just a special case as you don't have a developer account?

**Comment by mgorges** [comment]
@doctorguile Is this resolved now, so we can close this?
