### ISSUE TITLE
xcode 8.3.3 xcrun: error: unable to find utility "PackageApplication"

### ISSUE THREAD

**Issue by zhaoboqiang** [part-cw/lambdanative#160]
PackageApplication is deprecated, use `xcodebuild -exportArchive` instead.
xcrun: error: unable to find utility "PackageApplication", not a developer tool or in PATH

**Comment by mgorges** [comment]
This isn't an easy fix - I can build with the xcodebuild change but the packaged archive is empty. Might be a week or two, unless you have a patch idea already? Here my current patches in progress:
[targets/ios/package](https://gist.github.com/mgorges/e53d144332fd70f83e501bb044c73186)
[targets/ios/build-binary](https://gist.github.com/mgorges/ebcaeb117abbc7c79cc6cbb8849e76a4)
[loaders/ios/App.xcscheme.in](https://gist.github.com/mgorges/71b7b3083be43efc0bf2e0a92ddfd2e5)
[loaders/ios/exportOptions.plist.in](https://gist.github.com/mgorges/9b3510b68e474da9aa5b460789c748e6)

**Comment by zhaoboqiang** [comment]
Maybe I can try to fix it with your patch, but I don't have a full test environment.

**Comment by mgorges** [comment]
Fixed in 6f09947, please try and if that fails reopen this ticket.
