### ISSUE TITLE
uiform radiobox performs action despite none defined

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#163]
radiobox lets an action to be defined for left and right. If this is set to #f (like in the example given in 
[wiki](https://github.com/part-cw/lambdanative/wiki/uiform-radiobox) )
a click on the button will make the view jump to the top which is inconvienient in long forms. It would be desirable that even with an action, the view would remain stable .
In  (glgui:uiform-action action)  one could add an if clause or remove the offset line. not clear what the cansequences on other projects would be

```
(define (glgui:uiform-action action)
(if action  ;;option1
  (let ((evalaction (if (procedure? action) (uiform:evalarg 'action action) action)))
    (glgui:uiform-keypad-down)
    (uiset 'nodemap '())
    (uiset 'offset 0)  ;;option 2:  comment out
    (uiset 'nxt-action #f)
    (uiset 'prv-action #f)
    (if evalaction 
      (if (list? evalaction)
        (glgui:uiform-modal-up evalaction)
        (uiset 'page evalaction)
    ))
)))
```

to replicate or test, click on dummy_radio3

```
(ex_boxes
"Radio/Check Boxes"
  ("Prev" ex_labels #f)
  ("Next" ex_checklists #f)
  (spacer)
  (label text "Choose one:" align center)
  (spacer)
  (radiobox id dummy_radio location ui left ("Yes" 1 #f) right ("No" 2 #f))
  (spacer)
  ,(lambda () 
     (let ((value (uiget 'dummy_radio 0)))
      `(label text ,(cond ((= value 0) "No choice made")
                          ((= value 1) "You chose: Yes")
                          ((= value 2) "You chose: No")) align center)))
 (spacer)
 (spacer)
 (spacer)
 (spacer)
 (spacer)
 (spacer)
 (spacer)
 (spacer)
 (spacer)
 (spacer)
  (radiobox id dummy_radio2 location ui left ("Yes" 1 #f) right ("No" 2 #f))
  (spacer)
  (radiobox id dummy_radio3 location ui left ("Yes" 1 #f) right ("No" 2 #f))
)
```

**Comment by ddunsmuir** [comment]
This has been fixed in [537ae35](https://github.com/part-cw/lambdanative/commit/537ae3585b90d6153ae9e9d57bf3fded9bb32c57).

We took an approach closer to your option 2, by only setting the offset to 0 (top of page) if the action results in going to a different page. If the action (or what is returned from the action procedure) is #f, a list (popup content), or the current page, then the offset is not set and it does not scroll to the top.
