### ISSUE TITLE
Camera and uiform

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#166]
The camera module in uiforms is very slow on Android (android 7 and 8) after the image is taken. 
Has this been observed before and is there a workaround?

Could it be due to the new Camera API in adroid?

**Comment by mgorges** [comment]
Sorry, don't have an Android 7 or 8 devices around for testing, maybe @ddunsmuir can have a look tomorrow?

**Comment by karliwalti** [comment]
Thank you for coming back to me on this.  I would be interesting to know if it works on any android device?

**Comment by shaybeau731** [comment]
I tested it out using a Nexus tablet running Android 6.0.1. It took ~7 seconds to go back to the LNhealth app after taking a picture using the camera.
The part that takes the most time seems to be processing/loading the image into the app (lines 861-873 of uiform.scm). When I comment those lines out it loads much faster (~2.5 seconds).

**Comment by ionathanch** [comment]
The bottleneck is the call to `gdImageCopyResampled`, of the `libgd` library, which takes ~10 seconds on a Nexus 6P, Android 8.1 (there's some other things that also take a noticeably long time, but the longest of them is only ~1 s). Looking at the [source code](https://github.com/libgd/libgd/blob/08ae745426579be883d7f8aeabcc592b24de0597/src/gd.c#L3450), it runs in O(srcH * srcW * b), where srcH, srcW, and b are the dimensions of the original photo and whatever bilinear interpolation depends on (it's just math, I think); on the Nexus 6P, that's 3024 x 4032 by default, or around 12 million pixels. 

To look into: We're using this function to scale down the image, so we could either tell the camera to use a lower resolution, or use `gdImageCopyResized`, which also O(srcH * srcW * n), where n is nearest-neighbour interpolation, which from what I gather could be [two times faster](https://www.mathworks.com/help/vision/ug/interpolation-methods.html), but will also look uglier, and half of 10s is still 5s.

**Comment by mgorges** [comment]
Taking a lower-resolution picture in the first place might be a much better solution as we typically can't display that large of an image anyway? If there is the need to capture full-resolution for later analysis that is fine, and could be made optional, but for the time being it may be worth looking into the former?

**Comment by karliwalti** [comment]
We have a workaround that works reasonable well. Unfortunately
we have not submitted it for code review yet as there are other things in uiform. the basic idea is to scale much stronger for preview, but to keep the original file for saving.

```
@@ -936,15 +966,16 @@ SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
          (filename (glgui:uiform-arg args 'filename (uiget idname #f)))
          (tmpimagepath (if filename (string-append (system-directory) (system-pathseparator) "tmp_" filename) #f))
          (loc (glgui:uiform-arg args 'location 'db))
-         (curimg (xxget loc filename #f))
+         (curimg (xxget 'st filename #f))
          (archive (glgui:uiform-arg args 'archive #f))
+         (scale (glgui:uiform-arg args 'scale 0.8))
          (display (glgui:uiform-arg args 'display  #t))
          (newimg (if (and display tmpimagepath (file-exists? tmpimagepath))
             (let* ((fd (gdFileOpen tmpimagepath "r"))
                    (gd (gdImageCreateFromJpeg fd))
                    (w0 (gdImageSX gd))
                    (h0 (gdImageSY gd))
-                   (w1 (fix (* 0.8 w)))
+                   (w1 (fix (* scale w)))
                    (h1 (fix (/ (* h0 w1) w0)))
                    (gd2 (gdImageCreateTrueColor w1 h1))
                    (img (begin 
@@ -954,15 +985,18 @@ SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
               (gdImageDestroy gd2)
               (gdFileClose fd) img) #f))
          (img (if newimg newimg (if curimg curimg #f)))
-         (h (if img (cadr img) (fix (* w 0.8))))
+         (h (if img (cadr img) (fix (* w scale))))
+         (filearchived #f)
          (fnt (uiget 'fnt)))
-     (if newimg (xxset loc filename newimg))
-     (if (and tmpimagepath (file-exists? tmpimagepath)) (begin (if archive (let ((newfilepath (string-append (system-directory) (system-pathseparator) filename))) (copy-file tmpimagepath newfilepath) (xxset loc id newfilepath))) (delete-file tmpimagepath)))
+    ;;(log-status "img: " img tmpimagepath)
+     (if newimg  (xxset 'st filename newimg))
+     (if (and tmpimagepath (file-exists? tmpimagepath)) (begin (if archive (let ((newfilepath (string-append (system-directory) (system-pathseparator) (uiget 'camerafolder ".") (system-pathseparator) filename))) (copy-file tmpimagepath newfilepath) (xxset loc id newfilepath) (set! filearchived #t))) (delete-file tmpimagepath)))
      (if (uiget 'sanemap) (begin
-       (if img (glgui:draw-pixmap-center x y w h img White)
-       (begin
-         (glgui:draw-box (+ x (* w 0.1)) y (* w 0.8) h (uiget 'color-default))
-        (if (and (not display) archive) (glgui:draw-text-center x y w h (glgui:uiform-arg args 'defaultcomplete "Photo taken.\n Tap here to take a different photo") fnt White) (glgui:draw-text-center x y w h (glgui:uiform-arg args 'default "Tap to take photo") fnt White))))
+       (if img (begin (glgui:draw-pixmap-center x y w h img White) (glgui:draw-text-center x y w h (glgui:uiform-arg args 'defaultcomplete "Photo taken. Tap here to take a different photo") fnt White))
+       (if (and (not display) filearchived) (begin
+         (glgui:draw-box (+ x (* w 0.1)) y (* w scale) h DarkGreen)
+        (glgui:draw-text-center x y w h (glgui:uiform-arg args 'defaultcomplete "Photo taken. Tap here to take a different photo") fnt White))
+            (begin (glgui:draw-box (+ x (* w 0.1)) y (* w scale) h (uiget 'color-default))(glgui:draw-text-center x y w h (glgui:uiform-arg args 'default "Tap to take photo") fnt White))))
      ))
    h
   ))

```

**Comment by ionathanch** [comment]
@karliwalti The runtime of `gdImageCopyResampled` depends on the original image size, not the final image size, so scaling down to an even smaller size (which I believe is what you're doing in the above patch?) doesn't change how fast it runs.

**Comment by karliwalti** [comment]
For us it sped up the process so it became acceptable. I think the display is faster. On a mi A1 it takes about 5s for a 12mpix image. Perception of time is not linear...

**Comment by ionathanch** [comment]
A few things:
* There's no way to change the settings of the camera app from the app that launches the intent, so for it to take a lower-resolution image we'd have to tell the user to change the settings themselves. Even so, at the lowest setting of 0.9 MP on the Nexus 6P for instance, `gdImageCopyResampled` takes 5 seconds.
* Using `gdImageCopyResized` in fact takes 600 ms (which is still a huge improvement!) — now the bottleneck is the Bitmap compression step in the camera module, which [Android themselves say](https://developer.android.com/reference/android/graphics/Bitmap#compress(android.graphics.Bitmap.CompressFormat,%20int,%20java.io.OutputStream)) may take several seconds. As for quality, I've taken screenshots of [resample](https://drive.google.com/open?id=1w5Q4T3WswfVEdMTnWjUrZ8qcxAjBXMxY) vs [resize](https://drive.google.com/file/d/1dYbURE-se2TxuzbEVTiYsYyqPpR2NcfR/view?usp=sharing), and resize doesn't look _that_ bad when it doesn't take up the entire screen (as opposed to DemoCamera, which I was previously testing on, which sets the entire background to the image).

So in addition to the `'display` argument @karliwalti added a while ago, I'll also add another `'highquality` argument to choose between using `gdImageCopyResampled` and `gdImageCopyResized`, and it'll be up to the developer using the camera widget of uiform to choose the setting they feel most appropriate when it comes to tradeoffs between quality/displaying the image and loading time.

**Comment by ionathanch** [comment]
@karliwalti Adding a `'scale` argument is a good idea either way. Do you want to create a pull request or would you like me to make a commit with your changes?

**Comment by karliwalti** [comment]
I'd appreciate if you can copy as we had issues in the past with the pull requests. 
Note that we added the file path to store as this is a field not relevant for the form itself
