### ISSUE TITLE
Can't compile to iOS from Linux

### ISSUE THREAD

**Issue by zedeleven** [part-cw/lambdanative#170]
I'm trying to compile the calculator app to iOS. It works fine when I compile to Android to make a .apk, but when I try to make an iOS app the following occurs:

[DEC-PDP-12] $ make
=== using profile your profile name here [/home/maxnchz/lambdanative/PROFILE]..
=== configured to build Calculator version 1.0 for ios on linux in debug mode

ls: cannot access targets/ios/host_linux*: No such file or directory
ERROR: failed on file Don't know how to setup a build for ios on a linux host
BUILD FAILED
make: *** [all] Error 1

Any ideas what I need to do?

**Comment by mgorges** [comment]
Hi @zedeleven, unfortunately this is not possible as the iOS toolchain is only available for macos. - I believe there are some efforts to port parts of it, e.g. [tpoechtrager/cctools-port/)](https://github.com/tpoechtrager/cctools-port/) but I am not aware of anything that works out of the box. Please correct me if you come across something different. Sorry Matthias

**Comment by zedeleven** [comment]
Darn, that is unfortunate. Is there a lambdanative user group of any kind where I might be able to find and pay someone to periodically compile lambdanative code for me? If not, do you know anyone individually who I could contact for such a purpose?

**Comment by mgorges** [comment]
This is probably the best place to start or you could try the [Gambit mailing list](https://webmail.iro.umontreal.ca/mailman/listinfo/gambit-list)? - This is not a simple ask as iOS store submission requires a paid Apple Developer account, and to build for testing one needs to add devices to the developer profile or deploy tests over TestFlight, which have limited lifetimes.
