### ISSUE TITLE
Error building gambit for ios: 'system' is not availble on iOS.

### ISSUE THREAD

**Issue by BusFactor1Inc** [part-cw/lambdanative#172]
I get the following error when I try and compile my basic app for iOS:

`
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -DIOS -DIPHONE -miphoneos-version-min=5.1.1 -fPIC -fsigned-char -fomit-frame-pointer -I/Users/burton/Library/Caches/lambdanative/ios/arm64/include -L/Users/burton/Library/Caches/lambdanative/ios/arm64/lib -Wno-unused -Wno-write-strings -O1 -fno-math-errno -fno-strict-aliasing -fwrapv -fomit-frame-pointer -fPIC -fno-common   -I"../include" -c -o "_gambc.o" -I. -DHAVE_CONFIG_H -D___GAMBCDIR="\"/Users/burton/Library/Caches/lambdanative/ios/arm64\"" -D___SYS_TYPE_CPU="\"arm\"" -D___SYS_TYPE_VENDOR="\"unknown\"" -D___SYS_TYPE_OS="\"none\"" -D___CONFIGURE_COMMAND="\"./configure '--prefix=/Users/burton/Library/Caches/lambdanative/ios/arm64' '--host=arm' 'host_alias=arm' 'CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -DIOS -DIPHONE -miphoneos-version-min=5.1.1 -fPIC -fsigned-char -fomit-frame-pointer -I/Users/burton/Library/Caches/lambdanative/ios/arm64/include -L/Users/burton/Library/Caches/lambdanative/ios/arm64/lib' 'LDFLAGS=-L/Users/burton/Library/Caches/lambdanative/ios/arm64/lib' 'CPPFLAGS=-I/Users/burton/Library/Caches/lambdanative/ios/arm64/include' 'CPP='"\" -D___OBJ_EXTENSION="\".o\"" -D___EXE_EXTENSION="\"\"" -D___BAT_EXTENSION="\"\"" -D___PRIMAL _gambc.c -D___LIBRARY
os_shell.c:831:14: error: 'system' is unavailable: not available on iOS
      code = system (ccmd);
             ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/stdlib.h:195:6: note: 'system' has been explicitly marked unavailable here
int      system(const char *) __DARWIN_ALIAS_C(system);
         ^
clang: warning: argument unused during compilation: '-L/Users/burton/Library/Caches/lambdanative/ios/arm64/lib' [-Wunused-command-line-argument]
1 error generated.
gmake[1]: *** [makefile:150: os_shell.o] Error 1
gmake[1]: *** Waiting for unfinished jobs....
gmake[1]: Leaving directory '/Users/burton/.lambdanative/tmp_install/gambc-v4_7_9/lib'
ERROR: failed with exit code 2
>> gmake -j 9 failed
BUILD FAILED - configure with verbose option for more information
make: *** [all] Error 1
`

**Comment by mgorges** [comment]
This sounds like a problem with the 4.7.9 version of [gambit](https://github.com/gambit/gambit). - Can you check there if it is already reported as this seems to be new with XCode for 11.2?

**Comment by BusFactor1Inc** [comment]
Opened: https://github.com/gambit/gambit/issues/328

**Comment by BusFactor1Inc** [comment]
Adding the following line to libraries/libgambc/make.sh after line 12:

`sed 's|^.*system (|//&|' ~/.lambdanative/tmp_install/gambc-v4_7_9/lib/os_shell.c > ~/.lambdanative/tmp_install/gambc-v4_7_9/lib/os_shell.c`

**Comment by mgorges** [comment]
Thanks - let me make a proper patch out of this, that tests for your version of XCode and also enables this only for iOS

**Comment by tim2718** [comment]
(Ran into same issue, thanks very much for working on it.)

**Comment by mgorges** [comment]
Closed in 4a2cc87. Thanks @clpetersen
