### ISSUE TITLE
iOS Signing Problem

### ISSUE THREAD

**Issue by BusFactor1Inc** [part-cw/lambdanative#173]
Trying to build for ios, I get the following signing issue.

`Code Signing Error: Provisioning profile "iOS Team Provisioning Profile: *" doesn't include signing certificate "iPhone Developer: XXXXXXXXXX (XXXXXXX)".
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
`

X's  added to remove my information.  Have you seen this problem before?  I'm pretty sure I have the correct certificates entered in PROFILE.

**Comment by BusFactor1Inc** [comment]
Any idea what the problem might be here?

**Comment by mgorges** [comment]
Sorry, was traveling for a conference for the last few days. It sounds strange that you would want to sign with a provisioning profile:Can you post your PROFILE file with the identifiers removed? Also which version of Xcode are you using?

Mine looks something like this:
> SYS_PROFILE="PART BC Children's"
> SYS_IOSRELCERT="iPhone Distribution: PART BC Children's (A?????????)"
> SYS_IOSDEVCERT="iPhone Developer: PART BC Children's (G?????????)"

**Comment by BusFactor1Inc** [comment]
# descriptive profile name (will appear in build log)
SYS_PROFILE="BusFactor1 Inc. LambdaNative Profile"
# organization identifiers, e.g. yourdomainhere.com:
SYS_ORGTLD="ca"
SYS_ORGSLD="busfactor1"
# iOS release (SYS_IOSRELCERT) and development (SYS_IOSDEVCERT) names:
SYS_IOSRELCERT="iPhone Distribution: BusFactor1 Inc. (WXXXXXXXX)"
SYS_IOSDEVCERT="iPhone Developer: Burton Samograd (QXXXXXXXXX)"


Xcode Version: 9.2 (9C40b)

**Comment by mgorges** [comment]
That sounds reasonable, even though I currently only have tested with Xcode 8.3 (8E162). Given that the error message is explicit about the provisioning profile, did you re-download all provisioning profiles after adding yourself as a team developer to the account?

**Comment by BusFactor1Inc** [comment]
I think I have, or at least clicked ‘Download Manual Profiles’ in the certificate section of Xcode.  Are there any more steps than that?

**Comment by mgorges** [comment]
I don't think so, but don't have your version of XCode as I can't sign with it due to the problem in [issues/160](https://github.com/part-cw/lambdanative/issues/160), with `PackageApplication` no longer existing. By the way did you try the solution as proposed in [issues/159](https://github.com/part-cw/lambdanative/issues/159)?

**Comment by mgorges** [comment]
@BusFactor1Inc I assume this works now, otherwise please reopen.
