### ISSUE TITLE
How do you update the contents of a glgui-chat

### ISSUE THREAD

**Issue by burtonsamograd** [part-cw/lambdanative#176]
I've managed to get a glgui-chat on screen and working, but I can't seem to update it's contents. 

I've tried:

```scheme
(set! computer-chat (glgui-chat gui 0 0 (- w 10) (- h 20) 14 *log* calc_14.fnt #f))

;;; and then later...

(glgui-widget-set! gui computer-chat 'lst *log*)
```

With no luck.  Any tips?

**Comment by mgorges** [comment]
I believe the internal element you want to update is called **'list** (not 'lst) - see [modules/ln_glgui/chat.scm#L58](https://github.com/part-cw/lambdanative/blob/master/modules/ln_glgui/chat.scm#L58)

**Comment by burtonsamograd** [comment]
I checked the source code and tried that but also with no luck, but thank you.  Is there a correct 'time' that these items can be set (like from inside a function called from the event handler)?  Should I expect the control to update as soon as I set the 'list element for it, or would I have to do anything else to make it update?

**Comment by mgorges** [comment]
@burtonsamograd the next time the event loop redraws the element it should get updated. In the example you gave you didn't seem to have modified the `*log*` variable, or maybe you simply didn't copy that piece of code? 

If you are looking for an example of its use look at [apps/DemoSerial/main.scm#L167](https://github.com/part-cw/lambdanative/blob/master/apps/DemoSerial/main.scm#L167) or [apps/DemoSerial/main.scm#L190](https://github.com/part-cw/lambdanative/blob/master/apps/DemoSerial/main.scm#L190)

**Comment by burtonsamograd** [comment]
I tried a number of things to get the GUI updated with no luck; the *log* variable is updated, but from a 'webhook' (custom content function from the webserver module).  I had my feelings that might have had something to do with it; is the webserver running in a different thread possibly?

**Comment by mgorges** [comment]
Can you try to first make this work using a simple app, like DemoHelloWorld, and then in a more complicated setting?

As for the thread question, I don't think being in a thread is the issue - the namespace, however, might be: [modules/website/website.scm#L41](https://github.com/part-cw/lambdanative/blob/master/modules/website/website.scm#L41) defines a namespace for the website module. - That said I wouldn't believe this will case issues with your `*log*` variable? - One way to test is to log it to file in both places, where you set it and where you try to use it?

**Comment by mgorges** [comment]
I assume this has been resolved, if not please provide additional information and reopen.
