### ISSUE TITLE
use shallow git clone to download 3rd party repos

### ISSUE THREAD

**Issue by rgh36167** [part-cw/lambdanative#180]
I would suggest in scripts/package.sh line 116 to use ```git clone --depth=1 ...```,  should be much faster, saves some bytes on disk and can be expanded to a full repo at any time fairly easy.

**Comment by mgorges** [comment]
Thanks for the suggestion! I am not familiar with this, so would this still work with the code in line 122, where we checkout a specific commit, which is oftentimes specified in the library scripts?

**Comment by rgh36167** [comment]
good question, I think the best is to try it. How do I get rid of the cached copy of git://libdmtx.git.sourceforge.net/gitroot and nothing else?

**Comment by mgorges** [comment]
To remove that cached copy do something like this: 
`rm ~/Library/Caches/lambdanative/packages/libdmtx-a3*.tgz`

**Comment by rgh36167** [comment]
```git pull --depth=1 ...``` should have worked but I can't figure out how to point it to the specific comit.

**Comment by mgorges** [comment]
I don't think it is possible to clone a specific commit and as the depth=1 doesn't give you the full tree you can't checkout older commits from it? If you do have a solution I'll gladly include it but at the moment I don't know how this can be done with a shallow clone.

**Comment by rgh36167** [comment]
what can be done is replace

```git submodule init && git submodule update``` with

```git submodule init && git submodule update --depth=1```

- apparently here it would be even possible to get a specific commit. Maybe not worth worrying now but hope something turns up in the future because some repos are quite big.
