### ISSUE TITLE
libz.a: No such file or directory

### ISSUE THREAD

**Issue by pdu4** [part-cw/lambdanative#181]
Hi

I have run into this error twice before, but I thought it was something wrong with the gcc update, but it is not 

I am using debian 9 on a virtual machine and everything runs fine till I update the system and then I get the  second error below. 
I have had to "reinstall" debian twice now and lambdanative works fine after a reinstall that but this time all I did was install openjdk so the issue can not be with gcc. but after installing openjdk (and openjdk -headless)

First I got this error....

```

make[1]: Entering directory '/opt/lambdanative'
=== using profile your profile name here [/xxxxxxxxxxxx/lambdanative/zt/02DConsole/PROFILE]..
=== configured to build DemoConsole version 1.0 for linux on linux in normal mode

==> checking for required tools..
==> checking for required libraries..
==> checking for lambdanative tools..
==> creating libraries needed for DemoConsole..
 => liblambdanative..
ranlib liblambdanative.a
ranlib: 'liblambdanative.a': No such file
ERROR: failed with exit code 1
>> compilation failed
BUILD FAILED - configure with verbose option for more information
Makefile:2: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/opt/lambdanative'
```

and then I did 

	make scrub
and 

	./configure DemoConsole verbose

	make

and then the usual error I keep getting 
there is a zlib folder but no libz.a inside 

any ideas what is going wrong?
```

make[1]: Entering directory '/opt/lambdanative'
=== using profile your profile name here [/xxxxxxxx/lambdanative/zt/02DConsole/PROFILE]..
=== configured to build DemoConsole version 1.0 for linux on linux in normal mode

==> checking for required tools..
  => grep.. ok
  => wget.. ok
  => zip.. ok
  => tar.. ok
  => sed.. ok
  => tr.. ok
  => cut.. ok
  => tail.. ok
  => head.. ok
  => find.. ok
  => autoconf.. ok
  => make.. ok
  => gcc.. ok
  => patch.. ok
==> checking for required libraries..
 => checking for sane localhost OpenGL setup..
 => removing old /home/user/.lambdanative/gltest..
 => removing old /home/user/.lambdanative/gltest.c..
==> checking for lambdanative tools..
 => removing old /home/user/.lambdanative/tmp.config.cache..
 => building lambdanative tool pngtool..
 => removing old /home/user/.lambdanative/tmp.subst..
lambdanative: 4e64a51
==> creating libraries needed for pngtool..
 => libz..
  => shasum.. ok
 => extracting /home/user/.cache/lambdanative/packages/v1.2.11.zip..
  => unzip.. ok
 => configuring source..
  CHOST=x86_64-linux-gnu   PKG_CONFIG_PATH=/home/user/.cache/lambdanative/linux/lib/pkgconfig   PATH="/home/user/.cache/lambdanative/linux/bin:.:/home/user/bin/:/home/user/bin/bash/:/home/user/bin/bash/tcl/:/home/user/bin/bin/:/home/user/bin/clisp:/home/user/bin/:/home/user/bin/bash/:/home/user/bin/bash/tcl/:/home/user/bin/bin/:/home/user/bin/clisp:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"   LDFLAGS=-L/home/user/.cache/lambdanative/linux/lib   LD_LIBRARY_PATH=/home/user/.cache/lambdanative/linux/lib   CPPFLAGS=-I/home/user/.cache/lambdanative/linux/include   CC="gcc  -DLINUX  -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib"   AR="ar"   RANLIB="ranlib"   NM="nm"   LD="ld"   AS="as"   CPP="cpp"   OBJCOPY="objcopy"   STRIP="strip"   GPROF="gprof"   READELF="readelf"   OBJDUMP="objdump"   ./configure --prefix=/home/user/.cache/lambdanative/linux --static 
Using ar
Using ranlib
Using nm
Building static library libz.a version 1.2.11 with gcc -DLINUX -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib.
Checking for size_t... Yes.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
Checking for attribute(visibility) support... Yes.
 => compiling source..
  CHOST=x86_64-linux-gnu   PKG_CONFIG_PATH=/home/user/.cache/lambdanative/linux/lib/pkgconfig   PATH="/home/user/.cache/lambdanative/linux/bin:.:/home/user/bin/:/home/user/bin/bash/:/home/user/bin/bash/tcl/:/home/user/bin/bin/:/home/user/bin/clisp:/home/user/bin/:/home/user/bin/bash/:/home/user/bin/bash/tcl/:/home/user/bin/bin/:/home/user/bin/clisp:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"   LDFLAGS=-L/home/user/.cache/lambdanative/linux/lib   LD_LIBRARY_PATH=/home/user/.cache/lambdanative/linux/lib   CPPFLAGS=-I/home/user/.cache/lambdanative/linux/include   CC="gcc  -DLINUX  -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib"   AR=ar   RANLIB=ranlib   make 
make[2]: Entering directory '/home/user/.lambdanative/tmp_install/zlib-1.2.11'
gcc -DLINUX -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -c -o example.o test/example.c
gcc -DLINUX -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o adler32.o adler32.c
gcc -DLINUX -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o crc32.o crc32.c
gcc -DLINUX -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o deflate.o deflate.c
gcc -DLINUX -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o infback.o infback.c
gcc -DLINUX -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o inffast.o inffast.c
gcc -DLINUX -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o inflate.o inflate.c
gcc -DLINUX -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o inftrees.o inftrees.c
gcc -DLINUX -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o trees.o trees.c
gcc -DLINUX -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o zutil.o zutil.c
gcc -DLINUX -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o compress.o compress.c
gcc -DLINUX -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o uncompr.o uncompr.c
gcc -DLINUX -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzclose.o gzclose.c
gcc -DLINUX -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzlib.o gzlib.c
gcc -DLINUX -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzread.o gzread.c
gcc -DLINUX -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzwrite.o gzwrite.c
ar rc libz.a adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o 
This progam needs one parameter
gcc -DLINUX -I/home/user/.cache/lambdanative/linux/include -L/home/user/.cache/lambdanative/linux/lib -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o example example.o -L. libz.a
gcc: error: libz.a: No such file or directory
Makefile:289: recipe for target 'example' failed
make[2]: *** [example] Error 1
make[2]: Leaving directory '/home/user/.lambdanative/tmp_install/zlib-1.2.11'
ERROR: failed with exit code 2
>> make failed
BUILD FAILED
Makefile:2: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/opt/lambdanative'
```

**Comment by mgorges** [comment]
The line with `ar rc libz.a [*.o]` resulting in `This progam needs one parameter` sounds strange. Is there something, which overlays with `ar`, that we don't call properly?

**Comment by pdu4** [comment]
Thanks, problem solved, "ar" is (well now was) a bash script of mine I had forgotten about. I had thought that a program would supersede my scripts,( I guess not) and I did not recognize "ar"  as a program, I thought it was a parameter of gcc. 

While I am here, I have  a few questions I was not sure where to ask and I did not want to create needless issues (like this one, Sorry!)

Macros 
I can't get them to work in the DemoConsole REPL, adding syntax-case to the modules in Demo Console leads to a seg fault when I try to run the program and I do not really understand [Ln repl define global macros 2 #121](https://github.com/part-cw/lambdanative/pull/121). but I noticed that define-macro is used in the source code of some of the modules.

Are the other functions that don't work intentionally disabled ("command-line" does not work either) or is that a byproduct of your extensions?

I have reordered/restructured the wiki ( between "getting started" and "Structure"  ) a bit  to make a beginners  tutorial/manual (which I plan to upload as a pdf when i have finished linking everything) but as I am only focusing on Linux to Android compilation (for now) I mainly fleshed it out in that direction . Will my input be any use? How do I show you the changes  without trying to change your wiki drastically (I am very new to github) so you can take what you want (if anything)? Is anyone in charge of vetting the wiki? 


Can LambdaNative (theoretically ) be used to build an on-screen keyboard with swipe (is multi ouch the same as a swiping event and can LambdaNatives' programs interface with other native platform programs eg the native messanger. I know I will find this out eventually but there is quite a bit to get into and I plan to reshape the buttons so I would like to know ahead of time if I will have to try to add anything else or if it is possible)?

Thanks for the quick reply and for implementing such a great idea(LambdaNative)!!

**Comment by mgorges** [comment]
@pdu4 I don't mind you opening additional issues for separate questions, as it might help others find similar problems - the issue search on Github is primarily limited to the titles so one question per issue might be best?

As for macros, I don't know if they work in the REPL, as I believe the `syntax-case` is compiled once and then integrated into the binary blob? Our team doesn't really use them, so there isn't anyone here that I can ask for ideas. maybe @fungiblecog will be able to point you in the right direction? The segfault is in `   ___JUMPGLONOTSAFE(___SET_NARGS(3),3,___G__24_sc_2d_put_2d_cte)` **(sc-put-cte)**

Next, any additions to the documentation would be most welcome. We get notified about changes but I don't know if there is a feature showing diffs (or submitting patches with proposed changes)? If you wanted to you could send a gist with the new content in the Markup language, but if the changes are small I'd suggest you simply make them in the project wiki. - Thanks for your help here!

Finally, we have support for native keypads [modules/native-keypad](https://github.com/part-cw/lambdanative/tree/master/modules/native-keypad) - only on iOS and android. I have never tried this with a swiping version on android, but it might be possible to do?

**Comment by mgorges** [comment]
Sorry seem to have missed the comment about `command-line` - so yes, multiple issues might be better. I don't think we intentionally disabled it, but from comparing behaviour to `psi` what you are looking for might be `(system-cmdargv 0)` related functions in [wiki/Index-of-Module-config](https://github.com/part-cw/lambdanative/wiki/Index-of-Module-config)
