### ISSUE TITLE
localnotification & Android SDK notification / target mystery

### ISSUE THREAD

**Issue by ghost** [part-cw/lambdanative#183]
Trying localnotification and get 
```
/home/rz/.lambdanative/tmp_build/src/org/rz/nf/nf.java:226: error: cannot find symbol
    [javac]     am.setExact(am.RTC_WAKEUP, ts_msec, sender);
    [javac]       ^
    [javac]   symbol:   method setExact(int,long,PendingIntent)
    [javac]   location: variable am of type AlarmManager
```
I have an older SDK where for my own projects I usually set target api to 16. The lambdanative compile messages suggest that it sets the target  to an even lower value
```
=== configured to build nf version 1.0 for android on linux in normal mode
** WARNING Android API changed to 9
 [checkenv] Android SDK Tools Revision 22.3.0
[gettarget] Project Target:   Android 2.3.1
[gettarget] API level:        9
[gettarget] WARNING: Attribute minSdkVersion in AndroidManifest.xml (11) is higher than the project target API level (9)
```
 - although I have no idea where or why?

**Comment by mgorges** [comment]
Android's [AlarmManager](https://developer.android.com/reference/android/app/AlarmManager.html#setExact(int,%20long,%20android.app.PendingIntent)) has a minimum API level of **19** and `ANDROIDAPI=15` is defined in the `SETUP.template`, as most other things don't need one that low. 

I am puzzled however, where the `9` and `11` respectively come from? - If you don't have 11 (or 15) installed it might try to go down to one you have, which might be `9`?

**Comment by mgorges** [comment]
What you see here is actually more of a limitation of the code in [modules/localnotification/ANDROID_java_activityadditions#L36](https://github.com/part-cw/lambdanative/blob/master/modules/localnotification/ANDROID_java_activityadditions#L36) as it tests the SDK of the target device, not what the compiler can handle.  - However, if don't know how to do a `#ifdef` equivalent for Java?

**Comment by rgh36167** [comment]
ok, for some reasons I hade ANDROIDAPI=11 in SETUP, changed to 16. Confused why it says ```** WARNING Android API changed to 14``` - does it always substract 2?

There appears to be ```currentapiVersion``` which could be used in such cases. For a related example see https://github.com/Red-Folder/Scheduler-Plugin/commit/0c80522ac72304c191de49065fbf3a8c1b8722e8

**Comment by rgh36167** [comment]
sorry. didn't look at the code well, it is exactly what you already have :(

**Comment by mgorges** [comment]
No, it doesn't always subtract 2 it tries to find one you have the SDK installed for as you might have specified a different one that what you have downloaded using the `android` tool.

**Comment by rgh36167** [comment]
On Wed, Mar 14, 2018 at 02:13:49PM -0700, Matthias Görges wrote:
> What you see here is actually more of a limitation of the code in [modules/localnotification/ANDROID_java_activityadditions#L36](https://github.com/part-cw/lambdanative/blob/master/modules/localnotification/ANDROID_java_activityadditions#L36) as it tests the SDK of the target device, not what the compiler can handle.  - However, if don't know how to do a `#ifdef` equivalent for Java?

I found this
https://stackoverflow.com/questions/13380191/conditional-compiling-in-android

However it is not at all important for me, I was just playing with the various 
things.
