### ISSUE TITLE
clang++: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by wigust** [part-cw/lambdanative#184]
Hello,

I fail to getting started on GNU/Linux Ubuntu 16.04.  I'll attach `configure`, `make`, `strace` logs.

**Comment by mgorges** [comment]
Sorry, I am traveling thus my slow response. From the linking errors it seems that you are missing some 64bit related function calls. 
`[armeabi] SharedLibrary  : libpayloadshared.so
/home/miles/.lambdanative/tmp.vOcnTI/libpayload/libpayload.a(os_base.o):os_base.c:function ___alloc_mem_code: error: undefined reference to 'mmap64'
/home/miles/.lambdanative/tmp.vOcnTI/libpayload/libpayload.a(os_base.o):os_base.c:function ___display_error: error: undefined reference to 'stderr'
/home/miles/.lambdanative/tmp.vOcnTI/libpayload/libpayload.a(os_base.o):os_base.c:function ___set_signal_handler: error: undefined reference to 'sigemptyset'`

To start debugging a bit more two questions: 
a) Can you build successfully for another platform, like linux? 
b) Could you rebuild after scrubbing the cache and provide those logs - I am wondering if the gambit build didn't complete successfully? 

Thanks Matthias

**Comment by mgorges** [comment]
This might be related: [android-ndk/ndk/issues/445](https://github.com/android-ndk/ndk/issues/445#issuecomment-313322546)

**Comment by mgorges** [comment]
Try adding `-D__ANDROID_API__=${ANDROIDAPI}` to [android/host_linux#L72](https://github.com/part-cw/lambdanative/blob/master/targets/android/host_linux#L72)

**Comment by danielsz** [comment]
Added: 
```sh
SYS_CC=$android_cross"gcc $SYS_DEBUGFLAG -DANDROID -isysroot $android_sysroot $cflag_additions -D__ANDROID_API__=${ANDROIDAPI}"
```
Followed by `make clean`, then `./configure DemoHelloWorld android && make`.

Output:

```sh
=== using profile Daniel Szmulewicz [/home/arch/daniel/scheme/lambdanative/PROFILE]..
=== configured to build DemoHelloWorld version 1.0 for android on linux in normal mode

==> checking for required tools..
==> checking for required libraries..
==> checking for lambdanative tools..
==> creating libraries needed for DemoHelloWorld..
 => liblambdanative..
 => cleaning up..
 => exploding library libgambc..
 => exploding library liblambdanative..
==> creating artwork needed for DemoHelloWorld..
==> creating textures needed for DemoHelloWorld..
==> creating fonts needed for DemoHelloWorld..
==> creating strings needed for DemoHelloWorld..
==> updating embedded files for DemoHelloWorld..
==> updating web assets for DemoHelloWorld..
 => compiling scheme payload..
    /home/arch/daniel/scheme/lambdanative/modules/config/config.scm ..
    /home/arch/daniel/scheme/lambdanative/modules/eventloop/eventloop.scm ..
    /home/arch/daniel/scheme/lambdanative/modules/ln_core/ln_core.scm ..
    /home/arch/daniel/scheme/lambdanative/modules/ln_glcore/ln_glcore.scm ..
    /home/arch/daniel/.cache/lambdanative/build/DemoHelloWorld/fonts/main-ascii.scm ..
    /home/arch/daniel/.cache/lambdanative/build/DemoHelloWorld/strings/main-title.scm ..
    /home/arch/daniel/scheme/lambdanative/modules/ln_glgui/ln_glgui.scm ..
    /home/arch/daniel/scheme/lambdanative/modules/audio/audio.scm ..
    /home/arch/daniel/scheme/lambdanative/modules/audioaux/audioaux.scm ..
    /home/arch/daniel/scheme/lambdanative/apps/DemoHelloWorld/main.scm ..
 => done compiling scheme payload
 => generating hook..
 => assembling payload..
 == /home/arch/daniel/.cache/lambdanative/android/lib/libpayload.a
==> creating android loader needed for DemoHelloWorld..
 => creating android project..
 => using target 2 [API 21]
 => preparing icons..
 => processing sounds needed for DemoHelloWorld..
 => processing sounds from /home/arch/daniel/scheme/lambdanative/apps/DemoHelloWorld/sounds...
 => /home/arch/daniel/scheme/lambdanative/apps/DemoHelloWorld/sounds/ahooga.wav..
 => transferring java hook..
 => transferring java public classes..
 => preparing manifest..
 => creating payload module..
 => preparing JNI..
 => compiling payload module..
NDK_MODULE_PATH=/home/arch/daniel/.lambdanative/tmp.Apiwkw /opt/android-ndk/ndk-build --silent APP_ABI=armeabi
Android NDK: Found platform level in ./project.properties. Setting APP_PLATFORM to android-21.
/opt/android-ndk/build/core/setup-app.mk:81: Android NDK: Application targets deprecated ABI(s): armeabi
/opt/android-ndk/build/core/setup-app.mk:82: Android NDK: Support for these ABIs will be removed in a future NDK release.
[armeabi] Compile thumb  : payloadshared <= bootstrap.c
[armeabi] SharedLibrary  : libpayloadshared.so
/home/arch/daniel/.lambdanative/tmp.Apiwkw/libpayload/libpayload.a(os_base.o):os_base.c:function ___display_error: error: undefined reference to 'stderr'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [obj/local/armeabi/libpayloadshared.so] Error 1
ERROR: failed with exit code 2
BUILD FAILED - configure with verbose option for more information
make: *** [Makefile:2: all] Error 1
```

**Comment by mgorges** [comment]
Sorry, the NDK needs to get this flag passed as well. One way would be to change "CFLAG_ADDITIONS" so [loaders/android/Android.mk.jni.in](https://github.com/part-cw/lambdanative/blob/master/loaders/android/Android.mk.jni.in) updates it too. The only way I currently see is either making two changes in android loader and target, or one in make.sh.

**Comment by mgorges** [comment]
E.g. changing [loaders/android/Android.mk.jni.in#L5](https://github.com/part-cw/lambdanative/blob/master/loaders/android/Android.mk.jni.in#L5) to `LOCAL_CFLAGS    := @CFLAG_ADDITIONS@ -DANDROID -D__ANDROID_API__=@SYS_ANDROIDAPI@ -I@SYS_PREFIX@/include`.

**Comment by danielsz** [comment]
Same output after applying indicated changes to `Android.mk.jni.in`.

**Comment by mgorges** [comment]
Too bad, then I'll need to get myself a virtual machine with your version of Arch Linux and see how to investigate this further. For reference which versions of the Android NDK and SDK do you have installed?

**Comment by danielsz** [comment]
Actually, it seems I needed to issue `make scrub`. This time around, I progressed further. Thank you.
A different issue came up:
```sh
[buildconfig] Generating BuildConfig class.
-pre-compile:
-compile:
    [javac] Compiling 3 source files to /home/arch/daniel/.lambdanative/tmp_build/bin/classes
    [javac] error: Source option 5 is no longer supported. Use 6 or later.
    [javac] error: Target option 1.5 is no longer supported. Use 1.6 or later.
BUILD FAILED
```
I run java 10. SDK is 26.1.1, and ndk is r16.b

**Comment by danielsz** [comment]
Works with Java 8, though. Thank you. Build succeeded.

**Comment by mgorges** [comment]
Thanks for trying some more options, and finding a successful one. Still a reason to explore the difference between Java 8 and 10 I should look into.

**Comment by danielsz** [comment]
I saw the same linker error when installing apps that have dependencies (like DemoPhysics with the chipmunk dependency), indicating that there might be more places where C flags need to be set. Could that be the case?

**Comment by mgorges** [comment]
Yes, it will probably need to go in lots of places but I have yet to figure out how to only set it once, instead of having to change a ton of different places.

**Comment by danielsz** [comment]
OK, no problem, please let me know if I can help with testing.

**Comment by mgorges** [comment]
I think the Java9/10 compatibility should have its own ticket. Also don't know when I'll be able to look into this further. Will look at the linker global addition piece tomorrow.

**Comment by danielsz** [comment]
You are right. 

I will wait for the global addition of C flags (that will propagate through gcc, NDK and project external dependencies) and test it when it lands in master. Thank you.

**Comment by mgorges** [comment]
Fixed in 1e213e01, which specified the desired android API in both the CFLAG in the android build configuration as well as SYS_CC.

**Comment by mgorges** [comment]
I thought that worked - will have to look again this week.

**Comment by mgorges** [comment]
@danielsz could you paste the full compilation log for DemoPhysics on android, as this does seem to work for me - I do get these lines int there, which seem appropriate: `/Users/mgorges/Library/Caches/lambdanative/android/android-ndk-r13b-arm-19-toolchain/bin/arm-linux-androideabi-gcc  -DANDROID -D__ANDROID_API__=19 -isysroot /Users/mgorges/Library/Caches/lambdanative/android/android-ndk-r13b-arm-19-toolchain/sysroot  -Wall -std=gnu99 -DNDEBUG -DCP_USE_DOUBLES -I../include/chipmunk -c *.c`

**Comment by mgorges** [comment]
maybe you didn't rebuild something after you pulled so you have mixed libraries still around?

**Comment by danielsz** [comment]
That is very possible. What is the procedure I should follow after pulling?

**Comment by mgorges** [comment]
I would typically say `make scrub; configure DemoPhysics android; make`, but this might be too much effort as it would rebuild everything for all platforms. 

Thus, I'd suggest you manually clear the android build cache and then simply do a `make` - the cache folder is located at `$HOME/lambdanative-cache`, `$HOME/.cache/lambdanative`, or `$XDG_CACHE_HOME/lambdanative` depending on your system; within it you find an android folder, which contains a lib folder, removing only the later one should be sufficient to force a library rebuild.

**Comment by danielsz** [comment]
Yup, that did it. Awesome. Thanks!
