### ISSUE TITLE
Paste from clipboard

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#185]
Is there any way to access the clipboard content of various platforms within lambdanative?

It would be a useful tool to fill forms quicker.

**Comment by mgorges** [comment]
Not sure I can work on this quickly as it requires three components: a) integration into the system calls like ` UIPasteboardNameGeneral` for iOS, `ClipboardManager` for Android, `X Window selection` for linux, `GetClipboardData` on win32 etc.; b) addition of workflow elements to allow selection, copy/paste, and c) integration of such workflow elements into the existing widget suite.

**Comment by mgorges** [comment]
Commit 3526885 adds support for the basic operations: a) copy, b) paste, and on some platforms c) clear and d) check if clipboard has content, for iOS, Android, MacOS, and Windows. We yet have to add Linux support, bindings to the native buttons like Crtl+C/V etc. Also it is still missing any widget integration.

**Comment by karliwalti** [comment]
Cool, thank you.

**Comment by ionathanch** [comment]
Update: d7595c341ecebe5855b5cced0e4a498a01404306 adds a longpress copy-paste menu for labels, 415e2e0cf507519752f43a8405c14c613cb84003 adds CTRL-C and CTRL-V events (and modifier key events in general) for macOS, and d6d090434f7694aef4979da7c8b184cd5a6513d5 adds them for Windows. Keybindings for Linux to come.

**Comment by ionathanch** [comment]
56b941660de538119f3622edc3c50c7857455382 implements copy on Linux, usable through both the hover menu in input labels and through CTRL-C.
