### ISSUE TITLE
Sierra macOS apps downloaded from the Internet

### ISSUE THREAD

**Issue by ddunsmuir** [part-cw/lambdanative#186]
Currently there is a permissions problem when running a lambdanative Mac app that was downloaded from a location such as Dropbox or Google drive. On macOS Sierra or newer, the app will not run the normal way even when you make a security exception for the app being from an unknown source. To get the app to run, you need to right click it and choose Show Package Contents and then double click the Unix Executable in that folder. This problem occurred even when transferring a file built on a Sierra iMac to another computer and back to the original computer through Dropbox.

**Comment by ionathanch** [comment]
Update: According to [this](https://developer.apple.com/support/developer-id/), we need to sign our macOS apps with a Developer ID. It seems like the iOS build does this signing when it builds with `xcodebuild`, but the macOS build builds with GCC?

**Comment by mgorges** [comment]
I thought we actually build with clang (which disguises itself as GCC), but in any case this switch would require us to add a lot of provisioning profiles and collect device UUIDs for testing as we currently only do for iOS. - It seems funny that simply showing the package content would bypass the Gatekeeper too.

**Comment by ionathanch** [comment]
`sudo spctl --master-disable` will re-enable the Anywhere option in `System Preferences > Security & Privacy > General > Allow apps downloaded from:`. This reverts behaviour to [pre-Sierra macOS](https://arstechnica.com/gadgets/2016/06/raw-shooting-a-harsher-gatekeeper-and-more-obscure-macos-and-ios-10-changes/). If we're not distributing macOS apps this way, only developing them, we can tell developers to run this command if they run into the issue.

**Comment by mgorges** [comment]
Commit 77db238 adds either macOS code signing using `"Developer ID Application: <your name> (<team ID>)"` certificates if found, or an ad-hoc signature, if it doesn't. This should resolve this issue but needs to be verified.
