### ISSUE TITLE
Define multiple OVERLAY_PATH in SETUP

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#188]
Is it possible to define multiple paths in SETUP to looks for apps as described here?

[Satellites](https://github.com/part-cw/lambdanative/wiki/Satellite-Frameworks)

**Comment by mgorges** [comment]
This is already possible, see [configure#L59](https://github.com/part-cw/lambdanative/blob/master/configure#L59), which uses a colon as the separator. E.g. 
> OVERLAY_PATH=/Users/d/Documents/i-something:/Users/d/Documents/lnHealth
