### ISSUE TITLE
NDK r17 deprecates armeabi

### ISSUE THREAD

**Issue by danielsz** [part-cw/lambdanative#196]
Which is fixed by editing https://github.com/part-cw/lambdanative/blob/cb446916a259bb32c47d12ebec7d883565726db0/targets/android/build-binary#L235
and changing into `armeabi-v7a`

**Comment by mgorges** [comment]
This would drop support for anything on ARMv5, v6 hardware, which are mainly below Android 4.4 (API level 16), right?

**Comment by danielsz** [comment]
This would drop support for ARMv5, v6 devices, indeed. Time-wise, this may correspond to Android 4.4 (API level 16), I don't know. 

It appears that the availability of low-end ARMv7 chipsets makes this a reasonable default.

**Comment by mgorges** [comment]
Will discuss with the team as we do use this for quite a few global health studies.
