### ISSUE TITLE
glgui-inputlabel will always obtain focus on BUTTON1UP event

### ISSUE THREAD

**Issue by nonphatic** [part-cw/lambdanative#197]
**Example scenarios:**
1. In a GUI with an input label, click outside of the label, then drag into the inside of the label, and release.
2. In a GUI with a keypad with `hideonreturn` enabled over an input label located behind the return key, click and release the return key.

**Expected behaviour:**
1. No changes; the input label does *not* obtain focus.
2. The keypad will be hidden; the input label does *not* obtain focus.

**Actual behaviour:**
In both cases, the input label *will* obtain focus. In scenario 2, I have also set the keypad to unhide in `onfocuscb` of the input label, so the keypad will not be hidden.

**Details:**
In [line 226](https://github.com/part-cw/lambdanative/blob/master/modules/ln_glgui/glgui.scm#L226) of glgui.scm, `EVENT_BUTTON1UP` is always propagated to all widgets. In [label.scm](https://github.com/part-cw/lambdanative/blob/master/modules/ln_glgui/label.scm#L184), `onfocuscb` will always be called if `(and clickable inside (fx= type EVENT_BUTTON1UP))`. The solution I see for this is to give label an `'armed` field (similar to keypad) such that it is set to `#t` on `EVENT_BUTTON1DOWN` if `(and clickable inside)` and trigger `onfocuscb` on `EVENT_BUTTON1UP` only if `(and clickable inside armed)`.

**Comment by mgorges** [comment]
Adding the armed piece as in box or keypad sounds like a sensible solution. - I doubt we have any behaviour with a label where we depend on the click to happen outside, however, I am wondering if we would also need disarming code?

**Comment by nonphatic** [comment]
@mgorges Following keypad and button, it looks like disarming should also occur on `EVENT_BUTTON1UP`.
