### ISSUE TITLE
Failed to create toolchain using Windows Subsystem on Linux

### ISSUE THREAD

**Issue by Valfather** [part-cw/lambdanative#198]
Hello. I am trying to get lambdanative running following the getting started page, but I can't compile for android even though compiling for linux works fine.
I am on Ubuntu 18.04.
I installed android studio; my sdk and  ndk are in /home/user/Android/sdk and /home/user/Android/sdk/ndk-bundle, so I set the ANDROIDSDK and ANDROIDNDK in SETUP accordingly. I also made sure to install the correct android platform version (19 / 4.4)

Here's the output when I run ./configure Calculator android --verbose && make

> ==> configured to build Calculator for android in normal verbose mode
>  == using source in /home/dreamer/Build/lambdanative/apps/Calculator
> === using profile Svipal [/home/dreamer/Build/lambdanative/PROFILE]..
> === configured to build Calculator version 1.0 for android on linux in normal mode
> 
> HOST_OS=linux
> HOST_EXE=
> HOST_ARCH=x86_64
> HOST_TAG=linux-x86_64
> HOST_NUM_CPUS=8
> BUILD_NUM_CPUS=16
> ERROR: Failed to create toolchain.
> ERROR: failed on file /home/dreamer/.cache/lambdanative/android/ndk-bundle-arm-19-toolchain
> BUILD FAILED
> Makefile:2: recipe for target 'all' failed
> make: *** [all] Error 1

I also tried with 21 and I get the same error.
This is my first time both using  Scheme and compiling for android, so I have absolutely no idea what might be the matter.. I apologize if this is not the place to post this.

**Comment by mgorges** [comment]
A few questions/comments: 
a) Are you sure the sdk tools are complete, when installing them using Android studio and not downloading the SDK command line tools and NDK separately? - Specifically, do you have the "Android SDK Tools", "Android SDK Platform-tools", "Android SDK Builds-Tools" as well as the API 19 "SDK Platform" installed?
b) Are the paths pointing in the right direction?
c) The correct usage of verbose is `./configure Calculator android verbose`, there are no two extra dashes before it.
d) What are your versions of the NDK and SDK?

**Comment by Valfather** [comment]
Thanks for your answer.
a) Yes ! See this.
![image](https://user-images.githubusercontent.com/16215390/40868459-acbce7a6-663f-11e8-948e-4814ac2bf780.png)

![image](https://user-images.githubusercontent.com/16215390/40868455-a5a93c30-663f-11e8-974c-870846c4746b.png)


b) if you mean the paths in the SETUP, yes. 


c) I didn't know ! Strange that it didn't warn me. It seems to work the same regardless.

d) A shown in the image above:
SDK Platform-tools 		27.0.1	
SDK tools 		26.1.1
NDK 17.0.4754217

**Comment by mgorges** [comment]
I can't seem to reproduce this - I removed my entire android sdk/ndks, cleared the lambdanative cache and it seems to start to build gambc fine. Will need to look a bit more.

**Comment by mgorges** [comment]
Actually I spoke too soon - I now get an issue:

> os_base.c: In function '___alloc_mem_code':
os_base.c:289:9: error: call to 'mmap' declared with attribute error: mmap is not available with _FILE_OFFSET_BITS=64 when using GCC until android-21. Either raise your minSdkVersion, disable _FILE_OFFSET_BITS=64, or switch to Clang.
   void* ptr = mmap (0,
         ^
gmake[2]: *** [makefile:150: os_base.o] Fehler 1

However, this seems to be resolvable by making the ANDROIDAPI=21

**Comment by Valfather** [comment]
Hey, thanks for digging.
I'm sorry I didn't precise this but I'm running Ubuntu 18.04 **on WSL** with Xming for graphical display. I was hopeful it would work the same way as a normal Ubuntu install since I never had issues with it before, can compile other languages fine, Android Studio works without a hitch  and the lambda native build for linux works fine as well. 
But since I don't get any of your errors, just the very terse output posted in the first message, I'm guessing it might be the reason ...
I tried a few things : installing with sdkmanager instead of android studio, which made me realize I forgot to install java, but it wasn't the problem. I still get the same output.

**Comment by mgorges** [comment]
Thanks for the additional information - The fact that you are using **Windows Subsystem on Linux** might have something to do with it as I am now wondering that you are missing some other binary (as you did with **Java**, which the ndk-bundle-arm-19-toolchain assumes to be present? One possible thing might be `cmake`?

I am wondering if we could make this part more verbose so it could tell you which one it is lacking?

**Comment by Valfather** [comment]
I do have cmake installed. That would be great !

**Comment by mgorges** [comment]
Revisiting this briefly, as I won't have a WSL machine to test with - could this be a permission problem of the place where the toolchain creation is supposed to happen?

**Comment by karliwalti** [comment]
Encountering the same problem both in a fresh Ubuntu 20.04 install and in WSL on windows 10:

```$ make
=== using profile karliwalti [/home/walterk/SoftwareRepo/lambdanative/PROFILE]..
=== configured to build DemoHelloWorld version 1.0 for android on linux in normal mode

HOST_OS=linux
HOST_EXE=
HOST_ARCH=x86_64
HOST_TAG=linux-x86_64
HOST_NUM_CPUS=1
BUILD_NUM_CPUS=2
Toolchain installed to /home/walterk/.cache/lambdanative/android/android-ndk-r13b-arm64-21-toolchain.
ERROR: failed on file /home/walterk/.cache/lambdanative/android/android-ndk-r13b-arm64-21-toolchain
BUILD FAILED
make: *** [Makefile:2: all] Error 1```

**Comment by karliwalti** [comment]
solution:

$ANDROIDNDK/build/tools/make-standalone-toolchain.sh is calling a python script. Therfore system needs to have python installed.

**Comment by peterlew** [comment]
Thanks for finding this! I've added `python` as a required tool to the Getting Started page for android development.

**Comment by mgorges** [comment]
Added as a requirement to [targets/android/check-tools](https://github.com/part-cw/lambdanative/blob/master/targets/android/check-tools) in d21034a to enforce this.
