### ISSUE TITLE
Can glgui-chat be dynamic?

### ISSUE THREAD

**Issue by Silverbeard00** [part-cw/lambdanative#199]
I'm trying to figure out how I can append new messages onto a glgui-chat box but I'm unable to find anything in the docs or source code.  Is this not possible?  

From it looks like I would have to destroy the widget,  add the new message to the original list saved somewhere else, and then recreate the widget with the new item.   This seems a bit unwieldy so I'm wondering if there is a better way to handle this.  I was just trying to see if a semi-realtime chat would work in lambdanative.

Thanks!

**Comment by mgorges** [comment]
@Silverbeard00, it doesn't have to be destroyed - you can simply update the `list` in the widget and it will re-render. If you are looking for an example of its use look at [apps/DemoSerial/main.scm#L167](https://github.com/part-cw/lambdanative/blob/master/apps/DemoSerial/main.scm#L167) or [apps/DemoSerial/main.scm#L167](https://github.com/part-cw/lambdanative/blob/master/apps/DemoSerial/main.scm#L167). Also potentially see issue #176

**Comment by Silverbeard00** [comment]
Thank you, that answered my question.
