### ISSUE TITLE
glgui: high idle CPU load

### ISSUE THREAD

**Issue by lighhw68** [part-cw/lambdanative#202]
Compiled a few of the demo apps and noticed that on Linux I get easily 20% idle cpu load. 

I am worried how that would affect battery life on phones or laptops? 

Is that fixable somehow?

**Comment by mgorges** [comment]
The demo apps are purposefully kept simple; you need to sleep more (how much depends on your app) to reduce CPU load. E.g. add something like this to your event loop (the one with ` (lambda (t x y)`:

    ;; If all we do is redraw sleep a bit more 40usec (10 was from normal sleep)
    (if (fx= t EVENT_REDRAW)
      (thread-sleep! 0.04)
    )

**Comment by lighhw68** [comment]
Looks like it should be good enough .. don't want to turn on my big computer until the worst of the heat wave is over.

Is the periodic refresh/redraw needed for some glgui-internal reason or  because X11 expose and similar events are not handled?

**Comment by mgorges** [comment]
You need to event loop to keep the screen refreshed (e.g. when moved), deal with input events, and update values as they change. Let us know once you tested this if this works for you in which case the ticket can be closed.

**Comment by lighhw68** [comment]
Tested with Calculator app the idle load on Linux goes from 23% down to 8%. Much better but not quite sure this is good enough. 

Can't the EVENT_REDRAW get generated only when needed? In principle it should be possible to detect conditions that require a redraw?

**Comment by ionathanch** [comment]
According to https://tronche.com/gui/x/xlib/events/exposure/expose.html#XExposeEvent, `XExposeEvent` has a `count` field for how many more `XExposeEvent`s are to follow, so we could check for `count == 0` to trigger a redraw. Would this patch help things?

```diff
diff --git a/loaders/x11/x11_microgl.c b/loaders/x11/x11_microgl.c
index 947ce44..082da1a 100644
--- a/loaders/x11/x11_microgl.c
+++ b/loaders/x11/x11_microgl.c
@@ -218,7 +218,9 @@ void microgl_pollevents(void)
         motion=1;
         break;
       case Expose:
-        expose=1;
+        if (event.count == 0) {
+          expose=1;
+        }
         break;
       case ClientMessage:  
         if( (Atom) event.xclient.data.l[ 0 ] == win.WMDeleteWindow )
```

**Comment by lighhw68** [comment]
Doesn't work, I get

```
x11_microgl.c: In function ‘microgl_pollevents’:
x11_microgl.c:221:18: error: ‘XEvent’ has no member named ‘count’
         if (event.count == 0) {
```

I am now getting 75 expose events per second, what is generating them? I don't move or do anything else with the window so X should not generate any XExposeEvents.

Could those 75/s redraws really amount for 23% CPU load? Seems something is wrong with GL on my Linux.

Another thing that could be tried is X11 backing store.

**Comment by ionathanch** [comment]
Whoops, it looks like I should be fetching the XExposeEvent first. Could you try `event.xexpose.count` instead of `event.count`?

Could you also provide some details about your setup (Linux distro, CPU cores, memory)? I'm going to try to reproduce the issue in a VM and it'd be beneficial to use a roughly similar environment. When I've got it set up, I'll also try setting the backing store window attribute to `WhenMapped` or `Always`.

**Comment by lighhw68** [comment]
I will do some experimenting and compare with my ancient bare bones X11 programs that handle expose events explicitly. The frequent expose events are puzzling me. Even if the cpu load could be much lower with better  hw acceleration it leaves no time for cpu sleep. 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ionathanch** [comment]
Looks like Expose events are sent by `microgl_refresh()`, which is called in a loop in `loaders/common/main.c`, which sleeps for 10 ms every loop. This would explain why you're getting ~100 redraws per second. You could instead manually trigger redraws similar to how `scm_runflag` works, so in `modules/eventloop/eventloop.scm` (of course also declaring `scm_redrawflag` in `LNCONFIG.h.in`):

```scheme
(define app:redrawflag 0)
(define (app-redraw)
  (set! app:redrawflag 1))
(c-define (c-redrawflag () int "scm_redrawflag" ""
  (if (number? app:redrawflag) app:redrawflag 0)
  (set! app:redrawflag 0))
```

Then in the loop in `main.c`:

```c
if (scm_redrawflag()) {
  microgl_refresh();
}
```

Or forgo the convoluted mess entirely by calling the redraw event yourself when needed:

```c
(if (string=? (system-platform) "linux")
  ((c-lambda (int int int) void "microgl_hook") EVENT_REDRAW 0 0))
```

In a different paradigm apps would call this `(app-redraw)` whenever something changes on-screen, but currently it works the other way around: the main event loop (in Scheme) calls `(glgui-event t x y)` when an event comes in, and if the event is an `EVENT_REDRAW`, the widgets' draw-handlers will be executed. That the draw-handlers are triggered periodically and often is crucial to the functionality of some of the widgets; for instance, label widgets react to longpress events by waiting in the draw-handler to see if no button-up event occurs within half a second, after which it triggers drawing a copy/paste menu. Therefore, whether the above solutions will work (replacing the existing call to `microgl_refresh()`, that is) depends on whether the widgets you use in your particular app have such a dependency in its draw-handler.

In the end, sleeping for a longer period of time might be the best solution, assuming your app doesn't depend on depend on the redraw rate (e.g. for animating things). Changing `usleep(10000);` to `usleep(100000);` in `loaders/common/main.c` lowers my CPU usage for DemoHelloWorld from around 15% to 2% when idle; any more than 100 ms might be humanly noticeable.

**Comment by lighhw68** [comment]
Is it so that glgui itself doesn't keep track of internal conditions that should trigger a redraw? 

It would be easy to trigger a redraw whenever a key/touch event occurs .. and possibly trigger periodic redraws for say a second after the last touch or other event so cases like the long-press would be covered.

Some changes like changing state from other threads or callbacks would probably require explicitly triggering a  redraw, afaics it magically works now but isn't anywhere specified. 

Wondering if it is possible to find some good compromise to avoid that an app that is sitting totally idle for 20 minutes triggers 100 per second redraws all the time. 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lighhw68** [comment]
I understand that you are reluctant to make such a big change, would it be possible  to have the programmer switch between this variants ? If programmers will use it they would identify the difficult corner cases, simple apps may profit easily and it would not be difficult to return to current behavior if case some unexpected problems arise. 

Good that you mention how the periodic data fetching in the oximetry app works, I was already wondering how async process like this would fit into the glgui programming model.

Doing it in the glgui event loop I am expecting would mean: 

* if the data fetch takes "longer" time it would render the gui unresponsive? 

* would anything relying on the event loop  stop when the app is moved to background so some data might get lost? 

Btw I have noticed the "androidbackground" module but don't see it used or documented anywhere?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lighhw68** [comment]
I have tested it on Android and it is even worse than expected: without any patches or changes Calculator consumes approximately 32% CPU time totally idle.. just blinking the cursor.

After pushing it to background with "home" it would apparently stay forever and consume about 0.1% CPU time and some amount of memory which is displayed as 940MB by top but only 25/17/16  MB by "OS Monitor" .. whatever those numbers mean.

**Comment by mgorges** [comment]
@clpetersen can you comment on this as well as the proposed changes, please?

**Comment by mgorges** [comment]
Should be mitigated by #330.
