### ISSUE TITLE
make.sh: Syntax error: redirection unexpected

### ISSUE THREAD

**Issue by juan-reynoso** [part-cw/lambdanative#207]
I read the Getting-Started https://github.com/part-cw/lambdanative/wiki/Getting-Started, so the  Step 4: Start the build: I had an error.

Info:

./make.sh: 829: ./make.sh: Syntax error: redirection unexpected
make: *** [Makefile:2: all] Error 2

O.S.:  Debian GNU/Linux

**Comment by ionathanch** [comment]
Many Linux distributions have `dash` as their default shell (i.e. `/bin/sh` will point to `dash`), but our scripts use `bash`. You can see what yours points to using `ls -l /bin/sh`. To fix this problem, you can change all references to `/bin/sh` in our scripts to `/bin/bash`, or you can change your `/bin/sh` to point to `bash` using `ln -sf bash /bin/sh`.

**Comment by juan-reynoso** [comment]
I changed it and it works, thanks.
