### ISSUE TITLE
problems with the '<<<' operator in make.sh

### ISSUE THREAD

**Issue by josrr** [part-cw/lambdanative#210]
I can only compile if I change the first line of make.sh to use /bin/bash
/bin/sh does not seem to know the operator '<<<':

```
lambdanative$ make
./make.sh: 829: ./make.sh: Syntax error: redirection unexpected
make: *** [Makefile:2: all] Error 2
```

**Comment by mgorges** [comment]
What is the default shell? - Also see [Issue 207](https://github.com/part-cw/lambdanative/issues/207)

**Comment by josrr** [comment]
Yes, it's Debian and it's dash.

Thank you. I checked if it was reported, it seems that I did not do very well.

**Comment by mgorges** [comment]
Maybe we should hardcode it to `bash` or is there a test we could employ to inform the user that his shell might not meet our needs?

**Comment by mgorges** [comment]
This problem was introduced in 353d4f6, we might have been able to use any other shell before? @ionathanch can you either rewrite that or we would need to change the default shell line. Thanks.

**Comment by karliwalti** [comment]
@ionathanch 

Still get 
```
$ make
./make.sh: 863: ./make.sh: Syntax error: Bad for loop variable
make: *** [all] Error 2
```
which is 
`for (( i = ${#domains[@]} - 2; i >= 0; i-- )); do`
