### ISSUE TITLE
Deployment of included files

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#212]
The localization files are integrated into the packages in android and ios, but only deployed if not yet existing. How can the  overwriting the existing files on the system be forced?

**Comment by ddunsmuir** [comment]
Put an exclamation mark in front of the file in the EMBED. Then that file will always be extracted, even if it already exists.

**Comment by ddunsmuir** [comment]
I have updated the [EMBED page](https://github.com/part-cw/lambdanative/wiki/Embed) with these details. This is found within the [Application Structure](https://github.com/part-cw/lambdanative/wiki/Application-Structure)  part of the wiki.
