### ISSUE TITLE
MacOS Mojave/Xcode 10.0: clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployme\ nt target of iOS 7 [-Wdeprecated] 

### ISSUE THREAD

**Issue by BusFactor1Inc** [part-cw/lambdanative#215]
To resolve, set IOSVERSION=7.0 in SETUP.

**Comment by mgorges** [comment]
This should be a warning, which you can ignore for the moment. I'd rather not remove iOS 6 support for the time being as it removes 4th-generation iPod Touches.

**Comment by mgorges** [comment]
Changed the `SETUP.template` in commit cec791d for future users; current ones should be able to continue to use their file until XCode 11 (or later) actually drops iOS6 support.

**Comment by BusFactor1Inc** [comment]
On my system it is not a warning but an error that causes the build to fail.  Setting IOSVERSION to 7.0 was the only way to get the Calcuator to build and install on my iPhone.  If you would like I could set it back to 6.0 and provide the full output to show the error.

**Comment by mgorges** [comment]
The error actually seems to be this, but the solution of setting the IOSVERSION=7 fixes that too:
`ld: library not found for -lstdc++`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
