### ISSUE TITLE
Is there a way to get geographic location using LambdaNative?

### ISSUE THREAD

**Issue by BusFactor1Inc** [part-cw/lambdanative#216]
I'm interested in writing an app that needs your current physical/geographic location on iOS.  Are there any functions available to determine such information?

**Comment by mgorges** [comment]
Please see the Wiki pages on [GPS](https://github.com/part-cw/lambdanative/wiki/Index-of-Module-gps), as well as its Demo app: [DemoSensors](https://github.com/part-cw/lambdanative/tree/master/apps/DemoSensors).

**Comment by BusFactor1Inc** [comment]
Ah yes, sorry.  I couldn't think of what the module would be named but now it seems obvious.  Thank you.
