### ISSUE TITLE
How does one view the log file on iOS?

### ISSUE THREAD

**Issue by BusFactor1Inc** [part-cw/lambdanative#220]
I have a crash on iOS that isn't happening on macOS. 

I found these debugging instructions:

https://github.com/part-cw/lambdanative/wiki/Debugging

I've put in the code to create the /log directory, but I'm not sure how to view the log file on iOS.

I can't find it through the Files application.

**Comment by mgorges** [comment]
You used to be able to get the files with `iTunes` in the `File Sharing` section but I don't know if this currently works. You might be able to find things through `XCode` using 'Installed Apps' in 'Devices and Simulators' but I don't know what they changed there lately and don't wish to break my setup to find out.

**Comment by mgorges** [comment]
Two things:
1. The logfiles are not in the place specified to look for in Xcode
1. For applications, that don't use the scheduler, you have to manually force the creation of the log file folder, e.g.
```(let ((logdir (string-append (system-directory) (system-pathseparator) "log")))
    (if (not (file-exists? logdir)) (create-directory logdir)))

**Comment by mgorges** [comment]
> I can't find it through the Files application.

Correct, this doesn't give you access to any of the files for any apps, only those loaded specifically for a different context. If you still have iTunes that works as of MacOS 10.14.6, but likely will need a new solution once iTunes goes away in 10.16.

**Comment by mgorges** [comment]
In MacOS _Catalina_, you can access the log files through Finder if you navigate to your device, select **_Files_** and then go to the _**application**_ which contains a **_log_** folder. Files will only appear starting with the second run, as in the initial run the folder isn't created until after the log file is to be written. You can drag this **_log_** folder to a different location as with any other folder, which copies the content. See below for a screenshot:
<img width="419" alt="FinderLogfiles" src="https://user-images.githubusercontent.com/4401074/94634919-3ac82300-0286-11eb-8e20-cc4b27a03e51.png">
