### ISSUE TITLE
Is there a way to create an app that has a space in the file name?

### ISSUE THREAD

**Issue by BusFactor1Inc** [part-cw/lambdanative#221]
It seems that spaces in the app directory name is not allowed, and that seems to be how the application name is set.  Is there another way to set the application name so that it can contain spaces, since spaces in the directory name causes configure to fail.

**Comment by mgorges** [comment]
As for spaces - this was a problem before, see issue [155](https://github.com/part-cw/lambdanative/issues/155). - We currently don't support it as there are issues with escaping spaces on multiple platforms and the fact that we use it to make various other variables. - I believe Android app names don't allow spaces either?

**Comment by peterlew** [comment]
We don't support *building* with a space in the app name, but there are easy ways to change the name in appearance, both on the icon and the window bar (if applicable). These will allow for names with spaces. 

iOS
-
1. Open `loaders/ios/Info.plist.in` and find the following:
```
<key>CFBundleDisplayName</key>
<string>@SYS_APPNAME@</string>
```
2. Replace `@SYS_APPNAME` with your desired app name.

Android
-
1. Open `loaders/android/AndroidManifest.xml.in` and find the following:
```
<activity android:name="@SYS_APPNAME@"
              @ANDROID_ACTIVITY_ATTRIBUTES@
              android:label="@string/app_name"
              android:launchMode="standard">
```
2. Replace `@string/app_name` with your desired app name.

OS X
-
1. `make` and `make install`.
2. Find app icon, right-click, and select "Show Package Contents".
3. Rename the UNIX executable file to the new name.
4. Rename the app to the new name. 

Linux
-
1. Open `loaders/x11/x11_microgl.c` and find the following:
```
XStoreName( Dpy, win.Win, SYS_APPNAME);
XSetIconName( Dpy, win.Win, SYS_APPNAME);
```
2. Replace `SYS_APPNAME` with your desired app name.
3. `make` and `make install`.
4. Rename executable file.
5. Rename application folder.
