### ISSUE TITLE
Where to have general discussion about lambdanative?

### ISSUE THREAD

**Issue by silasdb** [part-cw/lambdanative#227]
Hi!

I searched it but didn't find anything. Is there a mail list, IRC channel or anything to for general talk about lambdanative? The wiki initial page (https://github.com/part-cw/lambdanative/wiki) even says that, for any lambdanative specific question, an issue should be opened here on github. Is this right?

Thanks!

**Comment by mgorges** [comment]
Dear @silasdb, 
there is no other channel that I am aware off. The developer community is rather small so we didn't think there was a need for it yet - however, if there is the need to revise, we can certainly consider a mailing list - I don't have time to monitor an IRC channel. Thanks

**Comment by 11111000000** [comment]
@mgorges  Gitter? Spectum?

**Comment by lighhw68** [comment]
I think a mailing list would be nice. Btw it seems the github wiki doesn't have something like talk pages?

**Comment by mgorges** [comment]
@11111000000, I am not familiar with either https://spectrum.chat or https://gitter.im and likely don't have the capacity to monitor a channel in either. However, I am happy to propose it to others in the team.

**Comment by mgorges** [comment]
@lighhw68 maintaining an email list installation, dealing with spam and managing subscribers is also not something we can commit to.

**Comment by mgorges** [comment]
If I had to pick one, probably https://gitter.im due to its integration in Github - alternatively, https://stackoverflow.com ?

**Comment by mgorges** [comment]
Having read more about it Gitter is owned by GitLab but Spectrum by GitHub, which means it is more likely to get deeper integration at some point. Thus have setup: https://spectrum.chat/lambdanative
