### ISSUE TITLE
Docker image with build environment

### ISSUE THREAD

**Issue by 11111000000** [part-cw/lambdanative#230]
I ran into issues with build on NixOS, because of  `-I/usr/X11/include` missing, and spent some time to resolve this. How about to support official docker image with configured build environment?

**Comment by mgorges** [comment]
Sorry, but I don't have the capacity to support this as it adds ongoing maintenance. - Would it better to provide a patch, with identifies the path in a smarter way?

**Comment by 11111000000** [comment]
Maybe. In case of NixOS that would be configuration option, i.e. GLPATH or something more general...

**Comment by mgorges** [comment]
Been years without response; we don't want to create a docker image so closing this. Feel free to reopen with a patch for your path issue.
