### ISSUE TITLE
fft module tries to fetch from now invalid source

### ISSUE THREAD

**Issue by recumbentbirder** [part-cw/lambdanative#231]
Using the 'fft' module makes lambdanative try to fetch the library that module is based upon (ffts) from http://anthonix.com/ffts/releases/ffts-0.7.tar.gz which is not a valid source any longer.

https://github.com/anthonix/ffts seems to be the currently available source.

**Comment by mgorges** [comment]
Thanks for bringing this to our attention. I had in the past tried to use a 2015 version of the Github version [ffts:dfab21f](https://github.com/anthonix/ffts/commit/dfab21f8096660f441fb33bf5012e7f2c3652fa9), however it requires additional patches for `neon`, `malloc` (win32, macOS), `sse` which might now have been added? Will investigate.

**Comment by mgorges** [comment]
Quick update: the version from the Github repository doesn't build with autoconf/configure/make, even when moving the `ftts.h` file in the right place and fixing the library includes - see an [issue #68](https://github.com/anthonix/ffts/issues/68) which says to use `cmake` only. I did try the [linkotec](https://github.com/linkotec/ffts) fork, but that doesn't help either. 
Options are:
1. Host the `ffts-0.7.tar.gz` file in the LN website, as we do for `libgd` 
1. Upgrade but use `cmake` to compile, which might not be available on all platforms. Also don't know how to cross-compile with it.

**Comment by lighhw68** [comment]
I would say option #1 unless there is a very good reason to use the bleeding edge github source?

**Comment by mgorges** [comment]
Commit 6317028 does restore the ability to compile for the time being.

**Comment by recumbentbirder** [comment]
Cool, thank you. Runs perfectly now.
