### ISSUE TITLE
procedure command-line returns empty list

### ISSUE THREAD

**Issue by 0-8-15** [part-cw/lambdanative#236]
in a fresh created a console application

$ lambdanative create myapp console

In apps/myapp/main.scm add at top:

(display (command-line))

Displays the empty list for me.

**Comment by mgorges** [comment]
I am sorry, but I don't quite understand your question. I am also not familiar with the `command-line` function and from a quick search we don't use it anywhere in our applications. 

Are you asking for how to retrieve the command line arguments in an application? If so [system-cmdarg](https://github.com/part-cw/lambdanative/wiki/system-cmdarg), or if there are more than one `system-cmdargc` should work - also see the wiki for the list of functions included in the [config](https://github.com/part-cw/lambdanative/wiki/Index-of-Module-config) module.

**Comment by 0-8-15** [comment]
Thanks, the config modules bindings solved my problems.

The `command-line` procedure is documented in the `gambit-c` manual.  Apparently not applicable.
