### ISSUE TITLE
Text color of button

### ISSUE THREAD

**Issue by saman-pasha** [part-cw/lambdanative#244]
How to set the string color of glgui-button-string or glgui-button-local

**Comment by mgorges** [comment]
`(glgui-widget-set! gui b 'color Red)` should work as it inherits this property from [glgui-label](https://github.com/part-cw/lambdanative/wiki/glgui-label)? The [glgui-button wiki page](https://github.com/part-cw/lambdanative/wiki/glgui-button) should also have an example which might apply here.

**Comment by saman-pasha** [comment]
thank you
