### ISSUE TITLE
Label alignment

### ISSUE THREAD

**Issue by saman-pasha** [part-cw/lambdanative#246]
There is an attribute 'align' for string horizontal alignment of label
what is the attribute of vertical alignment?

**Comment by ddunsmuir** [comment]
There is no vertical alignment attribute. In LambdaNative you cannot current control that.

(glgui-label) creates a one line label no matter the height of it, the text will be centered vertically. I recommend keeping your label height to the height of the font for a one-line label, so centring doesn't really matter.

(glgui-label-wrapped) creates a multi-line label which starts at the top and fills in lines downward (a vertically alignment of top).

**Comment by saman-pasha** [comment]
OK, I use negative height value for fixing verticaliy
