### ISSUE TITLE
SDL2

### ISSUE THREAD

**Issue by on91** [part-cw/lambdanative#251]
Is it possible to support SDL2, SDL2-image and SDL2-ttf in android ?

**Comment by mgorges** [comment]
If this is something that is cross-platform, maybe, as we wouldn't want to build something Android-specific! From a quick glance at http://www.libsdl.org it seems that it provides `low level access to audio, keyboard, mouse, joystick, and graphics hardware via OpenGL and Direct3D` so I am not sure why we would need this as we already support for most of these features? Can you be more specific what features we are currently lacking that you might need?

It is certainly not something that would make it on my toDo list anytime soon (or at all), but you are welcome to submit some pull requests if you do an implementation of it for us to consider.
Sorry, Matthias
