### ISSUE TITLE
input editing in uiform vs. glgui

### ISSUE THREAD

**Issue by 0-8-15** [part-cw/lambdanative#258]
So far I'm using uiform for some rather simple, though flexible GUIs.

The input editing of uiform capabilities are bothering me: only backspace allows to chop of the last character and the clipboard is unavailable.

In the code of `glgui/label.scm` I found code, which seems to do line editing and clipoard cut&paste.  Unfortunately I don't understand enough of the code to make `uiform`s `label` use the latter or mix `uiform` and `glgui`.

Possible? How?

**Comment by ddunsmuir** [comment]
Ah, yes, in some ways the GUI within uiform is reinventing the wheel as it doesn't use any of the existing glgui code. You are correct that we don't have use of the clipboard in there yet or jumping the cursor to different part of the string by tapping/clicking on them. We may eventually add this, when we have more time or if you want to work on it.

Another possibility for now may be to use the glgui/label.scm within the uiform for those fields you really want to have those features. We designed the function [(uiform-register-legacy)](https://github.com/part-cw/lambdanative/wiki/uiform-register-legacy) exactly for this reason, to use the glgui components within uiform. Let me know if you have any problems.

**Comment by 0-8-15** [comment]
Am Tue, 03 Sep 2019 10:05:50 -0700
schrieb Dustin <notifications@github.com>:

> Ah, yes, in some ways the GUI within uiform is reinventing the wheel
> as it doesn't use any of the existing glgui code.

Hm.  Except that it depends on it.  ;-)

> You are correct
> that we don't have use of the clipboard in there yet or jumping the
> cursor to different part of the string by tapping/clicking on them.
> We may eventually add this, when we have more time or if you want to
> work on it.
> 
> Another possibility for now may be to use the glgui/label.scm within
> the uiform for those fields you really want to have those features.
> We designed the function
> [(uiform-register-legacy)](https://github.com/part-cw/lambdanative/wiki/uiform-register-legacy)
> exactly for this reason, to use the glgui components within uiform.
> Let me know if you have any problems.

I shall try.

Thank you so much for the hint.

**Comment by 0-8-15** [comment]
Am Tue, 03 Sep 2019 10:05:50 -0700
schrieb Dustin <notifications@github.com>:

> Ah, yes, in some ways the GUI within uiform is reinventing the wheel
> as it doesn't use any of the existing glgui code. You are correct
> that we don't have use of the clipboard in there yet or jumping the
> cursor to different part of the string by tapping/clicking on them.
> We may eventually add this, when we have more time or if you want to
> work on it.
> 
> Another possibility for now may be to use the glgui/label.scm within
> the uiform for those fields you really want to have those features.
> We designed the function
> [(uiform-register-legacy)](https://github.com/part-cw/lambdanative/wiki/uiform-register-legacy)
> exactly for this reason, to use the glgui components within uiform.
> Let me know if you have any problems.

I do have problems.  :-/

I tried the following:

     (uiform-register-legacy 'text glgui:label-draw glgui:label-input)

To test I created a textentry replacement like this:


    (define (test-text-extry)
      (lambda ()
        `(text
          enableinput #t label ,(dbget 'CN "<<<noting here yet>>>")
          font ,(uiget 'fnt)
          focuspos 0
          align ,GUI_ALIGNLEFT
          color ,Black
          direction ,GUI_LEFTTORIGHT
          longpress (#f #f 0)
          longpress-range 10
          longpress-duration 0.5
          longpress-callback ,glgui:label-copypaste-overlay
          aftercharcb
          ,(lambda (g wgt type mx my) (dbset 'CN (glgui-widget-get g
    wgt 'label))))))

(((Looks a bit tedious, but I don't mind [for now].)))

Which I than used in an uiform page like this

    (test-text-extry)

If I remove any of the attributes in this `(test-tex-entry)` thingy, it
will crash, otherwise I can follow via instrumented code that it does
actually renders the label somehow.

BUT: I don't see it!  The resulting page does simply not contain any
trace of it.

My initial guess was that the size calculation might be wrong and
uiform elements following it would draw over it.  To test for this, I
moved it to the very bottom of the (mostly empty) uiform page.  But
that did not change a thing.

I'd appreciate any hint.  Best would be a working code snippet.

Thank you soo much!

/Jörg

**Comment by 0-8-15** [comment]
Wait!

Just after I wrote this, I figured out that the glgui-lable *is*
actually drawn!!!

Just all positions are way off.  And I had to mess with the colors to
find it.

Sill appreciating a working example.

Best

Am Sun, 29 Sep 2019 21:04:12 +0200
schrieb "Jörg F. Wittenberger" <Joerg.Wittenberger@softeyes.net>:

> Am Tue, 03 Sep 2019 10:05:50 -0700
> schrieb Dustin <notifications@github.com>:
> 
> > Ah, yes, in some ways the GUI within uiform is reinventing the wheel
> > as it doesn't use any of the existing glgui code. You are correct
> > that we don't have use of the clipboard in there yet or jumping the
> > cursor to different part of the string by tapping/clicking on them.
> > We may eventually add this, when we have more time or if you want to
> > work on it.
> > 
> > Another possibility for now may be to use the glgui/label.scm within
> > the uiform for those fields you really want to have those features.
> > We designed the function
> > [(uiform-register-legacy)](https://github.com/part-cw/lambdanative/wiki/uiform-register-legacy)
> > exactly for this reason, to use the glgui components within uiform.
> > Let me know if you have any problems.
> 
> I do have problems.  :-/
> 
> I tried the following:
> 
>      (uiform-register-legacy 'text glgui:label-draw glgui:label-input)
> 
> To test I created a textentry replacement like this:
> 
> 
>     (define (test-text-extry)
>       (lambda ()
>         `(text
>           enableinput #t label ,(dbget 'CN "<<<noting here yet>>>")
>           font ,(uiget 'fnt)
>           focuspos 0
>           align ,GUI_ALIGNLEFT
>           color ,Black
>           direction ,GUI_LEFTTORIGHT
>           longpress (#f #f 0)
>           longpress-range 10
>           longpress-duration 0.5
>           longpress-callback ,glgui:label-copypaste-overlay
>           aftercharcb
>           ,(lambda (g wgt type mx my) (dbset 'CN (glgui-widget-get g
>     wgt 'label))))))
> 
> (((Looks a bit tedious, but I don't mind [for now].)))
> 
> Which I than used in an uiform page like this
> 
>     (test-text-extry)
> 
> If I remove any of the attributes in this `(test-tex-entry)` thingy,
> it will crash, otherwise I can follow via instrumented code that it
> does actually renders the label somehow.
> 
> BUT: I don't see it!  The resulting page does simply not contain any
> trace of it.
> 
> My initial guess was that the size calculation might be wrong and
> uiform elements following it would draw over it.  To test for this, I
> moved it to the very bottom of the (mostly empty) uiform page.  But
> that did not change a thing.
> 
> I'd appreciate any hint.  Best would be a working code snippet.
> 
> Thank you soo much!
> 
> /Jörg
> 
> 
> 
>

**Comment by 0-8-15** [comment]
Looks like it's extremely fragile, whether or not anything is rendered.

Depending on the use (last on the page or not) and who knows what else,
I see either the rendered string (on the wrong position) or not, or I
see it for a fraction of a second and than it disappears.

:-/

Am Sun, 29 Sep 2019 21:04:12 +0200
schrieb "Jörg F. Wittenberger" <Joerg.Wittenberger@softeyes.net>:

> Am Tue, 03 Sep 2019 10:05:50 -0700
> schrieb Dustin <notifications@github.com>:
> 
> > Ah, yes, in some ways the GUI within uiform is reinventing the wheel
> > as it doesn't use any of the existing glgui code. You are correct
> > that we don't have use of the clipboard in there yet or jumping the
> > cursor to different part of the string by tapping/clicking on them.
> > We may eventually add this, when we have more time or if you want to
> > work on it.
> > 
> > Another possibility for now may be to use the glgui/label.scm within
> > the uiform for those fields you really want to have those features.
> > We designed the function
> > [(uiform-register-legacy)](https://github.com/part-cw/lambdanative/wiki/uiform-register-legacy)
> > exactly for this reason, to use the glgui components within uiform.
> > Let me know if you have any problems.
> 
> I do have problems.  :-/
> 
> I tried the following:
> 
>      (uiform-register-legacy 'text glgui:label-draw glgui:label-input)
> 
> To test I created a textentry replacement like this:
> 
> 
>     (define (test-text-extry)
>       (lambda ()
>         `(text
>           enableinput #t label ,(dbget 'CN "<<<noting here yet>>>")
>           font ,(uiget 'fnt)
>           focuspos 0
>           align ,GUI_ALIGNLEFT
>           color ,Black
>           direction ,GUI_LEFTTORIGHT
>           longpress (#f #f 0)
>           longpress-range 10
>           longpress-duration 0.5
>           longpress-callback ,glgui:label-copypaste-overlay
>           aftercharcb
>           ,(lambda (g wgt type mx my) (dbset 'CN (glgui-widget-get g
>     wgt 'label))))))
> 
> (((Looks a bit tedious, but I don't mind [for now].)))
> 
> Which I than used in an uiform page like this
> 
>     (test-text-extry)
> 
> If I remove any of the attributes in this `(test-tex-entry)` thingy,
> it will crash, otherwise I can follow via instrumented code that it
> does actually renders the label somehow.
> 
> BUT: I don't see it!  The resulting page does simply not contain any
> trace of it.
> 
> My initial guess was that the size calculation might be wrong and
> uiform elements following it would draw over it.  To test for this, I
> moved it to the very bottom of the (mostly empty) uiform page.  But
> that did not change a thing.
> 
> I'd appreciate any hint.  Best would be a working code snippet.
> 
> Thank you soo much!
> 
> /Jörg
> 
> 
> 
>

**Comment by ddunsmuir** [comment]
Hey, sorry I do not have access to a computer over the next couple of weeks to look at this in depth. I apologize for suggesting you could easily plug in the draw procedure from label.scm into the uiform. In this case it is not that straightforward. The inputs and outputs do not match what is expected. I suggest you make a procedure that uses glgui:label-draw, but handles the input and output properly.

**Input:**
Look at glgui:uiform-textentry-draw in uiform. It takes the following arguments: x y w . args
These are not consistent with glgui:label-draw which expects: g x y w h label fnt color . bgcolor
Thus you need to write a procedure that takes in x y w . args and then send glgui:label-draw what it expects.

**Output:**
You may notice that all the uiform draw procedures such as glgui:uiform-textentry-draw end with (return) the height of the item being drawn. Since glgui:label-draw does not do this, it may assume it has a height of 0 and just overwrite it with the next item. Your procedure that you wrap around glgui:label-draw should return the height.

I hope that helps. I will try to put together an example when I have more time, if you don't have one constructed yourself by mid-October.

Cheers,
Dustin

**Comment by peterlew** [comment]
When initializing an element that has been registered with `uiform-register-legacy`, you should set all fields that could be accessed during the draw or input calls. The safest way to do this is to copy code from the relevant constructor function - in this case, copy all the fields straight from the `glgui-label` function in [ln_glgui/label.scm](https://github.com/part-cw/lambdanative/blob/master/modules/ln_glgui/label.scm).

The following code will let you use a glgui-label with any of its native functionality within UIForm:

In initialization: 
`(uiform-register-legacy 'myText glgui:label-draw glgui:label-input)`
And in the UIForm: 
```
(myText
     old-mx #f
     old-my #f
     rounded #f
     font ,ascii_18.fnt
     label "Registered Legacy Label"
     callback #f
     aftercharcb #f  
     onfocuscb #f   
     armed #f
     longpress (#f #f 0) 
     longpress-range 10
     longpress-duration 0.5 
     longpress-callback ,glgui:label-copypaste-overlay
     copyable? #t
     pastable? #t
     color ,White
     hidden #f
     direction ,GUI_LEFTTORIGHT
     password #f
     enableinput #t 
     focus #f
     focuspos 0
     clearoninput #f
     showstart #f 
     bgcolor #f
     align ,GUI_ALIGNCENTER
     draw-handle  ,glgui:label-draw
     input-handle ,glgui:label-input
     update-handle ,glgui:label-update
  )
```

This is copied straight from the `glgui-label` function, then edited however you need. It could also easily be wrapped in a new function if you're making several of them. In my testing it behaves similarly to 

```
      (set! stdLabel (glgui-label gui 120 400 200 20 "Standard Label" ascii_18.fnt White)))
      (glgui-widget-set! gui stdLabel 'enableinput #t)
      (glgui-widget-set! gui stdLabel 'align GUI_ALIGNCENTER)
      (glgui-widget-set! gui stdLabel 'copyable? #t)
      (glgui-widget-set! gui stdLabel 'pastable? #t)
```
