### ISSUE TITLE
Linker needs libsndio on linux

### ISSUE THREAD

**Issue by zwieblum** [part-cw/lambdanative#271]
Linker needs to add "-lsndio" to li nk correctly on devuan/beowulf and debian/buster:

$ diff ./targets/linux/build-binary~ ./targets/linux/build-binary
68c68
<       -L$SYS_PREFIX/lib $ldflag_additions -lpayload -lGL -lXext -lX11 -lasound -lrt -lutil -lpthread -ldl -lm"
---
>       -L$SYS_PREFIX/lib $ldflag_additions -lpayload -lGL -lXext -lX11 -lasound -lrt -lutil -lpthread -ldl -lm -lsndio"

**Comment by mgorges** [comment]
This is an audio library so adding this link should only be needed for projects that use parts of the `audio` module or the `libportaudio` library? So would we still need to add a new dependency for all linux-based systems? That said issue #190 also required this addition and there is a patch for BSD in [libraries/libportaudio/openbsd.patch](https://github.com/part-cw/lambdanative/blob/master/libraries/libportaudio/openbsd.patch)

**Comment by zwieblum** [comment]
Yes, it's ony needed when the audio module is used. Interestingly the openbsd patch is applied when comiling on linux, too.

**Comment by mgorges** [comment]
The patch shouldn't do anything for Linux, but just to be on the safe side, would you mind deleting the patch file locally and see if you can compile on Linux without the `-lsndio` addition?

**Comment by zwieblum** [comment]
Compiles fine without the openbsd.patch deleted and without -lsndio.

**Comment by mgorges** [comment]
Thanks for checking - so a better approach might be to patch only for OpenBSD but no other platforms.

**Comment by zwieblum** [comment]
IMO that would be thze correct way.
