### ISSUE TITLE
Post / get hybrid app

### ISSUE THREAD

**Issue by gassechen** [part-cw/lambdanative#277]
Hi. excellent job. If this is not a problem, they could put an example of a post / get method in a hybrid application. Thank you.

**Comment by mgorges** [comment]
@gassechen sorry, but I am not quite sure I understand your request - are you wondering about how to communicate with a hybrid application from the outside, i.e. using a TCP service, or how the browser interacts with the client as [apps/DemoHybridApp/main.scm](https://github.com/part-cw/lambdanative/blob/master/apps/DemoHybridApp/main.scm) only shows a simple webpage being loaded?

**Comment by gassechen** [comment]
I will try to explain myself better. How can I put a form in my hybrid application and through the post / get method process the data in my main.scm?

**Comment by mgorges** [comment]
I'll check with @ddunsmuir on Monday as all the examples I have right now require a bunch of dependencies like `framework7` and other modules we did make public yet.

**Comment by gassechen** [comment]
Thanks for your attention. I will be attentive to the news.

**Comment by ddunsmuir** [comment]
Yes, you are right that the example is very basic and does not show communication between a web front-end (HTML, Javascript) and a Scheme backend. I will add an example of this to the app.

**Comment by gassechen** [comment]
Hello dunsmuir. The hybrid app is a relationated with a mobile device. But i m write a codes in my linux or Android.
<code>
(define db (website->table "/storage/emulated/0/vmc"))

(website-serve db 8080)
 </code>
Thisis an simple http server the   document root is route defined (website->table "/my_document_root"). And in this route i have all html/css/js documents. its Great lambdanative. I intent a ajax JavaScript whit json but cant do this  working in my scheme server side. At the moment i do this because i no expert in a ssax.
Thank. My english is very limited. 
meant i do this because i no expert in a ssax.
Thank.

**Comment by ddunsmuir** [comment]
I have [committed an update](https://github.com/part-cw/lambdanative/commit/f5081f11ab59184a1641de579a1580f5ba7e4113). I have added an example of a GET method to backend Scheme from Javascript. It sends the values from a form. Calculations are then done in Scheme and returned in JSON format (encoded as a u8 vector).

**Comment by gassechen** [comment]
Gracias.

**Comment by ddunsmuir** [comment]
@gassechen I have now also updated the DemoHybrid app to show how to use a CSS file. https://github.com/part-cw/lambdanative/commit/1afa5630c10c3481117a91bf44495994a37a0428
