### ISSUE TITLE
ANDROID_activity_attributes needs leading \n

### ISSUE THREAD

**Issue by zwieblum** [part-cw/lambdanative#287]
ANDROID_activity_attributes needs to start with an empty line. If not, the substition merges  the user-provided attribute-line with the preceeding line giving an error:

Example: ANDROID_activity_attributes:
`android:screenOrientation="portrait"
`

is transformed to:
`android:configChanges="orientation|screenSize"android:screenOrientation="portrait"`

... which does not build. 

But ANDROID_activity_attributes:
`                                                      `
`android:screenOrientation="portrait"`

is transformed to:
`android:configChanges="orientation|screenSize"` 
`android:screenOrientation="portrait"`

... which does build.

**Comment by mgorges** [comment]
I am not sure if this would be considered a bug in [targets/android/build-binary#L58](https://github.com/part-cw/lambdanative/blob/9fe5b9dd0f4c30a027adfe1156f13eb1eaa6adf1/targets/android/build-binary#L58) or a case of a missing line break at the end of [modules/hybridapp/ANDROID_activity_attributes](https://github.com/part-cw/lambdanative/blob/master/modules/hybridapp/ANDROID_activity_attributes), which seems the only place where this is used?

**Comment by mgorges** [comment]
9926bbc adds extra line break to [modules/hybridapp/ANDROID_activity_attributes](https://github.com/part-cw/lambdanative/blob/master/modules/hybridapp/ANDROID_activity_attributes)

**Comment by zwieblum** [comment]
Works now as expected. IMO targets/android/build-binary should insert extra \n before and after each substitution in Androidmanifest.xml - a space should work, also. (some time in a not no distant future: "why is there a blank line at the end of the file?" "don't know" " then let's remove it" ...)

**Comment by mgorges** [comment]
I don't think we can change the default behaviour of the substitution to add new lines as that will break other things. If you have suggestions of how to to this specifically for the Android manifest component we'd welcome a pull request. Thanks.

**Comment by zwieblum** [comment]
Sorry, did not manage the pull request. anyway, here's the patch against targets/android/build-binary

[build-binary.patch.txt](https://github.com/part-cw/lambdanative/files/4866040/build-binary.patch.txt)
