### ISSUE TITLE
simple template module + demo app

### ISSUE THREAD

**Issue by zwieblum** [part-cw/lambdanative#291]
This is the template module that I came up with. Does what I wanted it do :)
Demo application is included.

https://klepp.biz/template-and-demoapp.tar.xz

**Comment by zwieblum** [comment]
Ok, upload works again. Rename the file to template-and-demoapp.tar.xz 
[template-and-demoapp.tar.xz](https://github.com/part-cw/lambdanative/files/4964348/template-and-demoapp.tar.xz.txt)

**Comment by mgorges** [comment]
The copyright clause for this is incompatible for this project, which is licensed as BSD 2.0 - see [LICENSE](https://github.com/part-cw/lambdanative/blob/master/LICENSE)

**Comment by zwieblum** [comment]
Oh my, I always forget ... is this better?

[template-and-demoapp.tar.xz.txt](https://github.com/part-cw/lambdanative/files/5064285/template-and-demoapp.tar.xz.txt)

**Comment by mgorges** [comment]
Thanks for updating the license. - The code in `modules/template/template.scm` is so minimal, that I am wondering if instead it should become a feature of the website module instead of needing to have a separate module for it? Similarly, the `DemoWebTemplate` app could have the content of its `main.scm` added to the wiki documenting the new functions?

**Comment by zwieblum** [comment]
Sure, but there is room for improvement: template-processor in it's current form is not context-aware. When I have time (and need it), I will extend it to use dynamic data from cgi-env :)

**Comment by mgorges** [comment]
Please revise and expand upon the documentation for [Wiki: website](https://github.com/part-cw/lambdanative/wiki/Index-of-Module-website) as needed. Specifically, I renamed the functions to [(website-addsubstitution token proc)](https://github.com/part-cw/lambdanative/wiki/website-addsubstitution) and [(website-substitute data)](https://github.com/part-cw/lambdanative/wiki/website-substitute)

**Comment by mgorges** [comment]
> Sure, but there is room for improvement: template-processor in it's current form is not context-aware. When I have time (and need it), I will extend it to use dynamic data from cgi-env :)
Also please file a new issue, ideally as a pull request, when you have added these features.
