### ISSUE TITLE
Debug REPL Help

### ISSUE THREAD

**Issue by charJe** [part-cw/lambdanative#296]
When I connect to the running application using telnet. The repl appears in the shell where I ran `make install` like so 
```
==> attempting to install linux application DemoRedSquare to local desktop..
==> Starting application..
----
LambdaNative REPL
DemoRedSquare 1.0
Built 2020-07-30 18:13:00 (00h 00m 29s ago)
------------- REPL is now in #<thread #2 unnamed_thread> -------------
> 
```
In the shell where I run `telent -4 localhost 7000` I get only the regular telnet output, no repl. I know the are connected though because the repl doesn't appear until I run telent and when I terminate `make install`, telnet also shuts down. It is as if it is not piping the repl correctly through the internet port. Inputs into telnet never make it to the repl and nothing makes it back.

**Comment by mgorges** [comment]
No idea - this seems related? https://mailman.iro.umontreal.ca/pipermail/gambit-list/2013-September/006975.html

**Comment by mgorges** [comment]
@fungiblecog or @clpetersen were the ones who contributed to [modules/ln_repl](https://github.com/part-cw/lambdanative/tree/master/modules/ln_repl), so maybe one of them can help?

**Comment by charJe** [comment]
I'm not sure if it is related to that, but the repl I do get is also very slow. Separately from the DemoRedSquare, the web-repl works properly for me on it's own.

**Comment by charJe** [comment]
I hacked something together. It is not as fast as I hoped, but it is far better then running `make; make install;` every time I want to refresh my gui. 
https://gist.github.com/charJe/2ca7dfd56cfda0ec5c8eced9db1d19bc

Advantages to `make; make install`:
- faster compilation
- more interactive
- better error messages

Disadvantages the usual gambit REPL:
- none of the debugging `,` commands work. It just spits out the error and moves on. 
- a little slow but still faster than what I got to work with ln_repl.
-

**Comment by mgorges** [comment]
There is also [apps/tcprepl](https://github.com/part-cw/lambdanative/tree/master/apps/tcprepl), but it seems to be a console app, so I can't speak to its utility.

**Comment by charJe** [comment]
It looks like my tcprepl module is nearly identical to the tcprepl app. I was just missing the close connection. It would be nice to have the full gambit debugger though.

**Comment by charJe** [comment]
I have revised my gist to allow devices other than localhost and to fix an issue where the client would terminate leaving the thread to overpower and cause the server a lot of latency.

**Comment by mgorges** [comment]
Thanks @Kyuvi - upon quick inspection, this works and doesn't break anything else, so I added it. I don't understand `macro-absent-obj` sufficiently to make the other modification you suggested.

Regarding the use of `(args . rest)` over `(args #!optional opts)`, this is a question for @clpetersen, who started the framework. I can't speak to the design decision. Still, you are correct that `#!optional` is barely used and found almost exclusively in code contributed by developers other than the team at BC Children's.
