### ISSUE TITLE
glgui-dropdown-box not behaving

### ISSUE THREAD

**Issue by charJe** [part-cw/lambdanative#298]
The dropdown box technically works because it is getting the right values for the correct ones clicked. However, it does not display correctly. The text of the options lingers as does the grey box representing the selected entry. An additional problem is that I cannot scroll on computer.
```scheme
(glgui-dropdownbox gui 20 (- (glgui-height-get) 30 30 40) 100 30                                                 
  (map (lambda (str)                                                           
         (lambda (lg lw x y w h s)                                             
           (if s (glgui-box lg x y w h Grey))                             
           (glgui-label lg (+ x 5) y (- w 10) h str dejavu_18.fnt Black)))
       (map number->string (list 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24)))                             
  Black White Black)                                                     
```
There is a second dropdown on this page (Hours) that has all the same problems.
![Screenshot_20200805-150938](https://user-images.githubusercontent.com/45857837/89486014-acdd2980-d767-11ea-9c73-02283c17afe6.jpg)

**Comment by mgorges** [comment]
Please check the [Wiki: glgui-dropdownbox](https://github.com/part-cw/lambdanative/wiki/glgui-dropdownbox) for the functions to be used in the lambda piece: 
You use `glgui-box`, which makes a new (and persistent) widget, but you need to use functions that are only rendered if needed - the example uses `glgui:draw-box` which is a runtime call. Same for `glgui-label`, which makes a new (persistent) widget every time it is called, but you again only want the rendered version of `glgui:draw-text-left` (or some other alignment version of it).

**Comment by charJe** [comment]
Thank for helping me out.
