### ISSUE TITLE
Android build on linux broken

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#304]
With one of the recent commits the building of DemoHelloWorld for Android on linux got broken:

`==> creating android loader needed for DemoHelloWorld..
 => creating android project..
./make.sh: 1: targets/android/build-binary: /tools/android: not found
ERROR: API 24 not a target.
`

looks like the path can't be found because $ANDROIDSDK is empty? Unfortunately I can't identify a relevant change in the codebase for this part

**Comment by peterlew** [comment]
What is your ANDROIDAPI set to in SETUP? We made some changes around which API level to target in [targets/android/build-binary](https://github.com/part-cw/lambdanative/blob/master/targets/android/build-binary)

**Comment by mgorges** [comment]
Also, you will need the the SDK for API level 24, or whatever newer level you plan to use. Older levels should still work, e.g. I am using ANDROIDAPI=21. The change in e387cd2, which added dual arm and arm64 compilation will require you to clear at least the android folder in the Cache too.

**Comment by karliwalti** [comment]
So, I have installed API 21, 22, 24 and recently 29.   The ndk and sdk versions are the recommended versions in https://github.com/part-cw/lambdanative/wiki/Getting-Started

I am at commit 3f40d2239ac4a and have manually deleted the `.cache/lamdanative/android` folder and make scrub make clean

If I configure with API29 it falls back to 24.  (maybe due to no arm image available through the sdk but that would be another issue to open)
 
`If I configure with 21,22, 24 it directly leads to above error message. with missing corresponding target.

**Comment by karliwalti** [comment]
I did set up a second installation on a VM and the problem does not persist. I conclude that it is related to my specific installation.

**Comment by peterlew** [comment]
Just to echo what @mgorges wrote, we found that we had to clear the /Caches/lambdanative/android folder after e387cd2, and if that doesn't help, delete the entire /Caches/lambdanative folder.

**Comment by mgorges** [comment]
> `If I configure with 21,22, 24 it directly leads to above error message. with missing corresponding target.

Maybe @peterlew could look into this as it relates in us trying lower API levels, so the logic in [targets/android/_host_macosx#L40](https://github.com/part-cw/lambdanative/blob/master/targets/android/_host_macosx#L40) and [targets/android/_host_linux#L40](https://github.com/part-cw/lambdanative/blob/master/targets/android/_host_linux#L40) doesn't work for arm64. Otherwise, please do make a new issue for this.

**Comment by mgorges** [comment]
For `android-ndk-r15c` I see the required files for APIs 21,22,23,24,26 (no 25?), but this might depend on your NDK?

**Comment by peterlew** [comment]
I get that error message when I don't have the target API in my android-sdk folder. If you've installed 24, it should be fine - could you try this command `android list targets | grep "^id:"` and let us know what you get?

**Comment by karliwalti** [comment]
hi, I resolved this for my installation. it was indeed due to $ANDROIDSDK being empty, but not because there was no sdk installation, but a typo in the SETUP script where it is set. :( sigh...

So is android-ndk-r15c also an acceptable ndk?

**Comment by mgorges** [comment]
`android-ndk-r15c` works for me on macOS and Linux; we haven't tested newer ones but there might be more that are okay and the [Getting Started](https://github.com/part-cw/lambdanative/wiki/Getting-Started) wiki page that mentions `13b` is simply outdated? There is a point though were they took away some tools we need; don't know quite when though; `17c` removes 'armeabi' as a target though we might be able to to 16b?

**Comment by peterlew** [comment]
I am using `android-ndk-r21d` and it mostly works fine. Glad we found the problem @karliwalti :)

**Comment by karliwalti** [comment]
great I will try this newest version too. thanks @peterlew !

**Comment by karliwalti** [comment]
Ok, updated to ndk-21d, must say this build process starts to explode my harddisk. 60GB is not enough  to host an ubuntu and android build pipepline... nevertheless building DemoHelloWorld for Android 21, 24 and 29 fails with similar error messages:

```make
=== using profile karliwalti [/home/walterk/SoftwareRepo/lambdanative/PROFILE]..
=== configured to build DemoHelloWorld version 1.0 for android on linux in normal mode

ls: cannot access '/home/walterk/.cache/lambdanative/android/android-ndk-r21d-arm64-21-toolchain/bin/*-gcc': No such file or directory
==> checking for required tools..
==> checking for required libraries..
==> checking for lambdanative tools..
ls: cannot access '/home/walterk/.cache/lambdanative/android/android-ndk-r21d-arm-21-toolchain/bin/*-gcc': No such file or directory
==> creating libraries needed for DemoHelloWorld..
 => liblambdanative..
 => cleaning up..
 => exploding library liblambdanative..
==> creating artwork needed for DemoHelloWorld..
==> creating textures needed for DemoHelloWorld..
==> creating fonts needed for DemoHelloWorld..
==> creating strings needed for DemoHelloWorld..
==> updating embedded files for DemoHelloWorld..
==> updating web assets for DemoHelloWorld..
 => compiling scheme payload..
 => done compiling scheme payload
 => generating hook..
 => assembling payload..
 == /home/walterk/.cache/lambdanative/android/arm/lib/libpayload.a
ls: cannot access '/home/walterk/.cache/lambdanative/android/android-ndk-r21d-arm64-21-toolchain/bin/*-gcc': No such file or directory
==> creating libraries needed for DemoHelloWorld..
 => liblambdanative..
 => cleaning up..
 => exploding library liblambdanative..
==> creating artwork needed for DemoHelloWorld..
==> creating textures needed for DemoHelloWorld..
==> creating fonts needed for DemoHelloWorld..
==> creating strings needed for DemoHelloWorld..
==> updating embedded files for DemoHelloWorld..
==> updating web assets for DemoHelloWorld..
 => compiling scheme payload..
 => done compiling scheme payload
 => generating hook..
 => assembling payload..
 == /home/walterk/.cache/lambdanative/android/arm64/lib/libpayload.a
==> creating android loader needed for DemoHelloWorld..
 => creating android project..
 => using target 1 [API 21]
 => preparing icons..
 => processing sounds needed for DemoHelloWorld..
 => processing sounds from /home/walterk/SoftwareRepo/lambdanative/apps/DemoHelloWorld/sounds...
 => /home/walterk/SoftwareRepo/lambdanative/apps/DemoHelloWorld/sounds/ahooga.wav..
 => transferring java hook..
 => transferring java public classes..
 => preparing manifest..
 => creating payload module..
 => preparing JNI..
 => compiling payload module..
NDK_MODULE_PATH=/home/walterk/.lambdanative/tmp.qoolES /usr/local/android-ndk-r21d/ndk-build --silent APP_ABI=" armeabi-v7a arm64-v8a"
Android NDK: Found platform level in ./project.properties. Setting APP_PLATFORM to android-21.    
[armeabi-v7a] Compile thumb  : payloadshared <= bootstrap.c
jni/bootstrap.c:143:12: warning: returning 'const char *' from a function with result type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
    return str;
           ^~~
1 warning generated.
[armeabi-v7a] SharedLibrary  : libpayloadshared.so
/usr/local/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/walterk/.lambdanative/tmp.qoolES/libpayload/armeabi-v7a/libpayload.a(1959055257.o): incompatible target
/usr/local/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/walterk/.lambdanative/tmp.qoolES/libpayload/armeabi-v7a/libpayload.a(2907813665.o): incompatible target
jni/bootstrap.c:54: error: undefined reference to 'ffi_event'
jni/bootstrap.c:59: error: undefined reference to 'ffi_event'
jni/bootstrap.c:119: error: undefined reference to 'scm_mediascanner_callback'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [/usr/local/android-ndk-r21d/build/core/build-binary.mk:725: obj/local/armeabi-v7a/libpayloadshared.so] Error 1
ERROR: failed with exit code 2
BUILD FAILED - configure with verbose option for more information
make: *** [Makefile:2: all] Error 1
```

**Comment by mgorges** [comment]
Please don't put multiple issues into one - continue in #309
