### ISSUE TITLE
library usb-serial-for-android no longer supported?

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#305]
it seems that this library is no longer correctly build (Android 21)?

=> generating hook..
ls: cannot access '/home/wk/.cache/lambdanative/android/arm/build/usb-serial-for-android/*.o': No such file or directory
ls: cannot access '/home/wk/.cache/lambdanative/android/arm/build/usb-serial-for-android/*.o': No such file or directory
 => assembling payload..
in above folder (and also arm64 as compiled twice ) there is only a `çlasses.jar` file

**Comment by mgorges** [comment]
DemoSerial compiles for me - the `ls` error has always been there and can be ignored; it happens as we include a provided JAR file and not a compiled object here.

**Comment by mgorges** [comment]
If I look into the `classes.dex` at the end of compilation, I see 'com/homo/android/usbserial' so this should still work?

**Comment by mgorges** [comment]
6d56c7c silences the missing file message.

**Comment by karliwalti** [comment]
This builds now for me with Android 21 but immediately crashes on any phone that I have available. Interestingly, not even a log file is generated.

**Comment by karliwalti** [comment]
update: this was with ndk-13. same behavior with ndk-19. With ndk-21 I get an error from jarsigner where the certificate chain is not found.

**Comment by mgorges** [comment]
> With ndk-21 I get an error from jarsigner where the certificate chain is not found.

This would either need to go to #309 or a separate issue.

**Comment by mgorges** [comment]
As for the rest, I don't have a Android device, so can't test this.

**Comment by peterlew** [comment]
I can confirm this issue on my device. It may have to do with the following error from `adb logcat` when the app is launched: 
```
F DEBUG   :     #01 pc 000000000054e264  /data/app/org.ecemgroup.demoserial-heIIaEodd58QWhxTuU8aJA==/lib/arm64/libpayloadshared.so (___throw_error+24)
```

**Comment by karliwalti** [comment]
> e: this was with ndk-13. same behavior with ndk-19. With ndk-21 I get an error from jarsigner where the certificate chain is not found.

see #314

**Comment by karliwalti** [comment]
I confirm that with API24 DemoSerial compiles and runs on an Android device as of today 006e919

**Comment by karliwalti** [comment]
thank you @mgorges for the update of the library

**Comment by mgorges** [comment]
Unfortunately, I don't think this is resolved for newer APIs though so reopening until we sorted that too.

**Comment by peterlew** [comment]
This seems to work now with the new setup instructions and the recent ANDROID and CONFIGURE changes. It may freeze on first run after asking for permissions, but works on subsequent runs. Tested with API 21, 24, and 28.
