### ISSUE TITLE
android 32 bit and 64bit always needed?

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#306]
this relates to #292 where for play store compatibility both 32 and 64 versions are build for each make. Is there a way to have only one being build i.e. for debug or dev purposes?
the main reason is time, especially after a make scrub/clean

**Comment by mgorges** [comment]
You should never have to scrub the android toolchain unless you change incompatible things, that is ABI levels, architectures, etc. Switching back from an **_arm_** only build to a **_arm+arm64_** build, will require you to clear the **entire android cache** so I don't think this would save you any time? If you **don't** want to build **_arm64_** you could change [targets/android/host_linux_arm64](https://github.com/part-cw/lambdanative/blob/master/targets/android/host_linux_arm64), or the respective macOS version, to use the fallback mode; i.e. comment lines 1-5, and 8, or making the test in line 1 evaluate to **FALSE**.

**Comment by mgorges** [comment]
or you could rename `targets/android/host_linux_arm64` to something like `targets/android/XX_host_linux_arm64`, which is what I did for `targets/android/XX_host_macosx_x86_64` as I only needed that once

**Comment by mgorges** [comment]
The other alternative is to target an API < 21, which you can now do dynamically with the changes proposed in #317, such as `./configure DemoRedSquare android-19; make` will only get you a 32bit version of the app. 

The time after `make scrub` likely will not be significantly influenced by this, as you are rebuilding an entire cache and at some point will need to rebuild both the _arm_ and _arm64_ versions, unless you never want them? Make clean should also clear all architectures, so again I don't think there would be any difference in times?
