### ISSUE TITLE
android signing doc 

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#314]
Newer android ndk's (likely after 19) a signing key is mandatory. 

The description how to generate key in [getting started](https://github.com/part-cw/lambdanative/wiki/Getting-Started)  does not work: 
```
$ . PROFILE
$ keytool -genkey -v -keystore android.keystore -alias "$SYS_ORGTLD.$SYS_ORGSLD" -dname "cn=Your Name, ou=YourOrgUnit, o=YourOrg, c=US"  -keypass "$SYS_ANDROIDPW" -storepass "$SYS_ANDROIDPW" -keyalg RSA -keysize 4096 -validity 1000000
```

-alias should be `"$SYS_ORGTLD.$SYS_ORGSLD_REVERSE"` (see description in PROFILE.template) but this is no longer available.

**Comment by mgorges** [comment]
Sorry what is no longer available - the alias or the reversed domain name, as from plotting `$SYS_ORGDOMAIN_REVERSE_DOT` that seems to be in the right order? We try to help setup the key automatically in [targets/android/build-binary#L356](https://github.com/part-cw/lambdanative/blob/master/targets/android/build-binary#L356), which is different from what the Wiki says, but I can't quite figure out why the Wiki was changed?

**Comment by karliwalti** [comment]
> but I can't quite figure out why the Wiki was changed?

I do not think the wiki was changed yet.

 targets/android/build-binary#L356 is not executed on my system. To reproduce: 

1. delete android.keystore  in lambdanative root folder
2. build for android
3. no new keystore in lambdanative root folder
4. build fails with signing

if keystore is build manually as in getting strated (with correct reverse order), build succeeds

There is some issue with detecting the presence of keystore?



> Sorry what is no longer available

`$SYS_ORGDOMAIN_REVERSE_DOT` after running `. PROFILE`

**Comment by mgorges** [comment]
Can you provide the errors you get during key generation or the signing? I just tried this with API=21 and `android-ndk-r21d` and had no issues with the automates key generation (which ends up in `.lambdanative/android.keystore` not the lambdaNative root?).
` => generating keystore [/Users/mg/.lambdanative/android.keystore]..`
`Generating 2,048 bit RSA key pair and self-signed certificate (SHA256withRSA) with a validity of 10,000 days
	for: CN=org.ecemgroup.dev`
`[Storing /Users/mg/.lambdanative/android.keystore]`
 `=> signing application with keystore /Users/mg/.lambdanative/android.keystore`
`jar signed.`

**Comment by karliwalti** [comment]
Ok, that clarifies the issue. 

The info on the setup page should be completely removed as it is done automatically now and not to the folder where SETUP is.

I think it would be nicer if the script would check whether the specific entry exist (and not the keyfile itself) and if not add it.  The command could be `keytool -list -keystore android.keystore -alias $SYS_ORGDOMAIN_REVERSE_DOT` and detecting whether it fails

**Comment by mgorges** [comment]
Not sure about the Wiki, the code that does this automatically has been present since 2013 which predates the wiki? Wouldn't your suggested test to be an additional thing to check, as if the file isn't there we would have to make it irrespectively?

**Comment by mgorges** [comment]
My keytool asks for a password when listing and won't accept the `-keypass`, so this is not as straight forward?

**Comment by karliwalti** [comment]
Aug 18 ae1c887

maybe a command that clears the android folder and this file, to be executed when changing ndks or APIs?

**Comment by mgorges** [comment]
a216abe implements the keytool list check, will remove it from the wiki.

**Comment by karliwalti** [comment]
nice. Thank you.

**Comment by mgorges** [comment]
> maybe a command that clears the android folder and this file, to be executed when changing ndks or APIs?

Yes, but this is not trivial either, as we don't keep track of what the last one was that you used. I have a way to force a world-wide rebuild for everyone (by changing the VERSION), but we'd have to think about this one - maybe create a new ticket for it?
