### ISSUE TITLE
Revert Feature Removal: `SYS_PLATFORM_VARIANT`

### ISSUE THREAD

**Issue by 0-8-15** [part-cw/lambdanative#316]
The commits https://github.com/part-cw/lambdanative/commit/fa18945 and https://github.com/part-cw/lambdanative/commit/6b04f9c introduced support for `SYS_PLATFORM_VARIANT`.

I am absolutely dependent on this feature by now.  It did a good job for the past 11 month.  Now I just backed up my cached files until I have a solution for the damage it would do: loose about **two hours of wall clock time** for a full basic test cycle from now on with about 8 minutes personal/manual attention/activity for the **same cycle taking about 10-12** minutes in total. (i.e., 2-4 minutes for compile and deploy on four platforms with two variants).

I'd suggest the feature a better solution to https://github.com/part-cw/lambdanative/issues/315 than repeatedly automatically cleaning the cache.

Which is why I introduced it in the first place.

**Comment by mgorges** [comment]
_Note_: If you don't want to rebuild your android cache, you can manually rename the arm and arm64 folders in [your cache location]/android to arm-api21 and arm64-api21 (or whichever current API you use) respectively.

**Comment by mgorges** [comment]
if you have previous copies of your cache, you can put them into their respective locations, which are all in the form of `$SYS_PREFIXROOT/$SYS_PLATFORM/arm${SYS_PLATFORM_VARIANT}`
