### ISSUE TITLE
How to use scrolling in glgui - documentation request

### ISSUE THREAD

**Issue by 0-8-15** [part-cw/lambdanative#326]
I can't figure out how to make the scrollbar work in glgui widgets.

So far I tried `glgui-list` and `glgui-chat`.  Both did not scroll.

Looking closer I could not find a hint in the source how it should/could work at all.

What am I missing?

**Comment by mgorges** [comment]
You do have more items that fit the screen, right? In case of doubt, assume that most widgets were developed for a mobile device – as such you need to click and drag the list items themselves not the tiny bar on the side.

**Comment by 0-8-15** [comment]
Am Fri, 25 Sep 2020 12:51:32 -0700
schrieb Matthias Görges <notifications@github.com>:

> You do have more items that fit the screen, right?

Sure.

> In case of doubt, assume that most widgets were developed for a mobile device – as such
> you need to click and drag the list items themselves not the tiny bar
> on the side.

a) I tried on Android (at least with the glgui-chat, not that sure
about the glgui-list) and it did not respond to drag/motion nor the
tiny bar.

b) I'd need it for other targets anyway.

**Comment by mgorges** [comment]
I made https://github.com/mgorges/lambdanative-testing/tree/master/apps/DemoList which has a minimal list implementation. This works, as expected, on all platforms I have access to right now: macOS, iOS, Linux. If you click any of the list elements and while the button is clicked drag the list item up and down the list scrolls. If you click an item, the number is shown below.

**Comment by 0-8-15** [comment]
Am Fri, 25 Sep 2020 13:15:36 -0700
schrieb Matthias Görges <notifications@github.com>:

> I made
> https://github.com/mgorges/lambdanative-testing/tree/master/apps/DemoList
> which has a minimal list implementation. This works, as expected

Thanks a lot!  Based on this I figured out that it was actually my bad
somewhere filtering out the EVENT_MOTION.  :-/
