### ISSUE TITLE
Module download fails on larger files

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#335]
I noticed that larger files (+8mb) are incorrectly downloaded (without giving error message). This is independent of the latest changes and also platforms. 
I've not been able to identify the issue, as the files are almost identical in size and content, but not exactly. It is sufficient to prevent videos to be played. A checksum test would be useful to integrate here too. 

I keep debugging and will update here...

**Comment by mgorges** [comment]
The performance of this is bad ... `%wget https://ecem.ece.ubc.ca/~mgorges/target.txt` takes 6.1 sec, while the same in a `DemoConsole` with this content
```
(define host "ecem.ece.ubc.ca")
(define path "/~mgorges/target.txt")
(define filename "~/Downloads/pattern.txt")
(download-getfile host path filename)
``` 
takes forever - it hangs after 9001 packages when no more data are received. Isn't [modules/download/download.scm#L158](https://github.com/part-cw/lambdanative/blob/master/modules/download/download.scm#L158) an infinite loop?

**Comment by mgorges** [comment]
The performance of this is not great ... `%wget https://ecem.ece.ubc.ca/~mgorges/target.txt` takes 6.1 sec, while the same in a `DemoConsole` with this content
```
(define host "ecem.ece.ubc.ca")
(define path "/~mgorges/target.txt")
(define filename "pattern.txt")
(download-getfile host path filename)
``` 
takes 7.3sec. Also note to self - the path has to be relative!

**Comment by mgorges** [comment]
Next, why is the file I get with the download module longer?
```
-rw-r--r--  1 mg  staff  9216745 29 Sep 02:19 pattern.txt
-rw-r--r--  1 mg  staff  9216000 29 Sep 01:59 target.txt
```

**Comment by mgorges** [comment]
The extra data are at the end of the first packet (len 279), but `SSL_read` in [modules/httpsclient/httpsclient.scm#L173](https://github.com/part-cw/lambdanative/blob/master/modules/httpsclient/httpsclient.scm#L173) is also that length. So it might be a change in OpenSSL 1.1? - I went back to 1.0.2n but the same length is returned.
