### ISSUE TITLE
broken linux build

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#344]
Latest commits up to 15446ca64  break my building on linux:

```
*** WARNING -- "frame-period-custom" is not defined,
***            referenced in: ("/home/walterk/.cache/lambdanative/linux/build/3948996557.c")
*** WARNING -- "when" is not defined,
***            referenced in: ("/home/walterk/.cache/lambdanative/linux/build/3948996557.c")
 => done compiling scheme payload
```
this segfaults after initialization sequence.

**Comment by mgorges** [comment]
The `frame-period-custom` is puzzling - @0-8-15 will need to explain that. The missing `when` might be as I didn't merge #336 yet?

**Comment by mgorges** [comment]
Commit 976561b should fix the error in f0b69b1 with respect to the order of the symbols for detecting the scheme version. I don't think this will fix the first problem though?

**Comment by karliwalti** [comment]
yes, fix first, but not other that is more critical

**Comment by mgorges** [comment]
I am pretty sure the issue is in [modules/ln_glgui/glgui.scm#L319](https://github.com/part-cw/lambdanative/blob/master/modules/ln_glgui/glgui.scm#L319) but not yet sure why, as this works with newer gambit.
