### ISSUE TITLE
Undefined g warning and segfault in eventloop with #342

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#353]
I'm getting a 

```
*** WARNING -- "g" is not defined,
***            referenced in: ("/home/walterk/.cache/lambdanative/linux/build/3948996557.c")

```

when building DemoHelloWorld for linux

when building DemoUIForm I get this warning too, and a segfault

**Comment by mgorges** [comment]
Only when building in `debug` mode, or all the time?

**Comment by mgorges** [comment]
Silenced missing `g` in ac71589 - this is only visible due to #342 removing **(block)** in debug mode.

**Comment by mgorges** [comment]
The segfault is related to **(system-platform)**
```
Program received signal SIGSEGV, Segmentation fault.
0x0000555555afb7d3 in ___H__20_2767889363 (___ps=0x555557182160 <___gstate0>)
    at /home/mg/documents/Programming/lambdanative-cache/linux-debug/build/2767889363.c:10808
10808      ___JUMPGLONOTSAFE(___SET_NARGS(0),147,___G_system_2d_platform)
```

**Comment by mgorges** [comment]
7876f8e **forces** `config` to be first in the module source list, as otherwise it causes segfaults if `eventloop` goes before it. This error occurs only when configuring in **debug** mode.
