### ISSUE TITLE
CAMERA / ANDROID:  external services no longer available

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#354]
```
camera-start
camera-start-video 
videoplayer 
```

are no longer working on API 24. 

consequently the buttons in  `DemoCamera` for Android are  not doing anything.

**Comment by karliwalti** [comment]
Also not working when building for API 22 and 29.
Is this linked to #256 ?

**Comment by mgorges** [comment]
Consider changing [loaders/android/AndroidManifest.xml.in#L8](https://github.com/part-cw/lambdanative/blob/master/loaders/android/AndroidManifest.xml.in#L8) to 21 or remove it's definition completely (which makes it equal to _@SYS_ANDROIDAPI@_; it was introduced in 66d130d as a requirement to go to the Play Store. All of these things are something that Google broke, we can only try to recover out technical debt in this respect or give up.

**Comment by ddunsmuir** [comment]
@karliwalti what about older Android? Did you try the suggestion above to edit the AndroidManifest.xml.in? If everything runs fine on 21 or older, then this is likely something Android specific. Something Google changed, not specific to LambdaNative.

**Comment by karliwalti** [comment]
Yes, working with API21 resolves the camera issue (but not  #372).

**Comment by karliwalti** [comment]
Update: on Android 11 systems, the 'trick' to set API21 no longer works with expected behaviors. Returning from the camera restarts the ln app instead of adding to the process. No crash, but also no picture... 
Systems with Android 10 work and are definitely the limit

**Comment by mgorges** [comment]
4582b2e allows changes to the launchMode - @peterlew overrides it in one of our apps, maybe this is related.

**Comment by mgorges** [comment]
Should be resolved by merging #380 ?

**Comment by karliwalti** [comment]
As far as I could test, this is indeed resolved. Thank you @peterlew !
