### ISSUE TITLE
ANDROID random crashes with "Wrong number of arguments passed to procedure" and too little debug info

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#372]
Building for Android 24 using the latest code I get random crashes at startup (initialization works).  There is no clear pattern that would determine why other than the type of error: "Wrong number of arguments passed to procedure", the function where it happens can be quite differnt such as `(##equal), (list-ref), (c-mediascanner-callback 0), (##extract-procedure-and-arguments 'string-or-settings) ` etc. sometimes it fails to write the error to log file. Sometimes the app runs and then no crash will occur again.

The debug entries for errors used to include trace information to code lines, this is no longer the case?

`[ERROR] 2020-10-13 14:50:15.7877082: primordial: (##extract-procedure-and-arguments 'string-or-settings): Wrong number of arguments passed to procedure`

One eception is this error, but said line does not even exist

```
[ERROR] 2020-10-13 14:54:58.5056171: primordial: (##raise-wrong-number-of-arguments-exception-nary): Wrong number of arguments passed to procedure
[ERROR] 2020-10-13 14:54:58.63484: trace: /home/walterk/lambdanative/modules/ln_glgui/primitives.scm line=297 col=13
```
@0-8-15 is this somehow linked to your recent work?

**Comment by karliwalti** [comment]
I think it is important to note that this is inconsistent across devices.
Happens on a tablet running Android 9, seems to be fine on a phone with Android 10

**Comment by mgorges** [comment]
I didn't merge anything with respect to changing the log trace, pull request #366 would do that though. There is a change to eventloop, with respect to interrupts: [modules/eventloop/eventloop.scm#L41](https://github.com/part-cw/lambdanative/blob/master/modules/eventloop/eventloop.scm#L41), and then lots of changes to debug compilation options [languages/scm.sh#L58](https://github.com/part-cw/lambdanative/blob/master/languages/scm.sh#L58), which change the way we now die on errors which we didn't in the past. Is the behaviour different if you don't use `debug` mode?

**Comment by mgorges** [comment]
> One exception is this error, but said line does not even exist

[modules/ln_glgui/primitives.scm#L297](https://github.com/part-cw/lambdanative/blob/master/modules/ln_glgui/primitives.scm#L297) does exist, it is `(apply glCoreTextureDraw (append (list (fl+ x0 gox) (fl+ (flo y) goy (fl- gh))) i (list 0.))))`

**Comment by karliwalti** [comment]
Same behavior with and without debug. Only enabled debug when we experienced so many unexplained crashes.


> modules/ln_glgui/primitives.scm#L297 does exist, it is (apply glCoreTextureDraw (append (list (fl+ x0 gox) (fl+ (flo y) goy (fl- gh))) i (list 0.))))

my bad.   (flo) was also one of the failed functions showing up

**Comment by mgorges** [comment]
To help us narrow this down - any app or a lnhealth one?

**Comment by karliwalti** [comment]
I will check with those and report

**Comment by karliwalti** [comment]
I could not find any of the Demo apps that experience these behaviors. 
My app uses these Modules: `config eventloop ln_glgui ln_core ln_glcore ln_store accelerometer settings uuid csv localization uiform redcap sanestring cdb `

While scanning through the demo apps I noticed that DemoSensors and DemoCamera (#354 ) are not running on Android.

**Comment by mgorges** [comment]
Will investigate tomorrow - one thing we know is that module order in `debug` mode is sensitive now, so if some are not the right way strange things happen. I think both of the sensor ones are related to permissions and handling NULL correctly when the user doesn't grant it

**Comment by karliwalti** [comment]
I somehow pinned it down. Commenting this line fixed all evil things: 

`(if (string=? (system-platform) "android") (android-run-mediascanner) )`

I use this sometimes to make sure the mediascanner runs at least once.

maybe it links to #295 ?

> one thing we know is that module order in debug mode is sensitive now

As behaviors of debug are expected to be different, would it make sense to add the term "debug" to the name of the binary to be able to distinguish between the two builds?

**Comment by mgorges** [comment]
I separated the two caches completely internally, which allows me to switch between both without scrubbing the cache at all. It adds duplication in terms of space (android is an extra 1GB) but shouldn't have other side effects. However, at the moment I don't need more complains, so not pushing the change yet:
```
diff --git a/make.sh b/make.sh
index 9adb96e..a3e7840 100755
--- a/make.sh
+++ b/make.sh
@@ -1002,6 +1002,9 @@ make_setup_target()
   ac_subst LDFLAG_ADDITIONS "$ldflag_additions"
   #--------
   . $setup_target
+  if [ "X$SYS_MODE" = "Xdebug" ]; then
+    SYS_PREFIX="${SYS_PREFIX}-debug"
+  fi
   if [ ! "X$SYS_CPU" = "X" ]; then
     SYS_PREFIX="$SYS_PREFIX/$SYS_CPU"
   fi
```

**Comment by mgorges** [comment]
> While scanning through the demo apps I noticed that DemoSensors and DemoCamera (#354 ) are not running on Android.

It's a permission request at start problem, but not only that, @peterlew is looking into it.

**Comment by mgorges** [comment]
> maybe it links to #295 ?

Don't think that this is related to `android-run-mediascanner` but rather an issue in linking, but not sure yet.
