### ISSUE TITLE
Segmentation fault at ___JUMPGLONOTSAFE(___SET_NARGS(3),503,___G_when)

### ISSUE THREAD

**Issue by goober99** [part-cw/lambdanative#400]
When trying to compile and run Calculator (or any of the GUI demo apps), it appears to compile fine, but when I try to run it I get a segmentation fault.

```bash
./configure Calculator
make
make install
make[1]: Entering directory '/opt/lambdanative'
=== using profile your profile name here [/opt/lambdanative/PROFILE]..
=== configured to build Calculator version 1.0 for linux on linux in normal mode

==> attempting to install linux application Calculator to local desktop..
==> attempting to copy .desktop file to /home/matthew/.local/share/applications/
==> Starting application..
Segmentation fault
make[1]: Leaving directory '/opt/lambdanative'
```

I recompiled in debug mode

```bash
./configure Calculator debug
make scrub
make
make install
```

and executed the resulting executable with GDB:

```bash
gdb Calculator
(gdb) run
Program received signal SIGSEGV, Segmentation fault.
0x0000555555d4567b in ___H__20_4204377870 (___ps=0x555556bd3920 <___gstate0>)
    at /home/matthew/.cache/lambdanative/linux/build/4204377870.c:571383
571383	   ___JUMPGLONOTSAFE(___SET_NARGS(3),503,___G_when)
```

I'm on Debian Sid using LambdaNative 1.1.

**Comment by mgorges** [comment]
Are you running the actual v1.1 (15446ca) as `when` was only backported in 98bf53e about 10 commits later?

**Comment by goober99** [comment]
I downloaded the zip file from [this page](https://github.com/part-cw/lambdanative/releases/tag/v1.1) and unzipped it to /opt.

**Comment by mgorges** [comment]
Yeah, that is not a working version - I had to be identified as a major big change to some critical component (all application timing behaviour is changed since) which needed to be identified as such. I guess it is time to make a new release...

**Comment by goober99** [comment]
Thanks. For now, I downloaded the zip for 1.0.13, and the Calculator demo will now compile and run. I'll try out the new release once it's out.

**Comment by mgorges** [comment]
I tagged v1.1.1 but it might need more testing.
