### ISSUE TITLE
** ERROR: could not find library libpng

### ISSUE THREAD

**Issue by gpatrickb** [part-cw/lambdanative#423]
Using openSUSE Leap 15.2

Used a clone from github.  
./configure Calculator <== works
make <== fails

 => extracting /home/999/.cache/lambdanative/packages/freetype-2.5.5.tar.gz..
 => patching source...
 => configuring source in /home/999/.lambdanative/tmp_install/freetype-2.5.5 ...
 => compiling source..
 => compiling source..
 => cleaning up..
 => exploding library liblambdanative..
** ERROR: could not find library libpng
make: *** [Makefile:2: all] Error 1

**Comment by gpatrickb** [comment]
Additional details:
localhost:/usr/lib64 # rpm -qa |grep libpng
libpng16-16-1.6.34-lp152.4.6.x86_64

That provides:
lrwxrwxrwx 1 root root     19 May 16  2020 libpng16.so.16 -> libpng16.so.16.34.0
-rwxr-xr-x 1 root root 272368 May 16  2020 libpng16.so.16.34.0

I installed libpng-1.6.34 to /usr/local/lib64 and symlinked to /usr/lib64:
 lrwxrwxrwx 2 root root     28 Sep 11 10:38 libpng16.so -> /usr/local/lib64/libpng16.so
lrwxrwxrwx 2 root root     28 Sep 11 10:38 libpng.so -> /usr/local/lib64/libpng16.so

But it always returns that it can't find libpng.

**Comment by gpatrickb** [comment]
localhost:/usr/lib64 # ls -lrt libpng*
lrwxrwxrwx 1 root root     19 May 16  2020 libpng16.so.16 -> libpng16.so.16.34.0
-rwxr-xr-x 1 root root 272368 May 16  2020 libpng16.so.16.34.0
lrwxrwxrwx 2 root root     28 Sep 11 10:38 libpng16.so -> /usr/local/lib64/libpng16.so
lrwxrwxrwx 2 root root     28 Sep 11 10:38 libpng.so -> /usr/local/lib64/libpng16.so

Even tried moving libpng16.so.16.34.0 to libpng16.so.16.34.0.bak so it wouldn't find the system installed libpng, but always the same error.

**Comment by mgorges** [comment]
Could you reconfigure with `./configure Calculator verbose` and redo `make`, please? It might be a path issue or some mismatch between a 32bit and a 64bit library?

**Comment by gpatrickb** [comment]
[make.txt](https://github.com/part-cw/lambdanative/files/7165444/make.txt)
Attached is make after configure verbose.

Thank you.

**Comment by mgorges** [comment]
Thanks for providing the additional details - it seems odd, as the log file seems to indicate that both `libpng` and `libfreetype` install correctly, even though I am a bit confused of why it is getting built twice (are you building it once for a 32 bit and also for a 64 bit system)? The other odd thing is that it installs things into a `lib64` and not a `lib` folder
```
Libraries have been installed in:
   /home/999/.cache/lambdanative/linux/lib64
```
It sounds a bit like #113 from many years ago that we never solved, but seemed related to 'multilib' support, and we did explore `--libdir` flags in `configure` steps but none of this were committed to the repository?

**Comment by mgorges** [comment]
Thanks - but ideally we'd want to prevent this by changing an option in the configuration - I just don't know how to test this other than downloading OpenSUSE and testing it in a VM?

**Comment by gpatrickb** [comment]
If you want me to test changes I'd be happy to do so.
