### ISSUE TITLE
can't download freetype-2.5.5.tar.gz

### ISSUE THREAD

**Issue by lachlanA** [part-cw/lambdanative#426]
can't download freetype-2.5.5.tar.gz

Debian 10,  amd64.
New install from github

Note:   looking at the URL for freetype I see there is no version 2.5.5.
Perhaps this needs to be updated,   ?

Lachlan

**Comment by mgorges** [comment]
Hi Peter,
I think this refers to [libraries/libfreetype/make.sh#L1](https://github.com/part-cw/lambdanative/blob/74ec19dddf2f2ff787ee70ad677bc13b9dfafc29/libraries/libfreetype/make.sh#L1) pointing to a file that no longer exists? A quick workaround could be to set it to `PKGURL=https://download.savannah.gnu.org/releases/freetype/freetype-old/freetype-2.5.5.tar.gz`, but it might be better to upgrade to 2.7, 2.8, or 2.9?

Cheers Matthias

**Comment by lachlanA** [comment]
Thanks, Matthias   that fixed the problem :)

Lachlan

**Comment by mgorges** [comment]
Should be closed with update to newer version in f45ecc2. If not, please reopen.
