### ISSUE TITLE
gmake compile Error on FreeBSD13

### ISSUE THREAD

**Issue by devosalain** [part-cw/lambdanative#427]
```
./configure Calculator freebsd
gmake
Error log:
...
...
=> done compiling scheme payload
 => generating hook..
 => assembling payload..
 == /home/x/.cache/lambdanative/freebsd/lib/libpayload.a
==> creating freebsd loader needed for pngtool..
 => processing sounds needed for pngtool..
 => compiling application..
gcc  -DFREEBSD -I/usr/local/include -I/usr/local/include/X11  -I/home/x/.cache/lambdanative/freebsd/include      -DUSECONSOLE -o /home/x/.cache/lambdanative/freebsd/pngtool/pngtool     -L/home/x/.cache/lambdanative/freebsd/lib  -liconv -lpayload  -lutil -lpthread -lm
/usr/local/bin/ld: /home/x/.cache/lambdanative/freebsd/lib/libpayload.a(system.o):(.bss+0x0): multiple definition of `cmd_argv'; /home/x/.cache/lambdanative/freebsd/lib/libpayload.a(2978470258.o):(.bss+0x0): first defined here
/usr/local/bin/ld: /home/x/.cache/lambdanative/freebsd/lib/libpayload.a(system.o):(.bss+0x8): multiple definition of `cmd_argc'; /home/x/.cache/lambdanative/freebsd/lib/libpayload.a(2978470258.o):(.bss+0x8): first defined here
collect2: error: ld returned 1 exit status
ERROR: failed with exit code 1
BUILD FAILED - configure with verbose option for more information
gmake: *** [Makefile:2: all] Error 1
``` 
OS: FreeBSD 13.0-RELEASE-p4 amd64

cc -v:
FreeBSD clang version 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c3fe)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin

gcc -v:
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc11/gcc/x86_64-portbld-freebsd13.0/11.2.0/lto-wrapper
Target: x86_64-portbld-freebsd13.0
Configured with: /wrkdirs/usr/ports/lang/gcc11/work/gcc-11.2.0/configure --enable-multilib --with-build-config=bootstrap-debug --disable-nls --enable-gnu-indirect-function --enable-host-shared --enable-plugin --libdir=/usr/local/lib/gcc11 --libexecdir=/usr/local/libexec/gcc11 --program-suffix=11 --with-as=/usr/local/bin/as --with-gmp=/usr/local --with-gxx-include-dir=/usr/local/lib/gcc11/include/c++/ --with-ld=/usr/local/bin/ld --with-pkgversion='FreeBSD Ports Collection' --with-system-zlib --without-zstd --with-isl=/usr/local --enable-languages=c,c++,objc,fortran,jit --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/man --infodir=/usr/local/share/info/gcc11 --build=x86_64-portbld-freebsd13.0
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.0 (FreeBSD Ports Collection)

**Comment by mgorges** [comment]
I don't use BSD so this might be a bit harder to troubleshoot, but akin to https://github.com/part-cw/lambdanative/issues/410#issuecomment-770985855 could you try adding '-fcommon' to [host_openbsd#L38](https://github.com/part-cw/lambdanative/blob/master/targets/openbsd/host_openbsd#L38) and L39?

**Comment by devosalain** [comment]
The linker is using gcc , which on my PC is gcc11.
Can i force somewhere to use gcc9, i would like to try that.

**Comment by mgorges** [comment]
I don't think this has to do with the window manager - have a look at the event capture and if you do find out, please let us know, thanks!
