### ISSUE TITLE
undefined reference to `BrotliDecoderDecompress'

### ISSUE THREAD

**Issue by cidne** [part-cw/lambdanative#428]
Followed instructions on Getting Started Wiki--installed all dependencies.

`./configure Calculator verbose`

(success)

`make`

Fails

Output of make attached:
[make.txt](https://github.com/part-cw/lambdanative/files/7647775/make.txt)

**Comment by mgorges** [comment]
The error is one when performing static linking during freetype building. A quick search shows only a single occurrence of this elsewhere: https://github.com/microsoft/vcpkg/issues/21778.
```
/usr/bin/ld: /home/cidne/.cache/lambdanative/linux/lib/libpayload.a(sfnt.o): in function `woff2_decompress':
/home/cidne/.lambdanative/tmp_install/freetype-2.11.0/src/sfnt/sfwoff2.c:327: undefined reference to `BrotliDecoderDecompress'
collect2: error: ld returned 1 exit status
```
Could you try rolling [libraries/libfreetype/make.sh](https://github.com/part-cw/lambdanative/blob/master/libraries/libfreetype/make.sh) back to an earlier version (we previously had 2.5.5 - see f45ecc2), or the latest one, which is 2.11.1 by changing the top two lines of the file to:
```
PKGURL=https://download.savannah.gnu.org/releases/freetype/freetype-2.11.1.tar.gz
PKGHASH=b92fc0b9f04d1f60a78e0e78723200d2b6d41dd8
```

**Comment by cidne** [comment]
Started working backwards--looks like the newest working version is freetype-2.10.1

PKGURL=https://download.savannah.gnu.org/releases/freetype/freetype-2.10.1.tar.gz
PKGHASH=3296b64ad1e7540289f22e4b6383e26e928b0a20
