### ISSUE TITLE
Bug in generalized-arrays module

### ISSUE THREAD

**Issue by gambiteer** [part-cw/lambdanative#432]
I fixed a one-line bug in SRFI 179:

https://github.com/scheme-requests-for-implementation/srfi-179/pull/23/commits/eae436a58b5bf5a521f9194540704f064da734fe

This line

https://github.com/part-cw/lambdanative/blob/7e69cbcdcbac134465bd4e2880a636c0a5a05494/modules/generalized-arrays/generalized-arrays.scm#L2072

should be changed as in the commit listed for SRFI 179.

I apologize for not catching it in testing earlier, it appears in rather esoteric circumstances.

I'd rather not fork lambdanative, build the special versions of Gambit that it uses, to make and test a pull request; perhaps someone can install this fix for me.

Brad Lucier

**Comment by mgorges** [comment]
Thanks @gambiteer, fixed as requested.
