### ISSUE TITLE
uSquish no longer in Google Play or Apple App store

### ISSUE THREAD

**Issue by bkmgit** [part-cw/lambdanative#448]
Can update [README.md](https://github.com/part-cw/lambdanative/blob/master/README.md), unless they will be returned.

**Comment by mgorges** [comment]
That is correct; the Google Play Store entry was removed as we can't complete their Business verification process as we are a research team, not a company, and thus don't have a DUNS number (now required). For Apple, we'd simply need to release a new version, as the current hasn't has been updated recently enough and also change the descriptions as the reviewer felt it was a game for children, which has new requirements. 
There are still apps built with LambdaNative on both stores, though, including https://github.com/part-cw/LNhealth/tree/master/apps/RRate, which is https://play.google.com/store/apps/details?id=ca.bccw.rrate and https://apps.apple.com/bg/app/rrate/id581390517.

**Comment by mgorges** [comment]
I will merge the commit as I personally don't have the capacity to fix these things at the moment.
