### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by bkmgit** [part-cw/lambdanative#450]
The current release dos not build on Fedora 40, but the head of the repository does.  Would it be possible to make a new release?

**Comment by mgorges** [comment]
Sure, we can release a new version, but the question is whether we switch the default version of Gambit to that too. The change is easy [modules/config/LIBRARIES](https://github.com/part-cw/lambdanative/blob/master/modules/config/LIBRARIES) will point to [libraries/libgambit](https://github.com/part-cw/lambdanative/blob/master/libraries/libgambit/make.sh) and no longer [libraries/libgambc](https://github.com/part-cw/lambdanative/blob/master/libraries/libgambc/make.sh). Yet, the problem with that is that it requires rebuilding of the entire cache, which I can force by incrementing [VERSION](https://github.com/part-cw/lambdanative/blob/master/VERSION), which [make.sh#L1672](https://github.com/part-cw/lambdanative/blob/master/make.sh#L1672) detects, but might make people unhappy as recompiling everything takes a while and might break things too?

**Comment by mgorges** [comment]
Added a new release in https://github.com/part-cw/lambdanative/commit/a5275cfd13c2160b1746cfeee7df59b36c594ffd, which is [v1.1.2](https://github.com/part-cw/lambdanative/releases/tag/v1.1.2) which only tags the current head but doesn't touch the Gambit version.

**Comment by bkmgit** [comment]
Thanks.  On Fedora used packaged Gambit which is 4.9.3 https://src.fedoraproject.org/rpms/gambit-c

**Comment by mgorges** [comment]
Our newer versions 4.9.2 as there was some issue with 4.9.3, but the current official default is 4.7.9 though nobody on our team has been using that for years.

**Comment by bkmgit** [comment]
Thanks for the release. Closing as main issue has been resolved.
