### ISSUE TITLE
Using meroon with Lambdanative

### ISSUE THREAD

**Issue by VincentToups** [part-cw/lambdanative#48]
Lambdanative is great, however, I'd like to use the meroon object system in my lambdanative project, however, if I follow meroon's instructions for use with gambit, I get an error: 

    *** ERROR IN feature-present? -- Unbound variable: *meroon-features*

I gather this has to do with evaluation time semantics.

I get this error if I try to include the meroon files directly in my project's `main.scm` or if I create a module and an appropriate meroon.scm like so:

    (include "meroon.gsc")
    (include "meroon.gambc24")

This is the instructions provided in the most recent version of meroon.  

I would be happy with any other object system as long as performance is adequate and the system doesn't generate a lot of garbage.  Any suggestions?

**Comment by shargo** [comment]
Did you find a more recent version of meroon than that one: http://www.math.purdue.edu/~lucier/software/Meroon/MeroonV3-2012Jan20.tar.bz2 ?

Running 'make_meroon' from that version will produce a loadable _meroon.o1 provided 'gsc' is pointing to the proper version of gambit compiler.

I suspect that the fastest way to integrate meroon into lambdanative would be by handling it the same way as syntax-case is being handled.

I do not know how tinyclos compares to meroon in terms of performance, but I think it can become a normal lambdanative module with little effort.

**Comment by mgorges** [comment]
I am not sure about how to include Meroon, as it is licensed with the Lisp Lesser General Public License (LLGPL), while all of our other code is under the 3-clause BSD license. I believe @clpetersen is looking at alternative OOML systems at the moment.

**Comment by VincentToups** [comment]
I hacked up a version of tinyclos I grabbed from someplace.  If performance
gets in the way, I'll probably try to optimize it some.

**Comment by VincentToups** [comment]
I'm going to close this issue as I have an alternative in place.

**Comment by mgorges** [comment]
@VincentToups would you mind sharing what you used instead? Thanks.

**Comment by VincentToups** [comment]
Sure, I am using this

https://github.com/wime12/tiny-clos

Except that I removed the code for the black hole module system.  Seems to be working ok!
