### ISSUE TITLE
Japanese Font "kochi-mincho" cannot be converted to scheme font atlas

### ISSUE THREAD

**Issue by duerrp** [part-cw/lambdanative#50]
I am trying to generate a japanese font (based on kochi-mincho.ttf) using the following character ranges:

```
U+3000-303F
U+3040-309F
U+30A0-30FF
U+FF00-FFEF
U+4E00-9FAF
U+3400-4DBF
```

Make tries to run the following command (taking a few seconds), but it results in an empty font file...

```
/home/peter/.cache/lambdanative/linux/bin/ttftool fnt2scm /home/peter/Software/lambdanative/fonts/kochi-mincho.ttf /home/peter/Software/lambdanative/fonts/kochi.set 18 kochi
```
Any idea how to fix this?

**Comment by mgorges** [comment]
The U+4E00-9FAF range (which are 20912 characters) seems to be the problem: If you remove that one from the set it builds an scm file!

The failure occurs in modules/ttf/ttf.scm, where a 1024x1024 texture size is exceeded. A 2048x2048 is not sufficient either, and 4096x4096 is no longer supported by some platforms, including iOS. Commit 60be918 adds support for these large textures, but includes a warning when building them.

**Comment by duerrp** [comment]
I see, thanks for looking into it so fast! iOS support is not really necessary for me at this point. I cannot see the commit yet - I assume you are pushing it at some point?

Thx again!

**Comment by duerrp** [comment]
Sorry for being impatient... got it now. Thx.

**Comment by duerrp** [comment]
Compiling this takes way too long though. I guess I need to figure out a way to restrict the range of unicode characters...

**Comment by mgorges** [comment]
That sounds like a sensible plan. Making a 16MB texture, which takes about 10min on my laptop, is probably going to give you a rather slow app...

**Comment by clpetersen** [comment]
Just a comment on use: Unless you really need full free-form entry of Japanese text, it might make more sense for you to pre-render your unicode text using the STRINGS mechanism, as demonstrated in the DemoUnicode app. This will be probably be much easier to work with than having a giant texture atlas of the entire font.

**Comment by duerrp** [comment]
Thanks for the hint. I considered it, but unfortunately I do need programatically generated strings at runtime. I compiled a shorter list of ~2500 characters but my PC is running out of memory when I try to compile the resulting .scm file. I guess I have to dig into the sources to see if it is possible to tap into the native fonts somehow.

**Comment by clpetersen** [comment]
For completeness, another option would be to generate the font dynamically from an embedded true type font. Commit cf7e49d allows dynamic font generation from unicode strings, so you can do something along:
```
(define (update-string gui wgt labelstring)
   (glgui-widget-set! gui wgt 'font (ttf->fnt "path_to_annapurna.ttf" 18 labelstring))
   (glgui-widget-set! gui wgt 'label labelstring)
)
(update-string mygui mywidget "एक हफ्ते में सात दिन")
```
This may be a solution in certain cases where strings cannot be generated at compile time.
