### ISSUE TITLE
Debugging Information/Support

### ISSUE THREAD

**Issue by VincentToups** [part-cw/lambdanative#51]
I'm developing a rather complicated application with lambdanative (a port of a game).  I love lambdanative, but I am vexed by the compiled executable  producing `Segmentation fault` and no other error messages for even very simple problems (calling a function with an unbound value, for instance).

Reading the gambit-c documentation implies that I should be able to get more detailed information about the program failures, but passing `-:` arguments to the generated executable seems to have no effect.  Is there documentation about how one should go about debugging lambdanative apps?  Is it possible to run the entire application in interpreted mode to enjoy better support?  Other options?

**Comment by mgorges** [comment]
The first thing to do is to look into the `log/*` files that your crashed application generated. (you may need to run the app twice, if it has never run before as the log folder only gets created on the initial run.) These will show basic errors. Alternatively try `make install` which places the application on your desktop (but overwrites existing builds there).

If that is not sufficient, reconfigure the application in debug mode, e.g. `./configure telePORT debug`, clean the cache so symbols are not stripped from libgambc and then recompile: `make clean; make` should do that. If you now run it you should get rather verbose log messages of errors. - You can even run it in gdb with full symbols to track down errors in native code.

**Comment by mgorges** [comment]
A quick example, if I change DemoConsole to include `(sin 2.3 3.3)`, which is obviously invalid, and just run it (without adding debug mode) with `./configure DemoConsole; make; make install` and then follow up with `cat ~/Desktop/DemoConsole.app/log/*` I get the following log file:

[SYSTEM] 2015-01-28 09:58:15: Application DemoConsole built 2015-01-28 09:58:09
[SYSTEM] 2015-01-28 09:58:15: Git hash lambdanative: 6c06e2b,parts: 3f70dff
[ERROR] 2015-01-28 09:58:15: primordial: (sin 2.3 3.3): Wrong number of arguments passed to procedure
[ERROR] 2015-01-28 09:58:15: HALT

**Comment by mgorges** [comment]
Sorry, about the spam. For unbound variables the compiler should already give you a warning. E.g. if DemoConsole contains `(sin blub)` with blub not defined, it throws a warning during compilation:
*** WARNING -- "blub" is not defined,
***            referenced in: ("/Users/mg/Documents/Programming/lambdanative-cache/macosx/build/3758660784.c")

and the log file also contains the following error:
[ERROR] 2015-01-28 10:00:29: primordial: (sin #!unbound): (Argument 1) NUMBER expected

**Comment by VincentToups** [comment]
I see - amazingly useful!  This should probably be in a more prominent place in the documentation.

**Comment by qingniaotonghua** [comment]
Hi,I have constructed the lambdanative on my mac os x yosemite, and cross complied the demo apps to generate the android apks. What make me confused is that the apps can pass the cross complication on the  Android 5.0.1, but can't pass any other android versions,the error information is:
/ndk-build --silent APP_ABI=armeabi
[armeabi] Compile thumb  : payloadshared <= bootstrap.c
[armeabi] SharedLibrary  : libpayloadshared.so
os.c:1754: error: undefined reference to 'lstat64'
os.c:1755: error: undefined reference to 'stat64'
os_base.c:1483: error: undefined reference to 'sigemptyset'
os_files.c:1088: error: undefined reference to 'mkfifo'
os_io.c:6127: error: undefined reference to 'fstat64'
os_io.c:673: error: undefined reference to 'sigemptyset'
os_io.c:674: error: undefined reference to 'sigaddset'
os_io.c:6800: error: undefined reference to 'grantpt'
os_io.c:6753: error: undefined reference to 'tcgetattr'
os_io.c:6764: error: undefined reference to 'tcsetattr'
os_tty.c:243: error: undefined reference to 'tcgetattr'
os_tty.c:530: error: undefined reference to 'tcsetattr'
os_tty.c:514: error: undefined reference to 'cfsetispeed'
os_tty.c:515: error: undefined reference to 'cfsetospeed'
os_tty.c:8580: error: undefined reference to 'sigemptyset'
os_tty.c:8581: error: undefined reference to 'sigaddset'
os_tty.c:8582: error: undefined reference to 'sigaddset'
os_tty.c:8583: error: undefined reference to 'sigaddset'
os_tty.c:8599: error: undefined reference to 'sigemptyset'
collect2: error: ld returned 1 exit status
make[1]: *** [obj/local/armeabi/libpayloadshared.so] Error 1
ERROR: failed with exit code 2
BUILD FAILED - configure with verbose option for more information
make: *** [all] Error 1

**Comment by mgorges** [comment]
My previous comment somehow got lost - I started a [debugging](../wiki/Debugging) section in the Wiki, which may need some expanding. Please feel free to add to it and close the ticket if you think it is good enough. Thanks!
