### ISSUE TITLE
Cross-compilation for different android versions errors

### ISSUE THREAD

**Issue by qingniaotonghua** [part-cw/lambdanative#52]
Hi,I have constructed the lambdanative on my mac os x yosemite, and cross complied the demo apps to generate the android apks. What make me confused is that the apps can pass the cross compilation on the  Android 5.0.1, but can't pass any other android versions,the error information is:
/ndk-build --silent APP_ABI=armeabi
[armeabi] Compile thumb  : payloadshared <= bootstrap.c
[armeabi] SharedLibrary  : libpayloadshared.so
os.c:1754: error: undefined reference to 'lstat64'
os.c:1755: error: undefined reference to 'stat64'
os_base.c:1483: error: undefined reference to 'sigemptyset'
os_files.c:1088: error: undefined reference to 'mkfifo'
os_io.c:6127: error: undefined reference to 'fstat64'
os_io.c:673: error: undefined reference to 'sigemptyset'
os_io.c:674: error: undefined reference to 'sigaddset'
os_io.c:6800: error: undefined reference to 'grantpt'
os_io.c:6753: error: undefined reference to 'tcgetattr'
os_io.c:6764: error: undefined reference to 'tcsetattr'
os_tty.c:243: error: undefined reference to 'tcgetattr'
os_tty.c:530: error: undefined reference to 'tcsetattr'
os_tty.c:514: error: undefined reference to 'cfsetispeed'
os_tty.c:515: error: undefined reference to 'cfsetospeed'
os_tty.c:8580: error: undefined reference to 'sigemptyset'
os_tty.c:8581: error: undefined reference to 'sigaddset'
os_tty.c:8582: error: undefined reference to 'sigaddset'
os_tty.c:8583: error: undefined reference to 'sigaddset'
os_tty.c:8599: error: undefined reference to 'sigemptyset'
collect2: error: ld returned 1 exit status
make[1]: *** [obj/local/armeabi/libpayloadshared.so] Error 1
ERROR: failed with exit code 2
BUILD FAILED - configure with verbose option for more information
make: *** [all] Error 1

Would you have any ideals to solve this problems?

**Comment by mgorges** [comment]
I will need some more information: What ANDROIDAPI did you specify in your SETUP file. Also what available Android targets do you have installed? Finally, what android version are you trying to compile for?

**Comment by qingniaotonghua** [comment]
Hi，the ANDROIDAPI I specify in my SETUP file is 14，the available Android targets I used is Android 4.0 －API Level 14. I’am sorry I don’t know where I can set the android version I want to comply for, I just regard the Android targets version as the android version I want to comply for..Could you tell me how to set the android version I want to comply for?
all demo apps can’t pass the make procedure,the error information is:

NDK_MODULE_PATH=/Users/王玮/.lambdanative/tmp.Lw0MoX /usr/local/android-ndk-r10d/ndk-build --silent APP_ABI=armeabi

[armeabi] Compile thumb  : payloadshared <= bootstrap.c

[armeabi] SharedLibrary  : libpayloadshared.so

os.c:1754: error: undefined reference to 'lstat64'

os.c:1755: error: undefined reference to 'stat64'

os_base.c:1483: error: undefined reference to 'sigemptyset'

os_files.c:1088: error: undefined reference to 'mkfifo'

os_io.c:6127: error: undefined reference to 'fstat64'

os_io.c:673: error: undefined reference to 'sigemptyset'

os_io.c:674: error: undefined reference to 'sigaddset'

os_io.c:6800: error: undefined reference to 'grantpt'

os_io.c:6753: error: undefined reference to 'tcgetattr'

os_io.c:6764: error: undefined reference to 'tcsetattr'

os_tty.c:243: error: undefined reference to 'tcgetattr'

os_tty.c:530: error: undefined reference to 'tcsetattr'

os_tty.c:514: error: undefined reference to 'cfsetispeed'

os_tty.c:515: error: undefined reference to 'cfsetospeed'

os_tty.c:8580: error: undefined reference to 'sigemptyset'

os_tty.c:8581: error: undefined reference to 'sigaddset'

os_tty.c:8582: error: undefined reference to 'sigaddset'

os_tty.c:8583: error: undefined reference to 'sigaddset'

os_tty.c:8599: error: undefined reference to 'sigemptyset'

collect2: error: ld returned 1 exit status

make[1]: *** [obj/local/armeabi/libpayloadshared.so] Error 1

ERROR: failed with exit code 2

BUILD FAILED - configure with verbose option for more information

make: *** [all] Error 1



In fact,I found that the compiling procedure of all demo apps will occur the same errors above on any android target versions which are below the android 5.0.1-API Level 21.


When the  android target version is the android 5.0.1-API Level 21, some demo apps can pass the compliation,but some can’t. for example:
1 When I make DemoSensors app,the error are:
NDK_MODULE_PATH=/Users/王玮/.lambdanative/tmp.UREr0K /usr/local/android-ndk-r10d/ndk-build --silent APP_ABI=armeabi

[armeabi] Compile thumb  : payloadshared <= bootstrap.c

[armeabi] SharedLibrary  : libpayloadshared.so

/Users/王玮/.lambdanative/tmp.UREr0K/libpayload/libpayload.a(1535488156.o):1535488156.c:function accel_x: error: undefined reference to 'android_accel_getx'

/Users/王玮/.lambdanative/tmp.UREr0K/libpayload/libpayload.a(1535488156.o):1535488156.c:function accel_y: error: undefined reference to 'android_accel_gety'

/Users/王玮/.lambdanative/tmp.UREr0K/libpayload/libpayload.a(1535488156.o):1535488156.c:function accel_z: error: undefined reference to 'android_accel_getz'

/Users/王玮/.lambdanative/tmp.UREr0K/libpayload/libpayload.a(1847783283.o):1847783283.c:function gyro_yaw: error: undefined reference to 'android_gyro_yaw'

/Users/王玮/.lambdanative/tmp.UREr0K/libpayload/libpayload.a(1847783283.o):1847783283.c:function gyro_pitch: error: undefined reference to 'android_gyro_pitch'

/Users/王玮/.lambdanative/tmp.UREr0K/libpayload/libpayload.a(1847783283.o):1847783283.c:function gyro_roll: error: undefined reference to 'android_gyro_roll'

/Users/王玮/.lambdanative/tmp.UREr0K/libpayload/libpayload.a(4052490860.o):4052490860.c:function enable_gps: error: undefined reference to 'android_location_toggleGPS'

/Users/王玮/.lambdanative/tmp.UREr0K/libpayload/libpayload.a(4052490860.o):4052490860.c:function disable_gps: error: undefined reference to 'android_location_toggleGPS'

/Users/王玮/.lambdanative/tmp.UREr0K/libpayload/libpayload.a(4052490860.o):4052490860.c:function sat_view: error: undefined reference to 'android_location_getsatviewed'

/Users/王玮/.lambdanative/tmp.UREr0K/libpayload/libpayload.a(4052490860.o):4052490860.c:function sat_fix: error: undefined reference to 'android_location_getsatfixed'

/Users/王玮/.lambdanative/tmp.UREr0K/libpayload/libpayload.a(4052490860.o):4052490860.c:function longitude: error: undefined reference to 'android_location_getlongitude'

/Users/王玮/.lambdanative/tmp.UREr0K/libpayload/libpayload.a(4052490860.o):4052490860.c:function latitude: error: undefined reference to 'android_location_getlatitude'

/Users/王玮/.lambdanative/tmp.UREr0K/libpayload/libpayload.a(4052490860.o):4052490860.c:function altitude: error: undefined reference to 'android_location_getaltitude'

/Users/王玮/.lambdanative/tmp.UREr0K/libpayload/libpayload.a(4052490860.o):4052490860.c:function accuracy: error: undefined reference to 'android_location_getaccuracy'

/Users/王玮/.lambdanative/tmp.UREr0K/libpayload/libpayload.a(4052490860.o):4052490860.c:function timestamp: error: undefined reference to 'android_location_gettimestamp'

/Users/王玮/.lambdanative/tmp.UREr0K/libpayload/libpayload.a(4052490860.o):4052490860.c:function location_service_status: error: undefined reference to 'android_location_service'

collect2: error: ld returned 1 exit status

make[1]: *** [obj/local/armeabi/libpayloadshared.so] Error 1

ERROR: failed with exit code 2

BUILD FAILED - configure with verbose option for more information

make: *** [all] Error 1

2 When I make DemoSchemeAndC, pngtool, packtool, ttftool apps,the error are:
 => compiling payload module..

NDK_MODULE_PATH=/Users/王玮/.lambdanative/tmp.yBUQoL /usr/local/android-ndk-r10d/ndk-build --silent APP_ABI=armeabi

[armeabi] Compile thumb  : payloadshared <= bootstrap.c

[armeabi] SharedLibrary  : libpayloadshared.so

jni/bootstrap.c:54: error: undefined reference to 'ffi_event'

jni/bootstrap.c:59: error: undefined reference to 'ffi_event'

collect2: error: ld returned 1 exit status

make[1]: *** [obj/local/armeabi/libpayloadshared.so] Error 1

ERROR: failed with exit code 2

BUILD FAILED - configure with verbose option for more information

make: *** [all] Error 1

3 When I make DemoCamera, the errors are:

NDK_MODULE_PATH=/Users/王玮/.lambdanative/tmp.wIXAb6 /usr/local/android-ndk-r10d/ndk-build --silent APP_ABI=armeabi
[armeabi] Compile thumb  : payloadshared <= bootstrap.c

[armeabi] SharedLibrary  : libpayloadshared.so

/Users/王玮/.lambdanative/tmp.wIXAb6/libpayload/libpayload.a(1706477706.o):1706477706.c:function camera_start: error: undefined reference to 'android_camera_start'

collect2: error: ld returned 1 exit status

make[1]: *** [obj/local/armeabi/libpayloadshared.so] Error 1

ERROR: failed with exit code 2

BUILD FAILED - configure with verbose option for more information

make: *** [all] Error 1

4 When I make DemoSerial, the error are:

NDK_MODULE_PATH=/Users/王玮/.lambdanative/tmp.O8w28m /usr/local/android-ndk-r10d/ndk-build --silent APP_ABI=armeabi

[armeabi] Compile thumb  : payloadshared <= bootstrap.c

[armeabi] SharedLibrary  : libpayloadshared.so

/Users/王玮/.lambdanative/tmp.O8w28m/libpayload/libpayload.a(1790122449.o):1790122449.c:function ___H__20_1790122449: error: undefined reference to 'serial_open'

/Users/王玮/.lambdanative/tmp.O8w28m/libpayload/libpayload.a(1790122449.o):1790122449.c:function ___H__20_1790122449: error: undefined reference to 'serial_openfile'

/Users/王玮/.lambdanative/tmp.O8w28m/libpayload/libpayload.a(1790122449.o):1790122449.c:function ___H__20_1790122449: error: undefined reference to 'serial_close'

/Users/王玮/.lambdanative/tmp.O8w28m/libpayload/libpayload.a(1790122449.o):1790122449.c:function ___H__20_1790122449: error: undefined reference to 'serial_readchar'

/Users/王玮/.lambdanative/tmp.O8w28m/libpayload/libpayload.a(1790122449.o):1790122449.c:function ___H__20_1790122449: error: undefined reference to 'serial_writechar'

/Users/王玮/.lambdanative/tmp.O8w28m/libpayload/libpayload.a(1790122449.o):1790122449.c:function ___H__20_1790122449: error: undefined reference to 'serial_flush'

collect2: error: ld returned 1 exit status

make[1]: *** [obj/local/armeabi/libpayloadshared.so] Error 1

ERROR: failed with exit code 2

BUILD FAILED - configure with verbose option for more information

make: *** [all] Error 1

**Comment by mgorges** [comment]
We think something is broken in your toolchain. Could you please try `./configure DemoRedSquare android debug verbose`, followed by `make scrub; make;` and post there full (and rather long) results as a [Gist](https://gist.github.com) ? Thanks.

**Comment by qingniaotonghua** [comment]
Thanks a lot, the make information link is below:
https://gist.github.com/qingniaotonghua/f8d2101930bea3e611c2

**Comment by clpetersen** [comment]
This build looks like it succeeded. Are you able to run the application on your android device (```make install```)? There seems to be a permissions problem in the scrub, where files in the calculator app could not be deleted.. but this should not affect the DemoRedSquare build.

**Comment by qingniaotonghua** [comment]
Yes, my problem is solved, the apps can run normally thank you so much!
