### ISSUE TITLE
How to render more than one gui at once

### ISSUE THREAD

**Issue by qingniaotonghua** [part-cw/lambdanative#57]
The code below is very like the demo app named DemoRedSquare, the difference between them is that I add a new gui named gui1 into the DemoRedSquare. What make me confused is why this program can't show all the guis together? To show more than one gui, what can I do? thanks!

https://gist.github.com/qingniaotonghua/da955184b1454499b8ec

**Comment by mgorges** [comment]
[(glgui-event guis t x y)](../wiki/glgui-event) can only be used once in your code, not twice. If you want to render more than one gui, guis has to be a list. See line 235 in [modules/ln_glgui/glgui.scm](../blob/master/modules/ln_glgui/glgui.scm#L235) how this works internally.

An example for the correct usage is: ````(glgui-event (list gui:main gui:trends) t x y)````

**Comment by qingniaotonghua** [comment]
Thanks a lot!
