### ISSUE TITLE
How to  increase the number of GUI objects dynamically

### ISSUE THREAD

**Issue by qingniaotonghua** [part-cw/lambdanative#58]
I want to  increase the number of GUI objects dynamically according to the input during the execution of the program，but I don't know how to do...Could you tell me?

**Comment by mgorges** [comment]
For a start, [modules/ln_glgui/dropdownbox.scm](../blob/master/modules/ln_glgui/dropdownbox.scm) dynamically creates and destroys list items for selection in a dropdown menu.

Could you provide an example of what you try to achieve so we give a better example? Thanks.

**Comment by qingniaotonghua** [comment]
Actually, I want to do data visualization like histogram and fan graph. On the GUI interface, There are a data list input gui and a corresponding data visualization like  histogram or fan graph, the size of the data list can increase or decrease, so the visualization gui also need to be changed dynamically..

By the way, is it difficult to draw sector on the lambdanative?

**Comment by mgorges** [comment]
I added a basic barchart widget to lambdanative. I would appreciate extensions, e.g. axis labels or axis ticks, if you have time to expand upon it! Here some usage examples until the Wiki is updated:

    (glgui-barchart gui 0 0 150 150 '(1 2 3 4) Blue)
    (glgui-barchart gui 0 170 150 150 '(1 2 3 4) (list Blue Red Green Yellow))
    (glgui-barchart gui 170 0 150 150 '(1 2 3 4 5 6 7 8 9 20) Green)
    (glgui-barchart gui 170 170 150 150 '((1 2) (3 4) (5 6) (7 8) (9 0)) (list Green Red))

For the fan I currently don't have time to help you with this. - If you can provide an example image I may be able to point you in the right direction. The main problem is that you can't just use a texture for it, which we use for the vast majority of our rendering. Hence, you would need to draw the parts as individual vertices in OpenGL, e.g. using  [(glCoreVertex2f x0 y0 . xtra)](../wiki/glCoreVertex2f). If you just need a simple time series plot, look at [(glgui-trace g x y w h trace color . lim)](../wiki/glgui-trace)

**Comment by qingniaotonghua** [comment]
OK ,I try to expand glgui-barchart, thank you..

**Comment by mgorges** [comment]
Let's keep this open until we have figured out if we also need a fan chart.

**Comment by mgorges** [comment]
Commit 36ea95a added a linechart and scatterplots. Closing this unless we need something else?
