### ISSUE TITLE
Puzzling question

### ISSUE THREAD

**Issue by qingniaotonghua** [part-cw/lambdanative#60]
when I replace the code"glgui-box gui (/ (- w dim) 2) (/ (- h dim) 2) dim dim Red)" with (glgui-keypad gui 0 0 (glgui-width-get) 140 calc_24.fnt keypad) in the DemoRedSquare, the program can't run....the ./configure WKeypad android debug verbose;make scrub;make information is below:
https://gist.github.com/qingniaotonghua/ba3e2991f7793c6e78ad

when
./configure WKeypad android debug;make;make install
it show:
 WARNING -- "calc_24.fnt" is not defined,
***            referenced in: ("/Users/\347\216\213\347\216\256/Library/Caches/lambdanative/macosx/build/1853929266.c")
*** WARNING -- "keypad" is not defined,
***            referenced in: ("/Users/\347\216\213\347\216\256/Library/Caches/lambdanative/macosx/build/1853929266.c")

https://gist.github.com/qingniaotonghua/47982fe66776b08e5412

but  the demo app Calculator which contain "glgui-keypad" can run normally..

**Comment by mgorges** [comment]
I don't understand why either of two warnings are puzzling to you. The reason this works in the `Calculator` app, but not your app, is that `keypad` is defined in lines 46-54, and `apps/Calculator/FONTS` defines `DejaVuSans.ttf ascii7.set 32,24,14 calc`. Specifically,

a) Unless you declared a font in the `FONTS` file in your application's folder (where the main.scm is located) `calc_24.fnt` doesn't exist. The minimum for your code to work is something like this, see [wiki/FONTS](../wiki/FONTS):

    cmss.ttf ascii7.set 24 calc

b) As for the `keypad` not being defined, if you look at the syntax for [(glgui-keypad g x y w h fnt . keypad)](../wiki/glgui-keypad), the keypad is optional! If you choose to specify one it has to be from the list of available keypads, such as `keypad:numeric` , `keypad:numfloat` , `keypad:numcolon` , `keypad:numdash` , `keypad:calculator`, `keypad:default` , or` keypad:simplified` Or if you'd like you can define your own keypad, which is what the `Calculator` app did.

**Comment by qingniaotonghua** [comment]
Oh, please forgive my ignorance, the program can run, thank you very much for your patience guidance

**Comment by mgorges** [comment]
You are welcome.
