### ISSUE TITLE
Is there a edit box in the lambdanative?

### ISSUE THREAD

**Issue by qingniaotonghua** [part-cw/lambdanative#61]
Hi, I just want to create a edit box like a text editor to get what I enter from the keypad, in this edit box,I hope I can control the position of  the cursor,could you tell me how can I do? thanks,Y(^_^)Y

**Comment by mgorges** [comment]
[(glgui-inputlabel g x y w h label fnt color . bgcolor)](../wiki/glgui-inputlabel) is probably what you are looking for. However, I am not sure you can move the cursor in it out of the box - I'll have to get back to you on that.

**Comment by ddunsmuir** [comment]
There is no implementation of moving the cursor within the input label, the cursor is always at the end of the text. The cursor will be flashing in a text box and taking keypad events if 'focus is set to #t, this happens when you click on a glgui-inputlabel.

**Comment by mgorges** [comment]
An initial attempt to improve this situation can be found in cef6c4e. Feel free to expand with other functionality, such as support for Home/End keys, and up/down keys in case of the wrapped label.

**Comment by mgorges** [comment]
Will close this for now - if functionality is not sufficient please provide a patch or reopen.
