### ISSUE TITLE
Debug Logs on Android

### ISSUE THREAD

**Issue by VincentToups** [part-cw/lambdanative#64]
I have an app that compiles and runs without problem on Ubuntu but seems to segfault on Android.  I have compiled in debug mode, but cannot find the logs on the device anywhere.  Where do they typically go?

There is a folder on my phone named after the app, but it is empty.

**Comment by clpetersen** [comment]
The logs live in a ```log``` subdirectory of the app directory. Logs are only created if this directory exists. The easiest way to create it is to place something like this in the initialization handler:

    (let ((logdir (string-append (system-directory) "/log")))
     (if (not (file-exists? logdir)) (create-directory logdir)))

You can see an example of this in the ```main.scm``` file of the DemoRTAudio app.

**Comment by VincentToups** [comment]
Most excellent, thanks!

**Comment by VincentToups** [comment]
Interestingly, this did result in the creation of the log directory, but
there still no logs post-crash.  The game starts up, but something rather
late in the turn logic causes the crash, and this is typically after many
log messages are printed in the linux version.  Any suggestions?

I am building with:

./configure CorpseWizard android debug && make clean && make && make
install

**Comment by VincentToups** [comment]
Ah, have to run it more than once!
