### ISSUE TITLE
Need a better default ANDROIDAPI in SETUP.template

### ISSUE THREAD

**Issue by ackalker** [part-cw/lambdanative#67]
Using ANDROIDAPI=10 in SETUP (with the correct target for API 10 installed using the SDK manager), I see:

```
$ ./configure Calculator android
[...]
$ make
[...]
=== configured to build Calculator version 1.0 for android on linux in normal mode
** WARNING Android API changed to 9
[...]
==> creating android loader needed for Calculator..
 => creating android project..
ERROR: API 9 not a target.
```

This appears to be a nasty Catch-22: Android API 10 is available as a terget in the latest SDK Manager, however it is not included in the latest NDK distribution. While Android API 9 is available in the NDK distribution, it is not available as a target in the latest SDK Manager.

I would like to suggest setting `ANDROIDAPI` to at least `12` in `SETUP.template` to spare users from having to sort this out. I think it would also be nice to include a table of some sorts (and keep it updated!) which indicates which APIs are available in both the SDK Manager and the NDK.

Another alternative would be to make the build scripts more intelligent with regards to API (backwards) compatibility, for instance to match a newer SDK API target with an older NDK API or the other way round. This probably needs (a lot of) testing.

#### Android SDK and NDK API availability
(Current as of 2015-08-09, using the latest installers)

Android version | API | SDK | NDK
|---|:---|:---:|:---:
? | 22 | X | -
5.0.1 | 21 | X | X
4.4W.2 | 20 | X | -
4.4.2 | 19 | X | X
4.3.1 | 18 | X | X
4.2.2 | 17 | X | X
4.1.2 | 16 | X | X
4.0.3 | 15 | X | X
4.0 | 14 | O | X
3.2 | 13 | O | X
3.1 | 12 | O | X
3.0 | 11 | O | -
2.3.3 | 10 | X | -
2.3.1 | 9 | H | X

Legend:

X = Available
O = Obsolete (must check the checkbox marking `Obsolete` to show)
H = Hard to reach, obsolete (must check the checkbox marking `Obsolete` followed by some crazy voodoo magic to show)

**Comment by ackalker** [comment]
_nevermind_, after twiddling a lot with the SDK manager, more (obsolete) API targets suddenly appeared. I will add them to the table in my previous comment, adding a note that they may be hard reach.

**Comment by clpetersen** [comment]
Commit bb66d6a changes the default API to 15, which appears to be the oldest non-obsolete target in your list. Thanks for looking into this.
