### ISSUE TITLE
can not run on ios Simulator

### ISSUE THREAD

**Issue by yarec** [part-cw/lambdanative#69]
➜  lambdanative git:(master) ✗ cat ./run
ios-sim launch /Users/rt/Library/Caches/lambdanative/ios/DemoHelloWorld.app --devicetypeid iPhone-6, 8.4
➜  lambdanative git:(master) ✗ ./run
Sep 10 10:55:52 rtdeMac-mini com.apple.CoreSimulator.SimDevice.A275F68D-6EA9-45A7-AEFC-6045B8B22663.launchd_sim[29701] (UIKitApplication:com.softidy.demohelloworld[0xa998][32762]): Program specified by service does not contain one of the requested architectures: �\!
Sep 10 10:55:52 rtdeMac-mini.lan SpringBoard[29715]: Unable to get pid for 'UIKitApplication:com.softidy.demohelloworld[0xa998]': No such process (err 3)
Sep 10 10:55:52 rtdeMac-mini.lan SpringBoard[29715]: Application 'UIKitApplication:com.softidy.demohelloworld[0xa998]' exited voluntarily.
Sep 10 10:55:52 rtdeMac-mini.lan SpringBoard[29715]: Unable to deliver -[UIRemoteApplication showTopMostMiniAlertWithSynchronizationPort:] message to port 0: (ipc/send) invalid destination port

➜  lambdanative git:(master) ✗ make
=== using profile softidy [/Users/rt/vcs/sdk/lambdanative/PROFILE]..
=== configured to build DemoHelloWorld version 1.0 for ios on macosx in normal mode
lambdanative: f94ee6a
==> checking for required tools..
==> checking for required libraries..
==> checking for lambdanative tools..
==> creating libraries needed for DemoHelloWorld..
 => liblambdanative..
 => cleaning up..
 => exploding library liblambdanative..
==> creating artwork needed for DemoHelloWorld..
==> creating textures needed for DemoHelloWorld..
==> creating fonts needed for DemoHelloWorld..
==> creating strings needed for DemoHelloWorld..
 => compiling scheme payload..
 => done compiling scheme payload
 => generating hook..
 => assembling payload..
==> creating ios loader needed for DemoHelloWorld..
 => preparing icons..
 => processing sounds needed for DemoHelloWorld..
 => processing sounds from /Users/rt/vcs/sdk/lambdanative/apps/DemoHelloWorld/sounds...
 => /Users/rt/vcs/sdk/lambdanative/apps/DemoHelloWorld/sounds/ahooga.wav..
 => preparing plist..
 => preparing custom config..
 => building loader..
 => verifying application..
 => relocating application..
 => cleaning up..
=== /Users/rt/Library/Caches/lambdanative/ios/DemoHelloWorld.app
==> making package..
 => making ios zip archive..
=== /Users/rt/Library/Caches/lambdanative/packages/DemoHelloWorld-1.0-ios.zip

**Comment by clpetersen** [comment]
LambdaNative does not support simulator targets. We've not considered that worth the effort, as it is generally equally/more efficient to simply target the host desktop system during app development. That's what we do here.

**Comment by yarec** [comment]
ok, thanks!
