### ISSUE TITLE
Make problem on Ubuntu 15.04

### ISSUE THREAD

**Issue by gambiteer** [part-cw/lambdanative#71]
make stops with

==> creating libraries needed for pngtool..
 => libgd..
 => downloading https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz..
WARNING: wget failed, retrying without certificate check..
ERROR: failed with exit code 8
>> download of https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz failed
BUILD FAILED - configure with verbose option for more information
Makefile:2: recipe for target 'all' failed

**Comment by gambiteer** [comment]
The command sequence I used was

    62	10:58	git clone https://github.com/part-cw/lambdanative.git
    63	10:58	cd lambdanative/
    64	10:58	cp SETUP.template SETUP
    65	10:58	cp PROFILE.template PROFILE
    66	10:58	./configure DemoConsole
    67	10:58	make

**Comment by clpetersen** [comment]
It looks like the download of libgd failed for some reason. I just tried a complete reinstall on my ubuntu box (14.04), it ran to completion without any issues. Could you try to download libgd manually:
```
wget https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
```
and if that succeeds copy the tarball into the package cache `$HOME/.cache/lambdanative/packages`, then repeat the configure make steps.

**Comment by gambiteer** [comment]
On 09/14/2015 11:26 AM, Chris Petersen wrote:
> It looks like the download of libgd failed for some reason. I just tried
> a complete reinstall on my ubuntu box (14.04), it ran to completion
> without any issues. Could you try to download libgd manually:
>
> |wget https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz |
>
> and if that succeeds copy the tarball into the package cache
> |$HOME/.cache/lambdanative/packages|, then repeat the configure make steps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/part-cw/lambdanative/issues/71#issuecomment-140115431>.
>
I get

heine:~/programs/lambdanative> wget 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
--2015-09-14 11:26:49-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Resolving bitbucket.org (bitbucket.org)... 131.103.20.168, 131.103.20.167
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:50-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Resolving bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)... 54.231.12.217
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:50 ERROR 403: Forbidden.

--2015-09-14 11:26:50-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:50-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:50 ERROR 403: Forbidden.

--2015-09-14 11:26:50-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:50-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:50 ERROR 403: Forbidden.

--2015-09-14 11:26:50-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:50-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:51 ERROR 403: Forbidden.

--2015-09-14 11:26:51-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:51-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:51 ERROR 403: Forbidden.

--2015-09-14 11:26:51-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:51-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:51 ERROR 403: Forbidden.

--2015-09-14 11:26:51-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:51-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:51 ERROR 403: Forbidden.

--2015-09-14 11:26:51-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:52-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:52 ERROR 403: Forbidden.

--2015-09-14 11:26:52-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:52-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:52 ERROR 403: Forbidden.

--2015-09-14 11:26:52-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:52-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:52 ERROR 403: Forbidden.

--2015-09-14 11:26:52-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:52-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:52 ERROR 403: Forbidden.

--2015-09-14 11:26:52-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:53-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:53 ERROR 403: Forbidden.

--2015-09-14 11:26:53-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:53-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:53 ERROR 403: Forbidden.

--2015-09-14 11:26:53-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:53-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:53 ERROR 403: Forbidden.

--2015-09-14 11:26:53-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:53-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:54 ERROR 403: Forbidden.

--2015-09-14 11:26:54-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:54-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:54 ERROR 403: Forbidden.

--2015-09-14 11:26:54-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:54-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:54 ERROR 403: Forbidden.

--2015-09-14 11:26:54-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:54-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:54 ERROR 403: Forbidden.

--2015-09-14 11:26:54-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:55-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:55 ERROR 403: Forbidden.

--2015-09-14 11:26:55-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
--2015-09-14 11:26:55-- 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu+/M8FsJa2bb6oJOTIM=&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment;%20filename=%22libgd-2.1.1.tar.gz%22
Connecting to bbuseruploads.s3.amazonaws.com 
(bbuseruploads.s3.amazonaws.com)|54.231.12.217|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-09-14 11:26:55 ERROR 403: Forbidden.

--2015-09-14 11:26:55-- 
https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz
Connecting to bitbucket.org (bitbucket.org)|131.103.20.168|:443... 
connected.
HTTP request sent, awaiting response... 302 FOUND
Location: 
https://bbuseruploads.s3.amazonaws.com/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz?Signature=NnCJIggQu%2B%2FM8FsJa2bb6oJOTIM%3D&Expires=1442244720&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82&response-content-disposition=attachment%3B%20filename%3D%22libgd-2.1.1.tar.gz%22 
[following]
20 redirections exceeded.
heine:~/programs/lambdanative>

**Comment by clpetersen** [comment]
Wow, that's a weird one.. a wget infinite loop?? The same wget command works on my machines after a single redirect. Commit 43a6a38 now points to a local tarball instead for now, see if that fixes your problem.

**Comment by gambiteer** [comment]
On 09/14/2015 11:44 AM, Chris Petersen wrote:
> Wow, that's a weird one.. a wget infinite loop?? The same wget command
> works on my machines after a single redirect. Commit 43a6a38
> <https://github.com/part-cw/lambdanative/commit/43a6a38f9d472a05b146bf919938eef257035365>
> now points to a local tarball instead for now, see if that fixes your
> problem.

Thanks, that works.

Brad
