### ISSUE TITLE
how to specify further libraries to link with (on OpenWRT)

### ISSUE THREAD

**Issue by attila-lendvai** [part-cw/lambdanative#72]
i'm trying to compile for the OpenWRT target, and building the mqtt lib fails with some missing libpthread symbols.

on OpenWRT it's possible to install packages/.so for libmosquitto and libpthread, and i'm wondering if it's possible to specify somehow that the final call to the linker should link to these OpenWRT provided libs (as opposed to using the internal ones in LambdaNative).

also, on a related note, for now i explicitly target OpenWRT only, but i got the impression that if i use LambdaNative then i get a significantly nicer environment than using Gambit directly. is that right, or is it just a newbie's impression?

note: i very much welcome also if someone more knowledgeable updates the wiki and just points me to that.

great project, thanks for all the work!

**Comment by clpetersen** [comment]
The combination of MQTT and OpenWRT sounds fascinating!  We are not currently using OpenWRT in a production system, and are not currently set up to test this target well. You should simply be able to add additional system libraries like pthread to the loader compilation step, which is line 48 in `targets/openwrt/build-binary`, currently:
```
\$(CC) \$(LDFLAGS) -o $SYS_APPNAME libpayload.a libgambc.a -lutil -ldl -lm
```
you might just get away with a simple change like
```
\$(CC) \$(LDFLAGS) -o $SYS_APPNAME libpayload.a libgambc.a -lutil -lpthread -ldl -lm
```
By the way, please submit any changes you end up making to the openwrt target back to lambdanative to keep that particular target up to date. It would be much appreciated!

LambdaNative is basically an environment that sits on top of the bare-bones Gambit compiler and tries to manage the dependencies that real-world applications have in a platform-independent, and hopefully minimally invasive, way. For our internal use it takes a lot of the headache out of managing multiple applications on multiple targets.

**Comment by attila-lendvai** [comment]
FTR, i've found the answer meanwhile.

for now it looks like one needs to kludge the scripts under ```target/openwrt```.

this is what i had to do to make it work using the SDK from OpenWRT 15.05. note the changed path inside the SDK (an extra ```base/``` needs to be added). the rest is just my hacking ahead...

```
diff --git a/targets/openwrt/build-binary b/targets/openwrt/build-binary
index ba5588b..09e4f89 100755
--- a/targets/openwrt/build-binary
+++ b/targets/openwrt/build-binary
@@ -36,7 +36,7 @@
 # SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 archname=`basename $OPENWRTSDK | cut -f 3 -d "-"`
-pkgfile=$OPENWRTSDK/bin/$archname/packages/$(echo $SYS_APPNAME)_$(echo $SYS_APPVERSION)_$archname.ipk
+pkgfile=$OPENWRTSDK/bin/$archname/packages/base/$(echo $SYS_APPNAME)_$(echo $SYS_APPVERSION)_$archname.ipk
 fnlpkgfile=$SYS_PREFIXROOT/packages/$(echo $SYS_APPNAME)-$(echo $SYS_APPVERSION)-openwrt-$archname.ipk
 tmpdir=$OPENWRTSDK/package/$SYS_APPNAME
 mkdir -p $tmpdir/src
@@ -45,7 +45,7 @@ cp $SYS_PREFIX/lib/libpayload.a $tmpdir/src/libpayload.a
 echo " => compiling application.."
 cat > $tmpdir/src/Makefile  << _EOF
 $SYS_APPNAME:
-	\$(CC) \$(LDFLAGS) -o $SYS_APPNAME libpayload.a libgambc.a -lutil -ldl -lm
+	\$(CC) \$(LDFLAGS) -o $SYS_APPNAME libpayload.a libgambc.a -lutil -ldl -lm -lpthread
 _EOF
 cat > $tmpdir/Makefile  << _EOF
 include \$(TOPDIR)/rules.mk
@@ -55,6 +55,7 @@ PKG_BUILD_DIR:=\$(BUILD_DIR)/\$(PKG_NAME)
 include \$(INCLUDE_DIR)/package.mk
 define Package/$SYS_APPNAME
 	TITLE:=$SYS_APPNAME
+	DEPENDS:=+libpthread +bluez-libs
 endef
 define Build/Prepare
 	mkdir -p \$(PKG_BUILD_DIR)
diff --git a/targets/openwrt/package b/targets/openwrt/package
index 82e57fe..c9ddec3 100755
--- a/targets/openwrt/package
+++ b/targets/openwrt/package
@@ -36,8 +36,8 @@
 # SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 archname=`basename $OPENWRTSDK | cut -f 3 -d "-"`
-pkgfile="$SYS_PREFIXROOT/packages/$(echo $SYS_APPNAME)-$(echo $SYS_APPVERSION)-$(echo $SYS_PLATFORM)-$archname.ipk"
+pkgfile="$SYS_PREFIXROOT/packages/base/$(echo $SYS_APPNAME)-$(echo $SYS_APPVERSION)-$(echo $SYS_PLATFORM)-$archname.ipk"
 assertfile $pkgfile
 echo "=== $pkgfile"
 
-#eof
\ No newline at end of file
+#eof
```

**Comment by attila-lendvai** [comment]
oh, i should have refreshed the browser... :) thanks for the fast answer!

ok, i'll fork and add pull requests when i have anything useful. i have made some nice progress meanwhile, now i'm porting some C bluetooth LE code to scheme... building seems to work for now, and i can add extra dependencies to the openwrt package, too.

not sure how to factor out the required customizations into something inside the project dir, but i guess that can wait until i get more experience.

**Comment by attila-lendvai** [comment]
i'm closing this... thanks again, and see you on a pull request!
