### ISSUE TITLE
<build-binary> requests $libs variable not assigned in <make.sh>

### ISSUE THREAD

**Issue by mhueser** [part-cw/lambdanative#73]
I encountered the following issue with the most recent version:

1. Tried to build an application that uses "serial" module, which
depends on "android-usb-serial" library.
2. Android USB serial library is built and outputs a JAR
3. "ar x android-usb-serial.a" tries to explode the library during build process, however 
no *.o files are output in this step
4. When global "ar \*" is attempted to link the payload, it fails because lib/usb-serial-android/\*.o" expands to nothing but is preserved in the command literally. The fix is to change the *.o into $(ls *.o) to guarantee expand to "empty".
5. When the loader for android is built, during "adding precompiled libraries" step (in "build-binary" shell script) it loops over the $libs variable. This variable is empty though at this stage. I assume it should have been assigned to during the execution of "make.sh". A variable $libraries exists instead.
The fix is to rename the loop-variable in "build-binary" from $libs to $libraries.

**Comment by clpetersen** [comment]
Thanks for reporting this! I was able to replicate the problem when compiling DemoSerial for android. Fixed with commit aab83ac.
