### ISSUE TITLE
LibGD compilation broken for Android

### ISSUE THREAD

**Issue by mhueser** [part-cw/lambdanative#79]
GD compilation fails on commit 8c618ecd82812771c6ac830268bf57cae954c25c (most recent)

I am building for Android API Level 21 with SDK 24.3.4.2 and NDK r10e-1

Can you reproduce the problem exhibited below?

>>>> DETAILED COMPILATION ERROR <<<<

ibtool: compile:  /home/mhueser/var/cache/lambdanative/android/android-ndk-arm-21-toolchain/bin/arm-linux-androideabi-gcc -g -O0 -DANDROID -isysroot /home/mhueser/var/cache/lambdanative/android/android-ndk-arm-21-toolchain/sysroot -I/home/mhueser/var/cache/lambdanative/android/include -L/home/mhueser/var/cache/lambdanative/android/lib -std=gnu99 -DHAVE_CONFIG_H -I. -I/home/mhueser/var/cache/lambdanative/android/include -I/home/mhueser/var/cache/lambdanative/android/include/libpng16 -I/home/mhueser/var/cache/lambdanative/android/include/freetype2 -g -O2 -I/usr/include -I/home/mhueser/var/cache/lambdanative/android/include -fvisibility=hidden -MT gd_rotate.lo -MD -MP -MF .deps/gd_rotate.Tpo -c gd_rotate.c -o gd_rotate.o
In file included from /usr/include/math.h:440:0,
                 from gd_rotate.c:7:
gd_rotate.c: In function 'gdImageRotate45':
/usr/include/bits/mathinline.h:751:3: error: impossible constraint in 'asm'
   __asm __volatile ("fnstcw %3\n\t"           \
   ^
/usr/include/bits/mathinline.h:503:5: note: in definition of macro '__inline_mathcodeNP_'
     code;              \
     ^
/usr/include/bits/mathinline.h:746:1: note: in expansion of macro '__inline_mathcodeNP'
 __inline_mathcodeNP (floor, __x, \
 ^
/usr/include/bits/mathinline.h:751:3: error: impossible constraint in 'asm'
   __asm __volatile ("fnstcw %3\n\t"           \
   ^
/usr/include/bits/mathinline.h:503:5: note: in definition of macro '__inline_mathcodeNP_'
     code;              \
     ^
/usr/include/bits/mathinline.h:746:1: note: in expansion of macro '__inline_mathcodeNP'
 __inline_mathcodeNP (floor, __x, \
 ^
/usr/include/bits/mathinline.h:751:3: error: impossible constraint in 'asm'
   __asm __volatile ("fnstcw %3\n\t"           \
   ^
/usr/include/bits/mathinline.h:503:5: note: in definition of macro '__inline_mathcodeNP_'
     code;              \
     ^
/usr/include/bits/mathinline.h:746:1: note: in expansion of macro '__inline_mathcodeNP'
 __inline_mathcodeNP (floor, __x, \
 ^
Makefile:772: recipe for target 'gd_rotate.lo' failed
make[1]: *** [gd_rotate.lo] Error 1
make[1]: Leaving directory '/home/mhueser/.lambdanative/tmp_install/libgd-2.1.1/src'

**Comment by mgorges** [comment]
Works for me with SDK 24.4. and NDK r10c for both API targets 8 and 21.

**Comment by mhueser** [comment]
Could you check if the <mathinline.h> under $NDKROOT/platforms/ tree is used, if it exists, or the
global one </usr/include/..> instead?

I cannot easily downgrade to r10c NDK but this might be the issue.

**Comment by mgorges** [comment]
I upgraded the NDK to r10e and libgd still builds fine. For the other question - no, it doesn't exist.
```mg@kanonia2 /opt/local/android-ndk-r10e/platforms $find . -name mathinline.h```
```mg@kanonia2 /opt/local/android-ndk-r10e/platforms ```

**Comment by mhueser** [comment]
I think this issue is related, unfortunately I cannot risk downgrading glibc right now
to investigate further:

https://github.com/mupen64plus-ae/mupen64plus-ae/issues/342

**Comment by mgorges** [comment]
The idea of `--without-x` was to remove `-I/usr/include` and `-L/usr/lib` from the path, which it shouldn't be for Android compilation.

**Comment by mgorges** [comment]
commit ca8b9c4 also disables VPX for Android which may be required on some Linux versions.
