### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by VincentToups** [part-cw/lambdanative#81]
Hi - I've got a few libraries I am using for game development (pathfinding, entity component systems, heaps, pattern matching) that work with lambda native.  Is there interest in integrating them into the main distribution?

**Comment by clpetersen** [comment]
That sounds great, happy to integrate the libraries if you think them of interest to the community, and your license is permissive (BSD/Apache). I assume these libraries are self-contained Scheme modules? If so, please just submit them as pull requests, and add the matching documentation for the API calls to the lambdanative wiki.

**Comment by mgorges** [comment]
Closed with #104
