### ISSUE TITLE
Modules which define macros

### ISSUE THREAD

**Issue by VincentToups** [part-cw/lambdanative#82]
I've got a few modules in my current project which are basically entirely macros (an algebraic pattern matcher and a single dispatch, mostly static object system).  I am just `include`ing the code in my project at the moment - is there a better way to integrate them into the module system?  I am trying to reduce my compilation times.

**Comment by clpetersen** [comment]
My understanding of Gambit `define-macro`'s is that they are local to the file they appear in, and you'd therefore always need to `include` such code to make it work. I can't think of a solution to that at the moment. We've largely avoided using macros altogether partly for this reason. An automated way to load macro includes at compile time would not reduce your compilation time. I'm happy to look into this further if there is something here that I'm not aware of..

**Comment by clpetersen** [comment]
Commit 9d3aaa8 adds support for globally defined macros. Put them in a  `global-macros.scm` in your module or app directory, and they will be active for all scheme code in the entire project (and no need to manually include `global-macros.scm`, it is automatically loaded at compile time). This does not reduce compile time, but does allow macros to be shared between modules.
