### ISSUE TITLE
Sideeffect of ANDROIDAPI?

### ISSUE THREAD

**Issue by zwieblum** [part-cw/lambdanative#83]
Is there a sideeffect of using differet API versions, despite loosing downward compatibility?

**Comment by mgorges** [comment]
Could you elaborate more on what you are trying to find out? - I am using API 8,9,12,and 21 for different purposes. There is a potential need to clear the cache if you change API levels in the downwards direction.

**Comment by zwieblum** [comment]
I would like to find out if I lose some functionality when I use API 9 instead of e.g. API 21. Or, what are the benefits of using a newer API?

**Comment by mgorges** [comment]
The only thing that currently comes to mind is that if you want to use the `serial` module on Android your minimum API level is 12 (see [libraries/usb-serial-for-android/make.sh](../blob/master/libraries/usb-serial-for-android/make.sh) )

**Comment by mgorges** [comment]
There is also different behaviour in the [modules/localnotification](../blob/master/modules/localnotification) module, albeit I don't think it runs properly on any API level at the moment.
