### ISSUE TITLE
Recommendations for looping sounds and music

### ISSUE THREAD

**Issue by VincentToups** [part-cw/lambdanative#84]
I notice the audio module doesn't provide for any looping functionality, but this is pretty common for some types of sound effects and, of course, for background music.  

Any suggestions for how to get this effect?

**Comment by clpetersen** [comment]
You could do a simple real-time two-channel mixer with a looping background and a foreground for effects. The pieces to do that are there, and could be tested right away by hacking the DemoRTAudio app. I'm not sure if this sort of mixing would generalize well in terms of performance/benefit, it might be better left as an application specific implementation tailored to specific needs.

**Comment by mgorges** [comment]
Was also closed in d61af68. Thanks for the patch @VincentToups!
