### ISSUE TITLE
Cannot simultaneously play multiple sound files

### ISSUE THREAD

**Issue by VincentToups** [part-cw/lambdanative#85]
The audio module only allows playing a single file at a time (on Linux, anyway).  This precludes the relatively common case of playing, for instance, music and sound effects at the same time, or multiple sound effects at once.

**Comment by VincentToups** [comment]
I believe I can patch this support in for linux without much trouble, I'd probably need assistance for the other platforms.  Can anyone tell me whether iOS and Android already support multiple sounds at once?

**Comment by clpetersen** [comment]
On iOS and Android, sounds are played through the native sound api. I'm not sure if this supports multiple sounds at once, but assume so. It is the portaudio implementation used on the desktop platforms that doesn't currently support multiple sounds at once. It would be great if you could patch that.

**Comment by VincentToups** [comment]
I'll give it a shot.

**Comment by VincentToups** [comment]
Update: have multiple sounds playing at the same time for the portaudio version.  I'm going to clean it up a bit and then get the iOS version working.  I'll submit a pull request with a commit chain when I have iOS, Android and Linux versions working. 

At that point I will add support for looping sounds as well.  Probably via a function called `audiofile-loop` to go with `audiofile-play`.

**Comment by VincentToups** [comment]
So I am trying to debug the iOS code.  The app is just crashing, though - is there someplace I can grab the stderr or logs from the running ios app?

**Comment by clpetersen** [comment]
If your crash is inside the iOS loader itself, you'd have to use whatever debugging facilities are available in Objective C.. I'm not familiar with those unfortunately. If you are dying on the Scheme side, you can create a log folder on the device and access it through iTunes. If your app is compiled from scratch with debug enabled, the log file will contain a trace. Details of how to  create the log dir is on the wiki:
https://github.com/part-cw/lambdanative/wiki/Debugging

**Comment by VincentToups** [comment]
I'm unfortunately not much of an iOS developer either, but I think I'll
figure it out. Thanks for the hints!

**Comment by VincentToups** [comment]
Quick question about the Android sound support - looks like you are using a SoundPool object to manage sounds, which is fine for short sounds, but will not work for music.  My plan is to modify the AudioHelper class in bootstrap.java.in to manage its own pool of MediaPlayer instead.  Since MediaPlayers stream from disk, this more closely mirrors the other implementations anyway, where sound data is streamed from disk.

However, I notice that AudioHelper already creates one MediaPlayer (or is passed one, more accurately) by the code in the onCreate method of the app.  It seems like this is used during setVolume audioHelper method but I don't think it should do anything, since the soundpool manages playing the loaded audio anyway. 

Am I missing something?  Does it seem like a reasonable strategy to replace the sound pool with a pool of MediaPlayers?

**Comment by clpetersen** [comment]
When you say streaming from disk, do you mean from the file system or from the app resources? The current implementation loads the audio from resources, as you can't pack separate audio files with the apk in a conventional way to my knowledge. If that scheme will continue to work in a MediaPlayer implementation, and both wav and ogg formats are still supported, then the switch should be fine.

**Comment by VincentToups** [comment]
I guess I mean from the same place as the SoundPool currently does.  I am
also pretty sure MediaPlayers will support wav and ogg.
-V

**Comment by mgorges** [comment]
@VincentToups I know you still can't build for iOS as the Apple headers are broken in the current XCode with gcc combination. In the meantime I'd like to make some progress on this. Hence, if you feel that your mixer code will work on Android and iOS why don't you make a pull request? We could either comment on it to let you resolve problems or merge it and fix any problems ourselves.
Thanks Matthias

**Comment by VincentToups** [comment]
Good idea - let me rebase on the most recent version and then arrange a
pull request.
