### ISSUE TITLE
Timer Event

### ISSUE THREAD

**Issue by absrnd** [part-cw/lambdanative#86]
Hi - It looks like the main-event callback is being called on a timer (I have only tested on Linux)..

..if so, is this event cross-platform; what frequency? and does it have an event id?

Many thanks for your help,
Stuart.

**Comment by mgorges** [comment]
Hi Stuart,
I believe you are mistaken about the use of a timer. 

The event loop is called through events, as defined in [modules/eventloop/eventloop.scm](../blob/master/modules/eventloop/eventloop.scm). Some events are based on user-input, e.g mouse movements or keyboard presses, while others are based on the application redraw requests by OpenGL. There are fake events `EVENT_IDLE` on some platforms, to make sure the app will continue to run if it is not in focus, but this is not done on Linux. At most you should expect the eventloop to run at 100Hz, but depending on how much time you spent in each iteration it might be less frequent. If you don't want to waste CPU time it is advisable to sleep in the main loop, e.g. using `(if (fx= t EVENT_REDRAW) (thread-sleep! 0.05))`

**Comment by clpetersen** [comment]
Just to expand, the confusion may arise from the OpenGL redraw loop being driven by timers on some (all?) platforms. The event loop thus receives redraw events at a fairly regular pace (though not at any exact frequency, it's a function of how fast the hardware is and how many graphical elements are rendered at any given time), in addition to asynchronous input related events.  Also, it is possible to use the event loop framework in non-gui applications, in which case the event loop really is driven by a straightforward timer. This is however not a typical use case, and really just for our team to be able to migrate iterative code blocks painlessly between gui and console applications.

**Comment by absrnd** [comment]
Thanks both. I think I need to get up to speed on the OpenGL redraw loop, and dig into the event loop code.. The DemoPhysics program calls physics-step every event callback and the function assumes an interval of (/ 1. 60.) second.
