### ISSUE TITLE
I can't build the "DemoHelloWorld" App for Android in Fedora Linux

### ISSUE THREAD

**Issue by egbaquela** [part-cw/lambdanative#88]
Hi, I try to build the "DemoHelloWorld" App for Android using the following instructions:

    ./configure DemoHelloWorld android
    make

But I get this error:

    ERROR: failed on file /opt/android-ndk-r10/platforms/android-3/arch-arm 
    BUILD FAILED - configure with verbose option for more information
    Reaping losing child 0x1487270 PID 31215 
    make: *** [all] Error 1
    Removing child 0x1487270 PID 31215 from chain.

The configuration of my setup file is:

    ## location of android SDK and NDK (linux or mac)
    ANDROIDSDK=`find /opt/android-sdk-*  -maxdepth 0 -print 2> /dev/null | tail -n 1`
    ANDROIDNDK=`find /opt/android-ndk-*  -maxdepth 0 -print  2> /dev/null| tail -n 1`
    # minimum version to support (a matching target must be installed)
    ANDROIDAPI=19
    #android target cpu, either arm (default), x86 or mips
    ANDROIDARCH=arm

I have android SDK 19,  the NDK is installed in "/opt/android-ndk-r10". The route "/opt/android-ndk-r10/platforms/android-3/arch-arm" does not exist, only exist the path "/opt/android-ndk-r10/platforms/android-L/arch-arm".

If i build apps for linux, the make works well.

**Comment by mgorges** [comment]
For a start which version of the NDK do you use - I am using 10e, which should be the latest and it works out of the box. Also could you post the directory listing for your `/opt/android-ndk-r10/platforms` folder? If it really only contains the `android-L` folder it is likely incomplete.

**Comment by egbaquela** [comment]
I use the 10c. And platforms only contain "android-L".
I'am going to unistall/re-install the NDK using the 10d revision.

**Comment by egbaquela** [comment]
It's work!!!
Thanks!!!
