### ISSUE TITLE
update str in glgui-button-string for toggle

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#89]
In https://github.com/part-cw/lambdanative/wiki/glgui-button-string
it is explained that str needs to updated through 'image. 

This does not seem to work for a toggle button with a list.
e.g. 
(glgui-widget-set! g w 'image (list " text1" "text2")) 

will convert a toggle button to a button with text1 as label
Best

**Comment by mgorges** [comment]
Hi Walter,
I think the argument for a toggle requires a list of lists, i.e. 
`(glgui-widget-set! g w 'image (list (list "a") (list "b")))`

Cheers Matthias

**Comment by karliwalti** [comment]
Matthias

Thank you for the answer.  I tried this and then I realized this could be done with a map which works for me now:
(glgui-widget-set! g w 'image (map list (list ("a" "b"))))

Best

**Comment by mgorges** [comment]
It would be great if you could add this as an example to the Wiki entry. Thanks.

**Comment by karliwalti** [comment]
Ok, with pleasure! Did not realize that I could edit the wiki.

**Comment by mgorges** [comment]
Anyone on Github can to the Wiki, which we had hoped would help complete the documentation.
