### ISSUE TITLE
callback of glgui-inputlabel not executed

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#91]
How can the glgui-inputlabel callback be invoked after taping on the inputlabel (when focus changes)?

Currently, it is only called by clicking on the label and then pressing enter which is not available on touchscreens.

**Comment by mgorges** [comment]
Consider if ['aftercharcb](https://github.com/part-cw/lambdanative/blob/master/modules/ln_glgui/label.scm#L307) would work for you? In [wiki/glgui-label](https://github.com/part-cw/lambdanative/wiki/glgui-label) it is listed as an optional attribute, which if set to a procedure and when focus is true, a procedure is called after each character is typed or deleted.

**Comment by mgorges** [comment]
Also almost all keypads in [modules/ln_glgui/keypad.scm](https://github.com/part-cw/lambdanative/blob/master/modules/ln_glgui/keypad.scm) have a return key, which will call the `'callback` procedure upon press.

**Comment by karliwalti** [comment]
Thank you for the suggestions. It would be useful to open the keypad once
focus is set. So no character or enter can be entered yet.

**Comment by karliwalti** [comment]
Thank you for the commit. I was just preparing a pull request realizing that you changed exactly the same 3 lines!
