### ISSUE TITLE
DemoHelloWorld for android x86

### ISSUE THREAD

**Issue by GermanGT** [part-cw/lambdanative#93]
Hi all. I'm trying to build the DemoHelloWord for android x86. Since virtual device for x86 run fast I want test my app with this architecture and later move this to arm.  But I get a lot of errors as show the attached file. Is lambanative incompatible with x86 or I'm doing something wrong?

Thanks
Germán

[log.txt](https://github.com/part-cw/lambdanative/files/110294/log.txt)

**Comment by mgorges** [comment]
Did you scrub the LambdaNative cache when switching architectures in SETUP from `ANDROIDARCH=arm` to `ANDROIDARCH=x86`? 

The easiest would be `make scrub`, followed by a rebuild of first a local app `./configure DemoHelloWorld;make` and then your android app `./configure DemoHelloWorld android;make`. The more selective approach is to remove the `android` folder in the lambdanative-cache folder and then rebuild the android app?

**Comment by GermanGT** [comment]
Thanks for your help, `make scrub` solved the problem :+1:

**Comment by mgorges** [comment]
You could now also just make this another architecture to build for, e.g. `$cat targets/android/host_macosx_x86_64`
``` 
if [ $SYS_ANDROIDAPI -ge 21 ]; then
  SYS_CPU=x86_64
  ANDROIDARCH=x86_64
  APP_ABI=x86-64
  . $SYS_ROOT/targets/android/_host_macosx
else
  vecho "WARNING: ARM64 requires a minimum API of 21 to build"
  . $SYS_ROOT/targets/android/host_macosx_arm
fi
```
