### ISSUE TITLE
Inputlabel labels are suffixed with spaces, lead to inconsistency and ultimately segfault in rendering

### ISSUE THREAD

**Issue by mhueser** [part-cw/lambdanative#96]
I am on the most recent commit of LambdaNative. I experienced multiple issues with the inputlabel GLGUI widget, here compiled for Linux.

(a) When a label is added that overflows the width of the inputlabel, then the white blinking cursor can overshoot the left boundary of the widget.

(b) Manually added labels are not honored and suffixed with a space, the following code gives a surprising result:

CODE:

(print_flush "CURRENT LABEL: [") (print_flush (glgui-widget-get personal_data_group w 'label)) (print_flush "]\n")
 (glgui-widget-set! personal_data_group w 'label (string-trim (glgui-widget-get personal_data_group w 'label)))
  (print_flush "CURRENT LABEL: [") (print_flush (glgui-widget-get personal_data_group w 'label)) (print_flush "]\n")

OUTPUT: 

CURRENT LABEL: [ALFONSO UGARTE ]
CURRENT LABEL: [ALFONSO UGARTE ]

where expected output:

CURRENT LABEL: [ALFONSO UGARTE ]
CURRENT LABEL: [ALFONSO UGARTE]

Further down the line it leads to a segmentation fault when the position of the white cursor is determined in the function <glgui:label-draw> because we index outside of the string with function -sublist- . Somehow there is an inconsistency of how long the label string is and how long the internal of inputlabel assume it is.

**Comment by mhueser** [comment]
;; Prints a string to the screen on Linux. On Android logs to the lowest
;; possible verbosity level 0 so that the messages can be ignored.
(define (print_flush str)
  (if (string=? (system-platform) "android") (log-debug str 0) (display str))
)

**Comment by mhueser** [comment]
CLOSED because unspecific; Problem (b) was caused by special Unicode characters which were not handled by INPUTLABEL functions. I will investigate this further before re-opening.

**Comment by mgorges** [comment]
Can confirm (a), which allows you to position the cursor to the left of the input label if you have access to an actual keyboard. The position, where string edits happen, seem to be correct. Were you expecting the string to scroll when the cursor goes off screen so you can see text surrounding the cursor?

Sorry, but I can't reproduce (b) with your example, as there is no padding in my version of the label code - can you provide the u8vector of the string which caused this issue for you? I'd suspect that the error might actually be in `string-trim`, which looks for and removed only `#\space`.

**Comment by mhueser** [comment]
Sorry about posting not the exact code point representation. What looked like a space was actually a non-breaking space (UTF8 code point 160) and was not trimmed, probably right so, by (string-trim str). I thought about using (char-whitespace? chr) but this returns FALSE for this character. 

More generally, a label string (de-identified) which causes a SEGFAULT when the field is touched with the cursor (and only then) is the following

(display) PRINTABLE REPRESENTATION: [RRRRRRRRRRR RRRRRÑRRRRRRRRR]
STRING LENGTH as reported by (string-length): [28] (which is +1 of expected because 209 is probably encoded by two bytes.)
UNICODE REPRESENTATION: [(82 82 82 82 82 82 82 82 82 82 82 32 82 82 82 82 82 209 82 82 82 82 82 82 82 82 82)]

The other problematic case (probably an instance of the same problem: non-ASCII code-points) was the non-breaking space, but this could be mitigated by writing a custom string cleaning function.

**Comment by mgorges** [comment]
According to R4RS, the whitespace characters are space, tab, line feed, form feed, and carriage return. Hence, the non-breaking space would not be covered. 

Unfortunately, standard gambit string operations are not utf8 aware, which is why [ln_core/utf8string.scm](../blob/master/modules/ln_core/utf8string.scm) was created. It'll take a bit of refactoring to make `label` more utf8 supported, which we could look into in the future. Thanks!
