### ISSUE TITLE
Short interview about LambdaNative for InfoQ.com

### ISSUE THREAD

**Issue by sdesimone** [part-cw/lambdanative#99]
Hi,

I am sorry for using this means to get in touch, but I could not find any contact page/address.

My name is Sergio De Simone and I would like to cover LambdaNative for InfoQ.com and would love to include a short interview with some qualified person about the project. You can find my questions below:

1 - On LambdaNative web page, you claim that LambdaNative makes it possible to hugely reduce development time in comparison to Java and C/C++? Could you elaborate more? Under which conditions was that the case? What are the specific advantages brought by LambdaNative that enable shrinking development time?

2 - What kind of applications/developers are you targeting with LambdaNative? (E.g., is there any specific reason why the apps you mention on your web page are all health-related? Are you targeting specific markets?)

3 - What is LambdaNative's approach to accessing OS-specific resources such as UI widgets, sensors, etc.? Along the same line, what kind of interoperability with the host OS does LambdaNative provide (e.g., using a native iOS Framework)?

4 - What's on LambdaNative roadmap?

Thank you a lot in advance.
Sergio

zergyo@gmail.com
http://www.infoq.com/author/Sergio-De-Simone

**Comment by clpetersen** [comment]
Hi Sergio,
thanks for getting in touch. We are happy to participate in an interview, I'll email you separately for details. 
Chris

**Comment by mgorges** [comment]
The resulting article can be found at http://www.infoq.com/news/2016/03/lambdanative-cross-platform-dev
